### ISSUE TITLE
exec returns EACCESS

### ISSUE THREAD

**Issue by tux-mind** [cSploit/android#1]
cannot start programs over certain devices, where exec returns EACCESS.

**Comment by tux-mind** [comment]
can someone test [this pre-release apk](https://github.com/cSploit/android/releases/tag/v1.2.4-issue1%2Bv1) ?

uninstalling or delete app data is not required.

thank you in advance :blush:

**Comment by mcilya** [comment]
Still cannot start process 
Catlog https://www.dropbox.com/s/cxdun06m7e7u5xn/2015-01-12-23-24-51.txt?dl=0

csploitd.log https://www.dropbox.com/s/nz0p1k2dm7mfp6p/cSploitd.log?dl=0

**Comment by tux-mind** [comment]
it didn't installed new tools...
can you clear app data or uninstall and re-install ?

i changed the app version to `1.2.4-issue1+v1` thus to make it reinstall the binaries, but it didn't work...

thanks in advance @mcilya

**Comment by mcilya** [comment]
I think it doesnt work on my phone
It says cannot start process on startup
Log https://www.dropbox.com/s/silan6zugs53x21/2015-01-13-07-40-20.txt?dl=0

Csploitd.log https://www.dropbox.com/s/nz0p1k2dm7mfp6p/cSploitd.log?dl=0

**Comment by alexmanner** [comment]
Hi Tux-mind. It is the same for me. CSploit will immediately crash after I have opened it. I have a Nexus 6 which runs 5.02.

Many thanks for your great work.

**Comment by mcilya** [comment]
@alexmanner your phone is affected by #24

**Comment by alexmanner** [comment]
@mcilya Yes, you are right, thanks for this. :-)

**Comment by mcilya** [comment]
@alexmanner no problems :wink:

**Comment by tux-mind** [comment]
@mcilya can you post `/data/data/org.csploit.android/files/start_daemon.log` ?

the issue hasn't been fixed...

**Comment by tux-mind** [comment]
@cmayer0087 did you test the mount solution ?

```sh
mount -o remount,rw /
mkdir /cSploit
mount -o bind /data/data/org.csploit.android/files /cSploit
mount -o remount,ro /
cd /cSploit
./cSploitd
```

maybe `d_path` kernel API still return `/data/data/org.csploit.android/files/cSploitd` instead of `/cSploit/cSploitd` .

please help me debug this issue with your device, without an affected device in my hands it's very hard to fix.

**Comment by mcilya** [comment]
@tux-mind start_daemon.log have 0 bytes weight
screenshot of 0 bytes https://copy.com/9v1kfYusiOqbgBcN

**Comment by tux-mind** [comment]
ok, this means that issue 1 hasn't been found on your device by the `known-issues` program...

let me fix it...

**Comment by mcilya** [comment]
Any ideas about it?

**Comment by tux-mind** [comment]
yeah, `fork(2)` it's translated to `clone(2)` even if the program does not use threads because the bionic libc has pthreads (badly) built in.

i'm moving the check from `fork (2)` to `execvp(3)` .

**Comment by tux-mind** [comment]
@mcilya [ready](https://github.com/cSploit/android/releases/tag/v1.2.4-issue1%2Bv2).

thanks for your patience :wink:

**Comment by mcilya** [comment]
@tux-mind i have email notifications :wink: 
i found start_daemon.log on /sdcard https://copy.com/0fbIkeGS9Bjf4P2O

**Comment by tux-mind** [comment]
@mcilya does it works now ?
the mount workaround should have been applied just before starting the daemon.

**Comment by mcilya** [comment]
still cannot start process
cSploitd.log says on_cmd_start: execvp: Permission denied

**Comment by tux-mind** [comment]
> still cannot start process + it starts longer

lol

TOTAL FAIL XD

i need that @cmayer0087 , which have an affected device, tell me which method to use for fix this issue.

he suggested the mount solution but didn't tried it.
probably it does not work and we need to find another way.

**Comment by mcilya** [comment]
i tried
mount -o remount,rw /
mkdir /cSploit
mount -o bind /data/data/org.csploit.android/files /cSploit
mount -o remount,ro /
cd /cSploit
./cSploitd
it doesnt work + cant rmdir /cSploit

**Comment by Rogue86** [comment]
So there is no way to make it work on 5.0.0 and above...

**Comment by tux-mind** [comment]
no @Rogue86 I have to finish the network-monitor, after that i will install lollipop on my Nexus 4.

once I installed lollipop on my phone i will be able to make it work on 5.0 and above.

so please wait :grin:

will be great if @cmayer0087 can find out a solution for this problem.

**Comment by mcilya** [comment]
tried 1.3.0 still cannot start process if you want i can post logcat :wink:

**Comment by tux-mind** [comment]
@mcilya yep, i didn't fixed this issue with last version, you logcat is not necessary, thanks anyway for you availability :blush: 

this problem still here. I have to put my paws on an affected device. I have a friend whit a Galaxy S3 Zoom ( it have an HUGE camera on the back ).

I will ask him if I can play with it for a little.
