### ISSUE TITLE
The newest verison of msf on this csploit its not the newest msf on the github

### ISSUE THREAD

**Issue by GetRektBoy724** [cSploit/android#1006]
DEVICE:
Samsung galaxy tab a

OS version:android v5

**cSploit version:**
Newest

**busybox** *(installed or not):*
Installed

**Rooted with supersu?**
Yes

**logcat** *(filter it!):*
[How-to guide](https://forum.xda-developers.com/showthread.php?t=1726238)

------------------------------------------------------------------------------------------------------------------------------

**Daemon specific questions**

Go version:

OS:

Using Docker (incase of unofficial build.)

Actions performed:

Logs:
------------------------------------------------------------------------------------------------------------------------------

**Issue:**
*Remember to search for issues alike before creating new one!*

**Comment by GitClo** [comment]
:(
