### ISSUE TITLE
Permission Problems

### ISSUE THREAD

**Issue by Chnorzy** [cSploit/android#102]
After installing cSploit and start it up it asks if I want to install the core. After a long time it starts extracting for a while. After this I got the message that I need to be root without beeing ask for root permission.
I could fix this for me with changing superSU general settings for root access to always allow instead of asking for each app. This is not a good solution. 
I installed superSU just because I got this errors in cSploit. I had root enabled in dev settings.

of course I changed back this settings after the core was installed and it seems to work.

I'm on Adroid 5.0.2
CyanogenMod 12
at old HTC Desire HD

I also saw the same problem with missing permissions after extracting core on rootet Stock Samsung Galaxy S4 with Android 5.0.x from a friend. Didn't try this fix there.

**Comment by Systemad** [comment]
This might be cSploit SuperSu but I had same problems in other root apps but not on cSploit.

**Comment by sorano** [comment]
Try out the latest version with updated supersu and busybox installed in the correct path.
Then if it is not working put the logfiles on pastebin and reopen the issue.
