### ISSUE TITLE
Dead?

### ISSUE THREAD

**Issue by UltraBlackLinux** [cSploit/android#1040]
Is this project Dead?

**Comment by theoneandonly-vector** [comment]
if somebody picks it up, it's not anymore..
currently there's no one working on it.

**Comment by theoneandonly-vector** [comment]
also it's most likely much easier to just use the same tools as on a pc through termux or linuxdeploy/nethunter.

**Comment by Systemad** [comment]
Also this
https://github.com/kimocoder/qualcomm_android_monitor_mode

**Comment by theoneandonly-vector** [comment]
nice thx for the link :)
