### ISSUE TITLE
Não está detectando o MSF

### ISSUE THREAD

**Issue by paulo830** [cSploit/android#1052]
DEVICE:

OS version:

**cSploit version:**

**busybox** *(installed or not):*

**Rooted with supersu?**

**logcat** *(filter it!):*
[How-to guide](https://forum.xda-developers.com/showthread.php?t=1726238)

------------------------------------------------------------------------------------------------------------------------------

**Daemon specific questions**

Go version:

OS:

Using Docker (incase of unofficial build.)

Actions performed:

Logs:
------------------------------------------------------------------------------------------------------------------------------

**Issue:**
*Remember to search for issues alike before creating new one!*

**Comment by Silur** [comment]
please follow the issue template and use english
