### ISSUE TITLE
Csploit core wont download

### ISSUE THREAD

**Issue by kenodroid** [cSploit/android#1053]
DEVICE:lg d415

OS version:

**cSploit version:**

**busybox** *(installed or not):*

**Rooted with supersu?**yes

**logcat** *(filter it!):*
[How-to guide](https://forum.xda-developers.com/showthread.php?t=1726238)

------------------------------------------------------------------------------------------------------------------------------

**Daemon specific questions**

Go version:

OS:

Using Docker (incase of unofficial build.)

Actions performed:

Logs:
------------------------------------------------------------------------------------------------------------------------------

**Issue:**
*Remember to search for issues alike before creating new one!*

**Comment by Silur** [comment]
issue does not follow guideline, I'm closing this due to lack of information
