### ISSUE TITLE
RCP Parado 

### ISSUE THREAD

**Issue by woosterlol** [cSploit/android#1054]
DEVICE:
Todas as vezes que entro já com o ruby e msf instalado o RCPD para após alguns minutos
tento refazer o teste RCPD só que continua a falhar alguém poderia solucionar meus problemas.
OS version:J7 PRIME Android:8.1.0

**cSploit version:** 

CSPLOIT V.1.6.6-rc.2 

**busybox** *(installed or not):*

**Rooted with supersu?**
Root magisk 

**logcat** *(filter it!):*
[How-to guide](https://forum.xda-developers.com/showthread.php?t=1726238)

------------------------------------------------------------------------------------------------------------------------------

**Daemon specific questions**

Go version:

OS:

Using Docker (incase of unofficial build.)

Actions performed:

Logs:
------------------------------------------------------------------------------------------------------------------------------

**Issue:**
*Remember to search for issues alike before creating new one!*

**Comment by Silur** [comment]
Please keep issues in english so the non-spanish speaking maintainers can actually help you :)
