### ISSUE TITLE
Missing last letter in Computer/Network name

### ISSUE THREAD

**Issue by Foul** [cSploit/android#108]
When Csploit is launched, all the scanned network in Capital name, are missing the last letter !

My own network name is FOULNUX, but in cSploit it's FOULNU
same for my french box : FREEBOX become FREEBO
everything in minus is fine...

 1.5.0 installed on Nexus 9 5.0.1

**Comment by fat-tire** [comment]
Could the problem be that the text was wrapping around and being overlapped on the next line and so you aren't seeing it?  Do you still see this issue with recent nightlies (say, starting tomorrow?)

**Comment by Foul** [comment]
Still happening with latest build (1.5.3)

**Comment by sorano** [comment]
Just tested this out and can confirm.
Still an issue in 1.5.4.

Like @Foul writes it affects hostnames written in caps only.

My HTPC shows as OPENELE (hostname OPENELEC).

**Comment by tux-mind** [comment]
it's an issue with cSploitDaemon cSploitCommon, not java, still in progress.

**Comment by Foul** [comment]
Still present in 1.6.0 RC1

**Comment by tux-mind** [comment]
fixed in cSploit/network-radar@bda0181e30ee9fe63c55a438a27507a9bc4b227c
