### ISSUE TITLE
Submit issue from cSploit is 404

### ISSUE THREAD

**Issue by Foul** [cSploit/android#109]
In cSploit, Submit Issue gives https://github.com/evilsocket/csploit/issues/new and a nice 404 error ;)

**Comment by fabinhojcr** [comment]
@Foul now just wait for the next release of cSploit

**Comment by tux-mind** [comment]
@fabinhojcr thanks for the fix :relieved: 

BTW when a resource is not to translate ( like links ) you can define it in `values/string.xml` and remove it from all other resource files.

in this way you/me/someone_else have to edit only one file when changing this kind of resources.

thanks again for your help :smiley: 

I'll create a team page as I have some free time. It will be great if you enter a quick description of you :grinning:

**Comment by fabinhojcr** [comment]
to me is a pleasure to help, I am with little spare time but always as you can I will help. Also I will follow your advice í ½í¸
