### ISSUE TITLE
ettercap returned #237 when password sniffer turned on

### ISSUE THREAD

**Issue by MerlinMerlin** [cSploit/android#110]
When password sniffer is turned on, it instantly turn off and "ettercap returned #237" is displayed.

Root and Busybox installed. I tried on KitKat and Lollipop but same thing happened

My logcat: http://pastebin.com/VGCiWcgr

**Comment by Klocko** [comment]
I'm in the same boat as you :(

**Comment by elitecompany** [comment]
I also got this message. I think it's because of the phone chipset. I read that the phones with the RTL8187 work well with ettercap. I am using a Motorola Moto G, and you?

**Comment by elitecompany** [comment]
Broadcom WiFi Chipsets works well on monitor mode... Does anyone know which phones are compatible with ettercap?

**Comment by MerlinMerlin** [comment]
I am, in fact, also using a Motorolla moto G (XT1032).

**Comment by Klocko** [comment]
I'm using a Nexus 6.

**Comment by Nauscar** [comment]
I'm using a Nexus 5 on 5.1. Same error message.

**Comment by tux-mind** [comment]
sorry for the late reply, confirmed as affect many users.

I bet that your chipset does not support the `SIOCGIFHWADDR` command, which is needed by `pcap_open_live`.

I need to investigate moreover.

**Comment by tux-mind** [comment]
fixed :sunglasses:

**Comment by elitecompany** [comment]
I have a Motorola XT1068. The ettercap message remains :(  in password sniffer
"Ettercap returned #237"

**Comment by lolzballs** [comment]
I have a OnePlus One, ettercap message remains as well.

**Comment by tux-mind** [comment]
with the latest nightly build ?

**Comment by lolzballs** [comment]
Ok, confirmed working on nightly build.

**Comment by scatteril** [comment]
thank you but the link to the nightly build gives error 404

**Comment by tux-mind** [comment]
@scatteril we are working on the build server, please hang on :grin:
