### ISSUE TITLE
[enhancement] Add SSL-Strip

### ISSUE THREAD

**Issue by Klocko** [cSploit/android#115]
Hi, when will you add SSL-Strip to cSploit?

Also, this is my first time submitting an issue on GitHub, how do I add labels?

**Comment by xaitax** [comment]
It is implemented for ages.

**Comment by BoBeR182** [comment]
SSL-Strip has been included for a while, if you are finding it is not working please file a bug report. Be aware that with certain HTTPS security protocols like https://en.wikipedia.org/wiki/HTTP_Strict_Transport_Security (HSTS) that make SSL-Strip useless.
