### ISSUE TITLE
CSploit are crached if u open traceroute.

### ISSUE THREAD

**Issue by 0MazaHacka0** [cSploit/android#118]
On my android 4.4.4 if i open traceroute csploit are crashed.

**Comment by tux-mind** [comment]
uh oh. fixing it now. it's a core issue.

thanks for the report :blush:

**Comment by tux-mind** [comment]
after 3 hours of debugging and searching around the web I found the bug :tada: 

`org.csploit.android.event.Hop` constructor takes a long as elapsed microseconds, but it arrives as unsigned int ( 32 bit ) from the NMap handler, this make the JVM/JNI crazy, them don't understand how to convert an `uint32_t` to a signed long.... **FACEPALM**.

I've already fixed it, but I have to check if this problem affect other snippet of code before committing.
I'll do it tomorrow.

thanks for the report @0MazaHacka0 , really appreciated :blush:

**Comment by 0MazaHacka0** [comment]
Thank you @tux-mind , u are the best developer!
