### ISSUE TITLE
Cant change msf rpc port

### ISSUE THREAD

**Issue by 0MazaHacka0** [cSploit/android#122]
Android 4.4.4. Csploit 1.5.3. If u change port on which msf rpc work you cant change it on future. For example, i change port to 44444, and after that port is 8080 and i cant change this.

**Comment by sorano** [comment]
This issue is still existing in 1.5.4.

Reproduce:
Settings --> RPC port --> Change the default to port of your choice, then press OK.

Tap RPC port again, to verify your new port is correct. It is now replaced with port 8080.
