### ISSUE TITLE
Bug in UI.

### ISSUE THREAD

**Issue by 0MazaHacka0** [cSploit/android#136]
Then you stop MSF RPCD it show message "MSF RPCD is stopped" but if you start RPCD this message don't show. Also don't show message if connection to RPCD daemon is failed. It shows only if you stop RPCD. And thats why u can't know lucky or no connect to RPC daemon.

**Comment by MrChesko** [comment]
It shows but cSploit does connect to server ~ 3-4 minutes, so you will see a message after 3-4 minutes

**Comment by Systemad** [comment]
Sometimes if you have been waited for msf to start for couple of minutes and then press Stop msf is shows "Failed to connect msf rpcd"
I dont think this are bugs, and this wouldn't be  about the ui

**Comment by sorano** [comment]
Closing this old issue.
MSF was solved in #205
