### ISSUE TITLE
Inform user that ruby/msf directories can be wiped

### ISSUE THREAD

**Issue by CHEF-KOCH** [cSploit/android#14]
Hello,  thanks for the new dsploit. But I found a very critical problem that is reproducable on my devices. 
- csploit 1.2.3rc and solid explorer needed (should works with other file manager apps too) 
- open csploit, now let it try to download both packages
- the release package will now return 1 code
- re-try to download it,  now it take some time on the extracting process
- open now solid explorer and try to create a folder dsploit or csploit on the internal sdcard, solid say now it can't create a folder 
- reboot
- open csploit again 
- open solid explorer and create the folders
- now let csploit re-download the realease
- congrats your sdcard is now almost empty,  it only shows folders which are in use, like whatsapp or such

Here is a debug but I don't know if this was captured.
https://mega.co.nz/#!AUdC2ASL!FIW5wJgGWcrLdIyHfPoLTbizVmaq4FJQVUt5Hm40mQU

**Comment by sorano** [comment]
There is now a prompt that ask you to proceed with deletion before performing it.

See #174

**Comment by CHEF-KOCH** [comment]
Thank you.
