### ISSUE TITLE
Update Ruby error

### ISSUE THREAD

**Issue by maximumbr** [cSploit/android#142]
Galaxy s4 i9505g google edition 4.4.4 update ruby error.
"An error occurred while downloading the update."

**Comment by TheNormalnij** [comment]
Explay A500 4.2. same error

**Comment by akremche** [comment]
the same ERROR ( S4 I9505 )

**Comment by mandriva91** [comment]
same here, s4 i9505

**Comment by sorano** [comment]
Duplicate of #205
