### ISSUE TITLE
heart attack csploit 1.5.3 android 4.2.1

### ISSUE THREAD

**Issue by antoniosilvawww** [cSploit/android#143]
Android Version: 4.2.1
Kernel Version: 3.4.5
Model number: bq Aquaris 5 HD
cSploit Version: 1.5.3

Core is not installed, the application will just check for updates. New version found!

Core version 1.0.5 is available, do you want to upgrade ?

(Pressed "Yes")

Checking...
Extracting...

(Granted cSploit root permission)

Initialization Error
heart attack

(Pressed "ok", and app closed)

---Attachment of "csploit-debug-error.log"---
org.csploit.android.core.ChildManager$ChildNotStartedException: cannot start commands
	at org.csploit.android.core.ChildManager.async(ChildManager.java:83)
	at org.csploit.android.tools.Tool.async(Tool.java:55)
	at org.csploit.android.tools.Tool.run(Tool.java:33)
	at org.csploit.android.tools.Raw.run(Raw.java:51)
	at org.csploit.android.tools.Raw.run(Raw.java:56)
	at org.csploit.android.core.UpdateService.wipe(UpdateService.java:599)
	at org.csploit.android.core.UpdateService.extract(UpdateService.java:1071)
	at org.csploit.android.core.UpdateService.onHandleIntent(UpdateService.java:1427)
	at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:65)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:153)
	at android.os.HandlerThread.run(HandlerThread.java:60)
org.csploit.android.core.ChildManager$ChildNotStartedException: cannot start commands
	at org.csploit.android.core.ChildManager.async(ChildManager.java:83)
	at org.csploit.android.tools.Tool.async(Tool.java:55)
	at org.csploit.android.tools.Tool.run(Tool.java:33)
	at org.csploit.android.tools.Raw.run(Raw.java:51)
	at org.csploit.android.tools.Raw.run(Raw.java:56)
	at org.csploit.android.core.UpdateService.wipe(UpdateService.java:599)
	at org.csploit.android.core.UpdateService.extract(UpdateService.java:1071)
	at org.csploit.android.core.UpdateService.onHandleIntent(UpdateService.java:1427)
	at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:65)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:153)
	at android.os.HandlerThread.run(HandlerThread.java:60)

**Comment by antoniosilvawww** [comment]
ok, I tried to install again today the nightly release and it worked :D, but, when I do "Start MetaSploit RPCD" it says "cannot start process" in toast :/

**Comment by antoniosilvawww** [comment]
In the latest version I am back to the heart attack *sigh*

**Comment by John-Kumar** [comment]
Same Problem here "Initialization Error - heart attack" can not update...Samsung Galaxy Core 2 SM-G355H

**Comment by DeveloppSoft** [comment]
Please send us your logs  (just enable "logging" into the settings

**Comment by antoniosilvawww** [comment]
Hi @DeveloppSoft, sorry the delay, here it is:

org.csploit.android.core.ChildManager$ChildNotStartedException: cannot start commands
	at org.csploit.android.core.ChildManager.async(ChildManager.java:83)
	at org.csploit.android.tools.Tool.async(Tool.java:55)
	at org.csploit.android.tools.Tool.run(Tool.java:33)
	at org.csploit.android.tools.Raw.run(Raw.java:51)
	at org.csploit.android.tools.Raw.run(Raw.java:56)
	at org.csploit.android.core.UpdateService.wipe(UpdateService.java:599)
	at org.csploit.android.core.UpdateService.extract(UpdateService.java:1071)
	at org.csploit.android.core.UpdateService.onHandleIntent(UpdateService.java:1427)
	at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:65)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:153)
	at android.os.HandlerThread.run(HandlerThread.java:60)

**Comment by antoniosilvawww** [comment]
Oh, forgot to mention, it happens just after decompressing core.tar.xz, I mean, I open csploit, it asks to download the core, it downloads, decompresses and it haves an heart attack :p

**Comment by John-Kumar** [comment]
Sorry for late reply, i have creating logs problem solved now..:)
Sir, If you can solved my problem i will be very thankful to you
Device : Samsung Galaxy Core II SM-G355H
Error Logs...

06-24 21:14:01.747 V/ApplicationPolicy(646): isApplicationStateBlocked userId 0 pkgname org.csploit.android
06-24 21:14:01.767 V/WindowManager(646): Input focus app has changed to AppWindowToken{427fcda0 token=Token{4231d118 ActivityRecord{42446908 u0 org.csploit.android/.MainActivity t32}}}
06-24 21:14:01.977 D/CSPLOIT[core.System.init](6313): initializing System...
06-24 21:14:02.137 D/CSPLOIT[core.UpdateChecker.run](6313): Service started.
06-24 21:14:02.137 D/CSPLOIT[core.System.readFirstLine](6313): /data/data/org.csploit.android/files/msf/VERSION: open failed: ENOENT (No such file or directory)
06-24 21:14:02.137 D/CSPLOIT[net.RemoteReader.run](6313): RemoteReader[api.github.com] started
06-24 21:14:02.137 I/CSPLOIT[net.RemoteReader.run](6313): fetching 'https://api.github.com/repos/cSploit/android/releases'
06-24 21:14:02.177 V/WindowManager(646): Input focus window has changed from null to Window{42562548 u0 org.csploit.android/org.csploit.android.MainActivity}
06-24 21:14:04.287 D/CSPLOIT[core.UpdateService.isUpdateAvailable](6313): localVersion   = 1.5.3
06-24 21:14:04.287 D/CSPLOIT[core.UpdateService.isUpdateAvailable](6313): remoteVersion  = 1.5.3
06-24 21:14:04.287 D/CSPLOIT[core.System.readFirstLine](6313): /data/data/org.csploit.android/files/VERSION: open failed: ENOENT (No such file or directory)
06-24 21:14:04.297 I/CSPLOIT[net.RemoteReader.run](6313): fetching 'https://api.github.com/repos/cSploit/android.native/releases'
06-24 21:14:04.817 W/CSPLOIT[core.UpdateService.isCoreUpdateAvailable](6313): unsupported platform ( android19.armeabi-v7a )
06-24 21:14:04.817 D/CSPLOIT[core.UpdateService.isCoreUpdateAvailable](6313): trying with 'android16.armeabi-v7a'
06-24 21:14:04.817 D/CSPLOIT[core.UpdateService.isCoreUpdateAvailable](6313): localVersion   = null
06-24 21:14:04.817 D/CSPLOIT[core.UpdateService.isCoreUpdateAvailable](6313): remoteVersion  = 1.0.5
06-24 21:14:04.827 D/CSPLOIT[core.UpdateChecker.run](6313): Service stopped.
06-24 21:14:04.887 V/WindowManager(646): Input focus window has changed from Window{42562548 u0 org.csploit.android/org.csploit.android.MainActivity} to Window{425d0b60 u0 Update Available}
06-24 21:14:05.887 V/WindowManager(646): Input focus window has changed from Window{425d0b60 u0 Update Available EXITING} to Window{42562548 u0 org.csploit.android/org.csploit.android.MainActivity}
06-24 21:14:05.917 I/CSPLOIT[core.UpdateService.verifyArchiveIntegrity](6313): verifying archive integrity
06-24 21:14:26.997 I/CSPLOIT[core.UpdateService.haveLocalFile](6313): file already exists: '/storage/emulated/0/core.tar.xz'
06-24 21:14:26.997 D/dalvikvm(6313): Trying to load lib /data/app-lib/org.csploit.android-1/libcSploitCommon.so 0x41a699b0
06-24 21:14:26.997 D/dalvikvm(6313): Added shared lib /data/app-lib/org.csploit.android-1/libcSploitCommon.so 0x41a699b0
06-24 21:14:26.997 D/dalvikvm(6313): No JNI_OnLoad found in /data/app-lib/org.csploit.android-1/libcSploitCommon.so 0x41a699b0, skipping init
06-24 21:14:27.007 D/dalvikvm(6313): Trying to load lib /data/app-lib/org.csploit.android-1/libcSploitClient.so 0x41a699b0
06-24 21:14:27.007 D/dalvikvm(6313): Added shared lib /data/app-lib/org.csploit.android-1/libcSploitClient.so 0x41a699b0
06-24 21:14:27.007 E/cSploitClient(6313): connect_unix: connect: No such file or directory
06-24 21:14:27.007 I/CSPLOIT[core.UpdateService.extract](6313): extracting '/storage/emulated/0/core.tar.xz' to '/data/data/org.csploit.android/files'
06-24 21:14:27.017 E/cSploitClient(6313): start_command: not authenticated
06-24 21:14:27.017 E/CSPLOIT[core.System.errorLogging](6313): cannot start commands
06-24 21:14:27.017 E/CSPLOIT[core.System.errorLogging](6313): org.csploit.android.core.ChildManager$ChildNotStartedException: cannot start commands
06-24 21:14:27.017 E/CSPLOIT[core.System.errorLogging](6313): 	at org.csploit.android.core.ChildManager.async(ChildManager.java:83)
06-24 21:14:27.017 E/CSPLOIT[core.System.errorLogging](6313): 	at org.csploit.android.tools.Tool.async(Tool.java:55)
06-24 21:14:27.017 E/CSPLOIT[core.System.errorLogging](6313): 	at org.csploit.android.tools.Tool.run(Tool.java:33)
06-24 21:14:27.017 E/CSPLOIT[core.System.errorLogging](6313): 	at org.csploit.android.tools.Raw.run(Raw.java:51)
06-24 21:14:27.017 E/CSPLOIT[core.System.errorLogging](6313): 	at org.csploit.android.tools.Raw.run(Raw.java:56)
06-24 21:14:27.017 E/CSPLOIT[core.System.errorLogging](6313): 	at org.csploit.android.core.UpdateService.wipe(UpdateService.java:599)
06-24 21:14:27.017 E/CSPLOIT[core.System.errorLogging](6313): 	at org.csploit.android.core.UpdateService.extract(UpdateService.java:1071)
06-24 21:14:27.017 E/CSPLOIT[core.System.errorLogging](6313): 	at org.csploit.android.core.UpdateService.onHandleIntent(UpdateService.java:1427)
06-24 21:14:27.017 E/CSPLOIT[core.System.errorLogging](6313): 	at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:65)
06-24 21:14:27.017 E/CSPLOIT[core.System.errorLogging](6313): 	at android.os.Handler.dispatchMessage(Handler.java:102)
06-24 21:14:27.017 E/CSPLOIT[core.System.errorLogging](6313): 	at android.os.Looper.loop(Looper.java:146)
06-24 21:14:27.017 E/CSPLOIT[core.System.errorLogging](6313): 	at android.os.HandlerThread.run(HandlerThread.java:61)
06-24 21:14:58.057 I/CSPLOIT[core.UpdateService.extract](6313): extraction completed
06-24 21:14:58.057 I/CSPLOIT[core.UpdateService.extract](6313): .nomedia created
06-24 21:14:58.077 E/cSploitClient(6313): connect_unix: connect: No such file or directory
06-24 21:14:58.177 E/cSploitClient(6313): connect_unix: connect: No such file or directory
06-24 21:14:58.187 E/CSPLOIT[core.UpdateService.onHandleIntent](6313): cannot connect to core daemon
06-24 21:14:58.227 D/CSPLOIT[core.UpdateService.finishNotification](6313): deleting notifications
06-24 21:14:58.227 V/WindowManager(646): Input focus window has changed from Window{42562548 u0 org.csploit.android/org.csploit.android.MainActivity} to Window{41fb1dd8 u0 Initialization Error}
06-24 21:15:00.267 D/CSPLOIT[core.System.setForwarding](6313): Setting ipv4 forwarding to false
06-24 21:15:00.267 E/cSploitClient(6313): start_command: not authenticated
06-24 21:15:00.277 E/CSPLOIT[core.System.setForwarding](6313): cannot start commands
06-24 21:15:00.277 D/CSPLOIT[core.System.clean](6313): Releasing locks.

**Comment by DeveloppSoft** [comment]
@John-Kumar, when I read your logs I see that :06-24 21:14:04.817 W/CSPLOITcore.UpdateService.isCoreUpdateAvailable: unsupported platform ( android19.armeabi-v7a ).
So, maybe your phone is unsupported for the latest core's version and csploit try with an older version, maybe that is not work with the current version officielle csploit.
Try to use a different apk  (the latest, or the nightly...).

PS: I know... My english is bad, but I am french.

**Comment by John-Kumar** [comment]
Thank you so much for your responding...Can you please show me another apk Link?

**Comment by DeveloppSoft** [comment]
Nightly build is here : http://rootbitch.cc/csploit/cSploit-nightly.apk.
Or make your choice here : https://github.com/cSploit/android/releases.
Please not it can solve or not your problem.

**Comment by John-Kumar** [comment]
Ok..thanks let me try

**Comment by antoniosilvawww** [comment]
The nightly link is offline... Tried with the latest release and the same happned, I have already tried with almost all of the releases before and always had some other problem if not the same. Anyway logs:

org.csploit.android.core.ChildManager$ChildNotStartedException: cannot start commands
	at org.csploit.android.core.ChildManager.async(ChildManager.java:83)
	at org.csploit.android.tools.Tool.async(Tool.java:55)
	at org.csploit.android.tools.Tool.run(Tool.java:33)
	at org.csploit.android.tools.Raw.run(Raw.java:51)
	at org.csploit.android.tools.Raw.run(Raw.java:56)
	at org.csploit.android.core.UpdateService.wipe(UpdateService.java:599)
	at org.csploit.android.core.UpdateService.extract(UpdateService.java:1071)
	at org.csploit.android.core.UpdateService.onHandleIntent(UpdateService.java:1427)
	at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:65)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:153)
	at android.os.HandlerThread.run(HandlerThread.java:60)

Is there any of I make things easier for you

**Comment by DeveloppSoft** [comment]
Same error.
For all who have this error : check busybox and if it doesn't work, give us
phone model.
Le 25 juin 2015 11:30, "antoniosilvawww" <notifications@github.com> a
écrit :

**Comment by antoniosilvawww** [comment]
sorry closing issue, that button is near comment on github mobile. I tried rhe nightly link but it is off, also tried almost all of the releases but those who do not have heart attack have some other kind of problem, the logs running the latests are:

org.csploit.android.core.ChildManager$ChildNotStartedException: cannot start commands
	at org.csploit.android.core.ChildManager.async(ChildManager.java:83)
	at org.csploit.android.tools.Tool.async(Tool.java:55)
	at org.csploit.android.tools.Tool.run(Tool.java:33)
	at org.csploit.android.tools.Raw.run(Raw.java:51)
	at org.csploit.android.tools.Raw.run(Raw.java:56)
	at org.csploit.android.core.UpdateService.wipe(UpdateService.java:599)
	at org.csploit.android.core.UpdateService.extract(UpdateService.java:1071)
	at org.csploit.android.core.UpdateService.onHandleIntent(UpdateService.java:1427)
	at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:65)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:153)
	at android.os.HandlerThread.run(HandlerThread.java:60)

Thanks in advance :)

**Comment by DeveloppSoft** [comment]
Same error.
For all who have this error : check busybox and if it doesn't work, give us
phone model.
Le 25 juin 2015 11:33, "antoniosilvawww" <notifications@github.com> a
écrit :

**Comment by antoniosilvawww** [comment]
BsuyBox seems to be working and updated.. any test that I can do to it?

**Comment by antoniosilvawww** [comment]
Wait wasn't updated, I am trying again

**Comment by DeveloppSoft** [comment]
I don't know. Maybe you can give us your phone model.
I will check that on mine.
Le 25 juin 2015 11:40, "antoniosilvawww" <notifications@github.com> a
écrit :

**Comment by antoniosilvawww** [comment]
The same happens...

**Comment by antoniosilvawww** [comment]
I wrote the model on the first post (when opened thw issue):

Android Version: 4.2.1
Kernel Version: 3.4.5
Model number: bq Aquaris 5 HD

**Comment by DeveloppSoft** [comment]
Sorry, I forget
Le 25 juin 2015 11:43, "antoniosilvawww" <notifications@github.com> a
écrit :

**Comment by antoniosilvawww** [comment]
No problem, look if there is anything more that I can do please let me know, I would be happy if I can help, and thanks for everything :)

**Comment by DeveloppSoft** [comment]
Of course, me too :).
Le 25 juin 2015 11:47, "antoniosilvawww" <notifications@github.com> a
écrit :

**Comment by DeveloppSoft** [comment]
Core successfully installed on my wiko ozzy (Android 4.2.2)

**Comment by DeveloppSoft** [comment]
Have you another phone/tab to test it ?

**Comment by antoniosilvawww** [comment]
No, I only have the one I am using, but if you need me to test again another compiled version I am ready... (and sorry for go away before 2minutes pass...)

**Comment by Megaeloelo** [comment]
Can you write a step-by- step how to install busybox ?
I have a problem just with that.

**Comment by antoniosilvawww** [comment]
download it from play store, open it, click on the button install, it will install, make sure it is the latest version of it, and that it say there was no errors installing it, if you have terminal emulator, you can also try some command (from the linux bash shell for example) that busybox adds ^_^ saying by head, but it is a very intuitive process ;)

**Comment by Megaeloelo** [comment]
Maybe the installer does not install everything

**Comment by DeveloppSoft** [comment]
Wrong, on some phones / tab it install core &ruby but on other devices, it
install nothing, I don't know why, but in the logs we can see that the core
is uncompatible with them.

**Comment by antoniosilvawww** [comment]
And is there any workaround, like a manual way to install the core?

**Comment by DeveloppSoft** [comment]
I think not, for the moment...
Le 2 juil. 2015 02:00, "antoniosilvawww" <notifications@github.com> a
écrit :

**Comment by Megaeloelo** [comment]
If you do not have SuperSu and, for example, KingoUser then core not unpack. Sorry for bad english :)

**Comment by antoniosilvawww** [comment]
The solution present by Megaeloelo works, yet another problem occurred, Metasploit won't install, I will open an issue report tomorrow with more details about, and I believe it is safe to close this one :) , Thanks you all by the whole support ^^
