### ISSUE TITLE
problem with gems msf installation

### ISSUE THREAD

**Issue by bauermateus** [cSploit/android#144]
hey, i'm not none expert in Android and nothing, but i want to help u and u help me... i updated core, ruby, and msf, but when finish extracting msf , it stuck on installing gems to MSF... can u help me? My phone is a motorola moto E xt1022

**Comment by bauermateus** [comment]
Sorry for my bad english... I am brasilian

**Comment by Systemad** [comment]
For long did you waited?
It can take up to 10 min. (It took 5 minutes for me)

**Comment by bauermateus** [comment]
I waited 10 hours

**Comment by sorano** [comment]
Duplicate of #205
