### ISSUE TITLE
обновление Ruby

### ISSUE THREAD

**Issue by Volufe32** [cSploit/android#153]
При попытке обновить Ruby выдает ошибку.

**Comment by CoolOppo** [comment]
Are you completely oblivious to the fact that this is an english-speaking website?

**Comment by Volufe32** [comment]
Ok, My problem is that Ruby is not updated.
I went in and he told me cSploit proposes to update Ruby, wait 2-3 minutes and then gives an error.

**Comment by sorano** [comment]
Duplicate of #205
