### ISSUE TITLE
msf update fail

### ISSUE THREAD

**Issue by forkmind** [cSploit/android#161]
I have already try to delete msf in preferences, what can i do ?

NB : I also have an issue to install Xposed framework ans have this error : cannot executable link dependencies library libdvsm.so notre found. It have perhaps nothing to deal with this issue but I post just in case : on KitKat i haven't this error on both, Xposed and Csploit.
NB2 : I am a Nethunter and a Lollipop user.

**Comment by sorano** [comment]
Duplicate of #205
