### ISSUE TITLE
App doesnt work says

### ISSUE THREAD

**Issue by LOOLOOOL** [cSploit/android#168]
Everytime i open the app it says
" core is not installed, the application will just check for updates "
then after a bit it say no core for this device found

**Comment by LOOLOOOL** [comment]
And now it say error occured whil downloading the update

**Comment by LOOLOOOL** [comment]
I have a nexus 4 
running on stock kitkat 4.4.4 
fully rotted busybox etc.
and i have kali nethunter... could that be a problem ?

**Comment by sorano** [comment]
Maybe the path for your busybox is wrong? Try change install path and then try newer version of csploit.

Without any logs it is impossible to help sorry. Im closing this issue for now.
Feel free to reopen once you've tried the above and don't forget to attach logfiles.
