### ISSUE TITLE
Metasploid update error. 

### ISSUE THREAD

**Issue by emiel89** [cSploit/android#173]
Csploid downloads the update and tries to install after a few minutes it gives the message "download error" on my experia Z phone.

**Comment by Systemad** [comment]
I don't know why people creating issues about Metasplout when there are already at least 10 of them, especially without a logcat.

**Comment by maddogbuster** [comment]
here a logcat for the metasploit update error ,,,   https://gist.githubusercontent.com/anonymous/a9a116a91e3bf09c9df1/raw/d212916dc224e372ab40125d9accaef75ec0ab06/logcat%20csploit...installing%20gems...An%20error%20occured%20while%20downloading%20the%20update%20....

**Comment by sorano** [comment]
Duplicate of #205
Try the latest version.
