### ISSUE TITLE
Deleting everything

### ISSUE THREAD

**Issue by thapr0digy** [cSploit/android#174]
I didn't notice it until I chose a different directory, but if you choose to switch the ruby or msf directory to a different one it will delete everything in that folder. I switched it to the /storage/emulated/legacy and wanted to choose "msf". Instead when I chose to restore default path it preceded to delete everything on my sd card. Not really a good way to go about it.

**Comment by Systemad** [comment]
Same thing happened to me.

**Comment by thapr0digy** [comment]
Can't even find a decent data recovery tool

**Comment by UrbanChrisy** [comment]
Contact the devleoper do your research before asking here, im not the developer. This is just a fork,

**Comment by tux-mind** [comment]
@thapr0digy sorry about that, I though that we show a warning about that ... have to check.

**Comment by tux-mind** [comment]
yes, there is a prompt that ask you to proceed with deletion before performing it.
