### ISSUE TITLE
Metasploit RPCD - Process wont start - XT1032

### ISSUE THREAD

**Issue by Qu1cksnap** [cSploit/android#178]
Hi,
The metasploit RPCD of csploit wont start on moto g XT1032. Android lollipop

**Comment by Systemad** [comment]
It depends on the cpu, it should take to to 5 min (for me on htc one m7)

**Comment by Qu1cksnap** [comment]
Even if i get the prompt saying that the process wont start? Also i shoud have include this is my original post. I also get prompt with an error messages when trying to download the latest Ruby updates. Thanks for the quick reply and awesome app! You'v got my like xD

**Comment by Qu1cksnap** [comment]
*cannot start process*(metasploit rpcd) and *an error as occured while downloading the update* (ruby update) are the 2 error messages i get. Should i post a log somewhere with my devices spec? Thanks again

**Comment by Systemad** [comment]
Log cat is not needed, the metasploit package seems to be broken. We just have to wait until @tux-mind fixes it. (He's very busy)

**Comment by PixelPips** [comment]
I have exactly the same issue: can't start metasploit or download Ruby.

The application appears to be working for the most part though.

**Comment by sorano** [comment]
Duplicate of #205
Try the latest version.
