### ISSUE TITLE
Core Install error

### ISSUE THREAD

**Issue by BoRoX1nAa** [cSploit/android#179]
when downloading core.tar.xz and extrating shows me "heart attack" how to fix that?

**Comment by emiel89** [comment]
Yeah this happened to me as well. I have the new android 5.0.2 installed and i got root. what can i do to fix it?

**Comment by t0fum4n** [comment]
Same issue. Tried multiple diff versions and fixes....anyone know whats up?

**Comment by EnolRekcah** [comment]
I'm having the same issue and still I don't know how to fix it.

**Comment by t0fum4n** [comment]
I have moved on. Some things just arent meant to work....

**Comment by Megaeloelo** [comment]
Probably:
KingoUser and others su managers - heart attack ,
SuperSu - Core installed .
This working for me .
Sorry for bad english .

**Comment by shaneshuford** [comment]
Why wouldn't Kingo Root work?  They make it very hard to switch to supersu

**Comment by DeveloppSoft** [comment]
Super su is more popular
Le 21 juil. 2015 02:23, "Shane J. Shuford" <notifications@github.com> a
écrit :

**Comment by shaneshuford** [comment]
It won't be more popular if Kingo root continues to offer such simple
methods of rooting your device. The number of google hits on replacing
kinguser with supersu is rediculas, and the number of people who fail to
make it switch successfully is just as large of a user base.

**Comment by sorano** [comment]
Older issue without any logs.
Try newer version with busybox installed in correct path and supersu. Then re-open and attach logs if you have further problems.
