### ISSUE TITLE
compile

### ISSUE THREAD

**Issue by DeveloppSoft** [cSploit/android#180]
Hello guys, I wan't try tout fix msf installation, but I dont know show to compile cSploit.

**Comment by 0MazaHacka0** [comment]
I know how compile, push your fix in my repository, or say what you edit.

**Comment by DeveloppSoft** [comment]
OK, in updategem function, we may had some lines running gem -f <gem that web can't install>.
Maybe you van explain me show to compile...

**Comment by mcilya** [comment]
compile it with android studio

**Comment by DeveloppSoft** [comment]
OK, thanks
