### ISSUE TITLE
Ruby/Core/MSF

### ISSUE THREAD

**Issue by asmodeusnof3** [cSploit/android#181]
Unfortunately I have kept an eye on this issue for quite some time as I HAD much preferred c/dsploit to ANTI, to no avail. Tux, your vision was awesome, and we are all painfully aware of your limited available time for the project but a very large portion of your user base is stuck with a broken update system. I am sure you are aware of the ruby, core, msf install issues by now but after quite a while of waiting I must officially bid you and this project adu. 

I am leaving this here in hopes that one day I will happen a crossed it and see this major crippling glitch has been addressed, but I am sadly not expecting it at this point. 

Dsploit had the potential to be the superior pentest suite which is why I was so excited when I saw that it had survived evilsockets migration. But after donating and migrating phones with csploit in mind, I can no longer wait for a fix to the installer issues, as it seems all help has ceased for the multiple users who have been stopped in our tracks.

Gl yall, hope to see this project revived again some day! 

/endrant

**Comment by tux-mind** [comment]
yeah don't worry, i'll keep up the work :wink:
for the better update system I'm working on it.

thanks for your time and donations, I'll try to make my best to satisfy your needs :blush:
