### ISSUE TITLE
stuck at install gems for msf

### ISSUE THREAD

**Issue by hackereg35** [cSploit/android#183]
update core  <-- done
update ruby  <-- done
update msf    <--done
install gems   <--this point never complete
log
http://pastebin.com/Vq1cMXZA
The last line has been shown
A 30 thousand times

**Comment by amindrs** [comment]
I have this problem too.
It never gets past this point and every time I run cSploit, it shows same msf update dialog.
"Installing gems for MSF"

**Comment by DeveloppSoft** [comment]
Yes, I open an issue to fix and tux-mind is coming back, so wait guys.

**Comment by sorano** [comment]
Duplicate of #205
Try the latest version.
