### ISSUE TITLE
Metasploit update issue / HTC One m7

### ISSUE THREAD

**Issue by kdotkdot** [cSploit/android#184]
After i've downloaded Metasploit, the installation seems to be a andless loop. Current OS: Cyanogen Mod 12-20141205-UNOFFICIAL-m7.

**Comment by nerunexus** [comment]
I will concure.  The m7 installs core and MFS but the Ruby gems install never completes. I'm on a cm12 based rom as well. For what it's worth dsploit works on stock.

**Comment by sorano** [comment]
Duplicate of #205
