### ISSUE TITLE
SD card is not allowed to run executables in Androind (CM) 12.1

### ISSUE THREAD

**Issue by CreekOne** [cSploit/android#194]
As the title says, there is a problem installing anything to the SDcard on CM 12.1 as it mounts all "sdcards" with noexec. To change this one have to edit the kernel .img and modify vold.

**Comment by CreekOne** [comment]
Also having two sd cards, I can't choose to change location from sdcard0 to sdcard1 in cSploit

**Comment by DeveloppSoft** [comment]
We can't chmod files on sdcard, sorry.

**Comment by CreekOne** [comment]
Ofc we can't chmod the files, as I said, the sdcard is mounted with noexec by vold. This can only be changed by editing vold in the kernel image as it overwrites the "fstab" on every boot.
This is easy to do on a rom like CM 12.1.

There is another way to do this with remount but it's still not really relevant to cSploit devs.

**Comment by DeveloppSoft** [comment]
@CreekOne, cSploit is not a ROM so we can not use what you suggest

**Comment by sorano** [comment]
like @DeveloppSoft said.

cSploit is not a ROM so we can not use what you suggest
