### ISSUE TITLE
Stuck with gems, i think you can help!

### ISSUE THREAD

**Issue by Diamondy4** [cSploit/android#197]
Stuck with gems as a lot of people here.
Can somebody with working program make an archive with program folder (/data/data/org.csploit.android), i think that if i use working files it will work =).
Thanks for help in advance!

My device is Note 3 lte (n9005) with lastest cyanogenmod 12.1

**Comment by Benjamin3992** [comment]
maybe that has something to do with CM 12.1; Same Issue with my OnePlus One

**Comment by Systemad** [comment]
This is not related to CM, the ruby and msf package are broken.

**Comment by DeveloppSoft** [comment]
Wrong, some gems packages are not installed because ruby is too old, but if
you give me the list of them, I will fix it, I already do the same thing to
run msf on my raspberry.
Sorry for my bad english.

**Comment by domenicoblanco** [comment]
I can't install only msgpack

**Comment by tux-mind** [comment]
duplicate of #205

**Comment by tux-mind** [comment]
thanks for the report anyway :blush:
