### ISSUE TITLE
ruby gems update fails

### ISSUE THREAD

**Issue by Derheynn** [cSploit/android#206]
cSploit displays "An error occured while downloading the update"
And here is the log entry:
07-18 00:14:35.775 E/CSPLOIT[core.UpdateService.execShell](14865): ERROR:  Could not find a valid gem 'mini_portile' (~> 0.5.0) in any repository
I'm running cyanogenmod on a Samsung G S3.
Thanks for your awesome job, you're doing it well !

**Comment by Derheynn** [comment]
PS: i uninstalled and reinstalled the app, and the error is still being thrown

**Comment by Pukson** [comment]
Please read the other issues before you it. Read the issue about MSF Installation.
