### ISSUE TITLE
Error al descargar metasploit

### ISSUE THREAD

**Issue by darknerk** [cSploit/android#217]
Me aparece error al descargar metasploit.
Se puede descargar pero al momento de instalar el msf me aparece ese error.
Porfavoz como puede solucionar este problema

**Comment by fabinhojcr** [comment]
Always use English to comment

**Comment by darknerk** [comment]
I get error downloading metasploit .
You can download it but when I install the SPS appears that mistake.
Please fix this problem as

**Comment by sorano** [comment]
Duplicate of #205
