### ISSUE TITLE
csploit

### ISSUE THREAD

**Issue by gelero43** [cSploit/android#219]
Metasploit dont start and port scanner dont find anything

**Comment by Rubenoo** [comment]
the developers are aware of those bugs, please leave more detail about the bug. for example make a catlog ect

**Comment by DeveloppSoft** [comment]
@Rubeeno, I totally agree with you.
@gelero23 and the others, please as you can see, we have a lot of issues like it, and... just one is needed, so do not reopen an issue, if you have something to add make a post into the issue

**Comment by sorano** [comment]
Duplicate of #205
