### ISSUE TITLE
MSF Update fails !

### ISSUE THREAD

**Issue by sudodevil** [cSploit/android#224]
At the point "installing gemz for MSF" update always fails and metasploit server can't start anymore. Whats wrong?

**Comment by DeveloppSoft** [comment]
We are already working on it

**Comment by Rubenoo** [comment]
@developpSoft do you guys have a ETA?

**Comment by DeveloppSoft** [comment]
@Rubenoo, please, what does 'ETA' mean ?

**Comment by Rubenoo** [comment]
D

**Comment by Rubenoo** [comment]
@developpSoft it means :"Estimated Time of Arrival" , I wanted to know if you guys know when the msf is working again, like next week or something

**Comment by Rubenoo** [comment]
@developpSoft it means :"Estimated Time of Arrival" , I wanted to know if you guys know when the msf is working again, like next week or something

**Comment by DeveloppSoft** [comment]
I do not know, @tux-mind is trying to downgrading msf.
For the moment, I am working on an other solution wich will work well with cSploit, and my Linux Distro

**Comment by Rubenoo** [comment]
@developpSoft Can you notice everyone if you find the solution? And thank you for helping tuxmind with this project

**Comment by DeveloppSoft** [comment]
Yes, of course

**Comment by sorano** [comment]
Duplicate of #205
