### ISSUE TITLE
Ruby update issue

### ISSUE THREAD

**Issue by loganrussell48** [cSploit/android#227]
There is currently an issue where Ruby doesn't update correctly on my LG G Pad 8.3 

To describe the issue, when i open the app, it tells me there is an update available for Ruby(whether or not there actually is an update, I'm not sure). I allow it to update, it downloads the file, checks the file, and right after it begins the extracting stage, it fails and no update is installed.

**Comment by hightechstl** [comment]
This is a known issue and is currently being worked on

**Comment by sorano** [comment]
Duplicate of #205
