### ISSUE TITLE
when launching the session hijacker the HTTPS redirection rule is always deleted

### ISSUE THREAD

**Issue by gainan** [cSploit/android#233]
Hi all,

I've realized while playing with the session hijacker module, that the HTTPS redirection rule is not added. The behaviour when you press the start button is as follow:
- if configured HTTPS redirection: clean all the rules, add a new HTTPS rule.
- clean all the rules, and add the HTTP redirection rule.

so the HTTPS rule is always deleted.
logcat:
> D/CSPLOIT[tools.IPTables.portRedirect]( 2209): Redirecting traffic from port 80 to port 8080
> D/CSPLOIT[tools.IPTables.portRedirect]( 2209): Redirecting traffic from port 443 to port 8082
> D/CSPLOIT[tools.IPTables.portRedirect]( 2209): Redirecting traffic from port 80 to port 8080
> D/CSPLOIT[tools.IPTables.portRedirect]( 2209): Redirecting traffic from port 443 to port 8082
> D/CSPLOIT[tools.IPTables.portRedirect]( 2209): Redirecting traffic from port 80 to port 8080

I've created a patch which solves this problem: https://github.com/gainan/android/commit/8cf955822bee33f5be23e29b6aa4c7f84d362ed8

Now the behaviour is this and the HTTPS redirection rule is not deleted:
> D/CSPLOIT[tools.IPTables.portRedirect](12798): Redirecting traffic from port 80 to port 8080
> D/CSPLOIT[tools.IPTables.portRedirect](12798): Redirecting traffic from port 443 to port 8082

**Comment by evertking** [comment]
Where are how do I use this patch? Thanks in advance.

**Comment by gainan** [comment]
you can create a patch from this commit by checking out my repository (git clone ...), extracting the patch (git format-patch 8cf955822bee33f5be23e29b6aa4c7f84d362ed8; git format-patch HEAD~~),  and applying it to yours/this one.

if @tux-mind considers it useful, I can create a pull request for merge it with the base. Anyway, I think the SSL interception is broken, at least for some modules.
