### ISSUE TITLE
Cannot start process Metasplojt RPCD

### ISSUE THREAD

**Issue by k0spwn** [cSploit/android#235]
Running last csploit version ( 1.5.3 ) 

When I try to start Metasploit RPCD it give the "cannot start process" error 

I'm on a Galaxy S4 GT-I9515 on Android 5.0.1 Stock

**Comment by caythanhgia** [comment]
me too,

i'm on a Sony xperia z2 android 5.1.1 Stock

**Comment by sorano** [comment]
Please stop spamming about this issue, it is well known and you will see lots of similar issues if you look them through, follow this for updates: https://github.com/cSploit/android/issues/205

**Comment by sorano** [comment]
Duplicate of #205
