### ISSUE TITLE
Suggestion: Allow cSploit to run on additional interfaces

### ISSUE THREAD

**Issue by sorano** [cSploit/android#240]
My idea is to have cSploit be able to run on interfaces other than wlan0.

Like a dropdown in options with ability to chose which interface to use.
For example on a Nethunter pad you can use OTG cable to connect an additional USB LAN/WLAN interface.

**Comment by maddog9696** [comment]
This would be so amazing and useful! I am not aware of any app that can do this at the moment other than Kali nethunter. If I could for example use my ALPHA with my galaxy tab pro 8.4 for packet injection/monitor mode in csploit this would be super! If actually implemented, I will give tux/anyone else every available penny I can to thank him! Thank you tux for your work you are truly AWESOME !

**Comment by gainan** [comment]
done!
