### ISSUE TITLE
Dark Theme text issue

### ISSUE THREAD

**Issue by maddog9696** [cSploit/android#258]
Not a major issue, however I thought I'd share it. Idk maybe it's supposed to be like that! 

When you choose dark theme, all of the descriptions of the tools are hidden because they're the same color as background.
![screenshot_2015-09-21-13-19-35](https://cloud.githubusercontent.com/assets/14237628/9999355/f5d265d6-6063-11e5-93d1-6454a5de80ad.png)

**Comment by MuradTroll** [comment]
When I use dark theme, and I try to click on a host, my CSploit crashes.

That means that I am not even able to get to your screen "Select a Module to run"...

**Comment by fat-tire** [comment]
That's my screw up.  When I [ported to material design](https://github.com/cSploit/android/commit/9eb34156d93543c60b62c3c420551ec717a1513e) the dark theme was screwed up, and I didn't go back and fix it (lower priority, but noted in the comments).  This is something a non-programmer could address if they want to get their feet wet and contribute back to the project.

Basically, take a look at the dark theming stuff in [style.xml](https://github.com/cSploit/android/blob/develop/cSploit/res/values/style.xml) and tweak to taste.  You can learn more [here](https://developer.android.com/guide/topics/ui/themes.html).

Have fun!  If you have questions about building or in general, swing by IRC and someone will hopefully be around to help.

**Comment by Tajnymag** [comment]
I can take a look at this tommorow, eventually on Wednesday. If you have no time, just tell me :-)

**Comment by fat-tire** [comment]
Hey check out  PR #279 and see if this fixes stuff.  It looks decent enough (I'm not a designer peoples!) on Lollipop.  I haven't checked w/other versions of Android but hopefully it'll look similar.

**Comment by fat-tire** [comment]
Dark theme was just checked in.  If it works for everyone, please close this.

![ss](https://i.imgur.com/qIilkhY.jpg)

**Comment by tux-mind** [comment]
fixed in develop branch, try out the nightly apk.
feel free to reopen the issue if you need.

and say thanks to @fat-tire :blush:
