### ISSUE TITLE
page or something to the community or tux-mind to make tutorials

### ISSUE THREAD

**Issue by hipopcorn** [cSploit/android#259]
we need 2 things: tutorials to know how to use the tools( it will be less issues)
and with peoples making videos, the issues will be reported as videos, than we will see better what is the problem.
@tux-mind  for a while, i think it would be better if you can give us a link of somewhere to post videos like tutorials or issues, or a page at your site, i dont know, but something like this will be awesome.
(and fix the payload bug, thaaanks)

**Comment by Tajnymag** [comment]
Please, use the Reddit page. It would clear the github issues.

**Comment by tux-mind** [comment]
@hipopcorn we are working on producing some docs int the wiki of the repo.

for issues the best thing is posting a brief description of the problem and a logcat.
videos does not tell us why something goes wrong, only show us the error as you see it.

if you want to make some video on how to use cSploit I'll be glad to use it in our tutorials.

thanks anyway for the suggestion :wink:

**Comment by hipopcorn** [comment]
@tux-mind surge!!, and i can translate the entirely wiki to portuguese if you prefer, cause google Translator is not so good, can i make a channel named csploit?

**Comment by tux-mind** [comment]
a channel on youtube ?
it will be great!
the top is to have them in english with subtitles :stuck_out_tongue_closed_eyes: 

I don't known if github support multi-language wiki... will see.

**Comment by hipopcorn** [comment]
@tux-mind i need somewhere to talk to you about the videos, and thanks for the cool notification about metasploit rpcd!!

**Comment by evertking** [comment]
Where can we find these videos? That's all that's missing!! CSploit rocks!! Forget nethunter

**Comment by hipopcorn** [comment]
@evertking i will work on it

**Comment by tux-mind** [comment]
@hipopcorn thank you :blush: 

if you need to talk give a look to the [Get involved] page :blush: 

[Get involved]: https://github.com/cSploit/android/wiki/Get-involved#irc
