### ISSUE TITLE
ActionBar menu does not appear on android 4.2.2

### ISSUE THREAD

**Issue by gustavo-iniguez-goya** [cSploit/android#263]
as you can see, the menu of the right side is missing on Android 4.2.2 (and probably >= 4.0 && <= 4.2.2)
![device-2015-09-22-185519](https://cloud.githubusercontent.com/assets/2742953/10025930/1efd3a8e-615f-11e5-859f-d64fc5ad463f.png)

On android 4.4.4 works fine

![screenshot1](https://cloud.githubusercontent.com/assets/2742953/10025968/619cfcd0-615f-11e5-97ec-d67dc6ba7282.png)

**Comment by DeveloppSoft** [comment]
Use your physical menu button.

**Comment by gainan** [comment]
yeah, it's a minor problem for me, but it should work as in android 4.4.4.

**Comment by tux-mind** [comment]
maybe [this](http://stackoverflow.com/questions/18407362/action-bar-not-showing-in-4-2-2) can help us

**Comment by mcilya** [comment]
It's ok for me with samsung galaxy tab 10.1, 4.0.4. http://m.imgur.com/zz37bqH

**Comment by IwraStudios** [comment]
Seems to be fixed; closing issue
