### ISSUE TITLE
no core found on first start

### ISSUE THREAD

**Issue by evertking** [cSploit/android#278]
Installed the nightly and says no core for device.
Where do I find the files and tools the app installs?

**Comment by DeveloppSoft** [comment]
What device are you using ?

**Comment by Rubenoo** [comment]
It's a comment issue just restart csploit and it will work again

**Comment by Rubenoo** [comment]
Common*

**Comment by mcilya** [comment]
@evertking Can u post a logcat?

**Comment by tux-mind** [comment]
probably a network error has occured and it couldn't connect to github.

should give a different feedback to the user.

**Comment by tux-mind** [comment]
cannot reproduce this.... I need someone that gives me a logcat with the problem.

thanks you in advance.

**Comment by Rubenoo** [comment]
still same problem on latest develop branch
logcat : https://gist.github.com/Rubenoo/c5c27a83d6cbcd3b1616
