### ISSUE TITLE
Dark theme needs fixing

### ISSUE THREAD

**Issue by Avamander** [cSploit/android#284]
The dark theme only changes a few text elements to black. I am using the latest version downloadable by the app's updater, 1.5.4. 

EDIT: Dark theme needs redesigning.

**Comment by DeveloppSoft** [comment]
Try 1.6.0

**Comment by Avamander** [comment]
@DeveloppSoft I suggest you'd next time don't include the email you reply to. It can be disabled in most mail clients.

**Comment by Avamander** [comment]
The 1.6.0-rc.1 version has dark theme, but it is hideous. :put_litter_in_its_place:

**Comment by fat-tire** [comment]
Well aren't you adorable, Avamander
![avamanderplease](https://media1.giphy.com/media/L29fiOMSDhhvi/200.gif)

I look forward to your pull request fixing this issue.

**Comment by Avamander** [comment]
@fat-tire 

No skills to do that, sorry. :D

Main menu is not that bad. But even when dark mode is enabled, settings are white .-.

![Main menu](http://i.imgur.com/8oTSlJQ.png)

**Comment by fat-tire** [comment]
Settings never has adopted the dark theme (I never changed that), but it's not a big deal to have it respect the theme...   In your image above, what's between the quotes?  I haven't seen that.

To adjust the theme-- just change the colors in [style.xml](https://github.com/cSploit/android/blob/develop/cSploit/res/values/style.xml#L18-L41).  To use the theme  in the settings, I think you can add something along the lines of:

~~~
    SharedPreferences themePrefs = getSharedPreferences("THEME", 0);
    if (themePrefs.getBoolean("isDark", false))
      setTheme(R.style.DarkTheme);
    else
      setTheme(R.style.AppTheme);
~~~

right [here](https://github.com/cSploit/android/blob/develop/cSploit/src/org/csploit/android/SettingsActivity.java#L81) in `SettingsActivity.java`.

Be sure it goes after:

       public void onCreate(Bundle savedInstanceState) {

and before

       super.onCreate(savedInstanceState);

Test thoroughly.  And I look forward to your pull request.

**Comment by Avamander** [comment]
Uhhh, I don't have the necessary tools to compile an Android app. So if I get time I might look into it. :)

**Comment by sorano** [comment]
It is usually considered rude to complain on another mans work when you can not do it better yourself.

In that case its better to be silent.

**Comment by Avamander** [comment]
Sorry if I was rude. But if a thing need improvement then it should be atleast mentioned.

**Comment by DeveloppSoft** [comment]
@Avamander sorry, I was using gmail
