### ISSUE TITLE
By default store MSF and Ruby in the apps data folder

### ISSUE THREAD

**Issue by Avamander** [cSploit/android#285]
It would be really great if instead of internal storage, MSF and Ruby are stored in the app's data folder on external storage.

**Comment by tux-mind** [comment]
Hi @Avamander , I'm happy to get suggestions from you again :blush:

does android wipe that dir when the application get removed ?

**Comment by Avamander** [comment]
Usually it does if the app is normally uninstalled. (Just to make sure, I am talking about <path to storage (internal usually)>/Android/data/<packagename>)
