### ISSUE TITLE
Everytime I try MITM or anygthing, app crashes or is very slow.

### ISSUE THREAD

**Issue by dimitriDymaKamarov** [cSploit/android#286]
When I ran this app before 1.5.4 it ran smooothlyyy as fvck. But now after the update it crashes and is really slow, But that is not the real issue. It also fails to start MITM, it says it crashed and I am unnable to do anything. Any ideas, suggestions? Got Rooted Sony Ericsson Xperia Mini Pro with LegacyXperia CyanogenMod 12.1, so 5.1.1 Lolipop.

**Comment by gainan** [comment]
Hi @dimitriDymaKamarov , thank you for open the issue.

Get a logcat while you reproduce the problem, and read this for further information:
https://github.com/cSploit/android/wiki/How-to-open-an-issue

**Comment by sorano** [comment]
User has not returned with logs of any kind. Feel free to re-open when you have logs.

https://github.com/cSploit/android/wiki/How-to-open-an-issue

> "Any issue which will not contain those details, will be signaled with a link to this page and  closed from 24h to ∞ later."
