### ISSUE TITLE
Installation hangs on update loop

### ISSUE THREAD

**Issue by tuxaddict** [cSploit/android#293]
Hi all, thanks for this great project!

i'm trying to install 1.6.0 RC1 as well as 1.5.4 on my Motorola Defy Mini XT320 rooted with Android 2.3.6 but the install "hangs" in a "update loop".

The Install is set by Link2SD to my SDCard, but the error also exist if i let the install write its data to the (standard) internal storage.

process:
Install with Paket Installer --> "Anwendung Installiert" --> "Update available - core-package 1.0.6 is available, shall i do an upgrade? --> YES " ... working ... screen blacks out for a second and then the "Update available" dialog starts again. And so on, and so on (-:

If i choose no to the update question, an "Initialising error" message appears, and the app exits.

Here's the LOGCAT incl device details: http://paste.ubuntu.com/12589704/

any ideas on this ? bst regards me (-:

**Comment by tux-mind** [comment]
thanks for the detailed report @tuxaddict , very appreciated :blush: 

I have a bad news for you: your phone run `OutOfMemory`.

try to launch the update and the close the app by clicking twice on back.

keep me posted :wink:
