### ISSUE TITLE
How can i compile cSploit?

### ISSUE THREAD

**Issue by ada-af** [cSploit/android#30]
How to compile all csploit modules in android studio or anything else?

**Comment by katepratik** [comment]
How to build jin files? I have added all lib to the jin Folder and trying to run ndk-configure file u provided but its not working. Please provid a step by step guide to integrate NDK to the Android code.

**Comment by tux-mind** [comment]
Hi @katepratik , sorry for the late reply, I'm under exams right now.

"not working" is not so much for me to understand what is going bad with your setup.

AFAIK the steps that I wrote in the previous post should work correctly, please report the output so I can help you.

**Comment by xaitax** [comment]
In case @tux-mind can't answer in time due to his exams just post here and let me know. As I am building the nightlies.

**Comment by Hwiggy** [comment]
Hello, is the process similar for Windows? As I try to run the build.sh and the sudo command cannot be located, ends up failing.

**Comment by xovertheyearsx** [comment]
`sh `is a shell script and is not a batch script so it will not work unless you install MSYS or Cygwin. `sudo` is not a windows `cmd `applet or recognized executable so that will not work either. sudo is particular to *nix environments. you should look up how to build natively to your system or use a vm with a linux flavor on it.

**Comment by fat-tire** [comment]
So I'm not a windows user, but I can at least give you some theories of how to build the app (not so much the binary libraries- I've got no idea on how toolchains work in Windows, so you'll have to use the prebuilt ones from a current version).  Probably the best and most educational way to learn is to load Ubuntu or another Linux via a virtual machine (such as the free Virtualbox) and install from there, but then you may run the risk of realizing what a piece of shit Windows is and want to use Linux for ever.

To build the app in Windows, should you somehow want to try, you'll first need to download [Android Studio for Windows](https://developer.android.com/sdk/index.html).  That should get you the build environment which you'd use for creating the .apk.

Next you'll need the source.  I'm not sure the best version of git for windows, but [this link](https://git-scm.com/download/win) came up for me when I did a quit search.  This is the program you'll use to get the source code for cSploit.  The normal command for doing this is:

     git clone https://github.com/cSploit/android.git

So it'll be something similar in windows.  The point is you'll get a directory called "android" with the source inside.  You can then open this project from Android Studio.  But there's one last step.  You'll need to add the prebuilt library files from a current .apk.  To do this, rename the cSploit-nightly.apk (or whatever it's called) to cSploit-nightly.zip.  If you search inside, you'll find four files:

    ./armeabi-v7a/libcSploitClient.so
    ./armeabi-v7a/libcSploitCommon.so
    ./armeabi/libcSploitClient.so
    ./armeabi/libcSploitCommon.so

Those go in this [jniLibs](https://github.com/cSploit/android/tree/develop/cSploit/src/main/jniLibs) directory.

Now you can use Android Studio to build the .apk, and voila.. you should have a freshly-made copy of cSploit!

Again, if you've never used Linux before-- don't mind @SwiftOnSecurity -- it's SO much better than Windows.  Fire up [Virtualbox](https://www.virtualbox.org/wiki/Downloads) and give it a try.

**Comment by zodd7** [comment]
thanks fat-tire, now i can compile and run cSploit without any problem.
