### ISSUE TITLE
dns spoofing not working

### ISSUE THREAD

**Issue by Haxin-hipopcorn** [cSploit/android#303]
i can launch dns spoof, on the csploit its all ok, but when i goes to the websites it crashes the site with ERR_CONNECTION_TIMED_OUT, if i dont touch on the default list, and try to access microsoft.com for example i get this error.

**Comment by evertking** [comment]
Is there a guide anywhere on how to use the DNS tool

**Comment by gainan** [comment]
@hipopcorn , try this: launch it again, and on the shell as root type: echo 1 > /proc/sys/net/ipv4/ip_forward 

If doing that works for you, then I'll take a look at it. I saw this behaviour a couple of times, but I couldn' t reprodcuce it. Thanks for reporting btw :]

@evertking , it's pretty simple: any configured domain on the DNS textbox will be spoofed to its corresponding spoofed IP. 

A common scenario could be to spoof the IP of a page to redirect it to a webserver you own, and serve a copy of the original page. This could be also be achieved by setting up a webserver from the mobile, and allowing the user to select which directory to use as the root of the webserver.

**Comment by hipopcorn** [comment]
@gainan it stills not working why?? :/

**Comment by gainan** [comment]
Closing the issue due to lack of information. In case of keep failing, post logcat + pings to www.ettercap.org + dig mx alor.org.

https://github.com/cSploit/android/wiki/How-to-open-an-issue

**Comment by Bauta76** [comment]
Not working also for me.
I tried also to "echo 1" to the proc as mentioned, but as soon as I start the dnsspoof and I browse a certain website from the victim phone, everything seems to stuck and can't access to the website that was supposed to be spoofed. As soon as I stop the dnsspoof, everything works again.
