### ISSUE TITLE
suggestion: make phishing pages and hosting it on the device ip

### ISSUE THREAD

**Issue by hipopcorn** [cSploit/android#304]
like the social engineering toolkit, you give an url example: facebook.com, then  it makes a phishing page, and turn your device ip into a server with your phishing page, and your collected data appears, you can integer it with dns spoofing

**Comment by evertking** [comment]
http://m.rahullah.store.aptoide.com/app/market/dolphin.developers.com/1/5394150/Social%20Engineering%20kit

Kinda like this?

**Comment by tux-mind** [comment]
Why use phishing when we are MitM ?
we ca have users surfing on the real website ( facebook, google or whatever ) while we sniff their login credentials and cookies.

SSL split support will be added on next releases of cSploit.

thanks for the suggestion anyway :blush:

**Comment by hipopcorn** [comment]
@tux-mind the problem is the htst, can you bypass it?

**Comment by xaitax** [comment]
HSTS can only bypassed if browsers don't have a hsts list built-in like IE or older versions of ff/chrome. We also would need sslstrip+ instead of sslsplit.

**Comment by tux-mind** [comment]
yep, @xaitax is right, but I'll start working on evilproxy soon.
I'll integrate ettercap dissectors with SSL split and sslstrip+ for HSTS.

simply a bomb :sunglasses:

**Comment by hipopcorn** [comment]
@tux-mind [MITMf]( https://github.com/byt3bl33d3r/MITMf) has a function to disable htst for the most of webbrowser and a lot of functions, can you include this functions??

**Comment by tux-mind** [comment]
yes @hipopcorn , it will require about 2 or 3 month of work but I can do it :wink: 

once I design the architecture of the evilproxy program suite I'll start searching some volunteer to speed up the process.

**Comment by hipopcorn** [comment]
@tux-mind cool!! I will be here trying to help

**Comment by evertking** [comment]
Man, this app has all but disappeared. And I lost my backup!! Could someone please reshare this app???

**Comment by tux-mind** [comment]
Look at the releases on github.

Exam now, have a nice day :)
Il 18/feb/2016 12:29 PM, "evertking" <notifications@github.com> ha scritto:
