### ISSUE TITLE
Core 1.0.7 Update Crashed msrpc

### ISSUE THREAD

**Issue by pgolecha** [cSploit/android#309]
Following the core update, starting metasploit rpc which was perfectly fine before started crashing everytime csploit started.
Here is the log
http://pastebin.ca/3177250

Phone Xiaomi Redmi 1S 
Android 5.1.1

**Comment by hipopcorn** [comment]
Same issue here I got back to the past nightly

**Comment by tux-mind** [comment]
can you test the nightly in the next hour ?
thanks in advance :blush:

**Comment by xaitax** [comment]
Please test it now guys. :)

**Comment by hipopcorn** [comment]
@tux-mind  it appears to be OK now!!
