### ISSUE TITLE
:::Closed:::Kill connections for entirely network

### ISSUE THREAD

**Issue by hipopcorn** [cSploit/android#310]
Why not? We can kill it individual why not kill all?
And see how much the IPs is using of internet..
 Like wifikill!! 
Then its more one app that we don't will need anymore ;)

**Comment by sorano** [comment]
Can't you already do this via MITM ARP poisoning (Kill connections) on the network/subnet?

I dont have my device with me currently, so can't test.

**Comment by daniloscala** [comment]
yes, this is good,  change  all images  in all device conected or other options in MITM

**Comment by gainan** [comment]
@sorano is right, this option is already possible, so please @hipopcorn close it if you're agree. If it's not working, please, open a new issue explaining in detail what is not working :)

Thank you!

**Comment by hipopcorn** [comment]
@gainan sorry kkkkkkk really sorry

**Comment by gainan** [comment]
@hipopcorn no problem at all! ^.^ (use the **Close issue** button please ;-))

**Comment by hipopcorn** [comment]
@gainan how can I close?
