### ISSUE TITLE
web services vulnerability scanner

### ISSUE THREAD

**Issue by Haxin-hipopcorn** [cSploit/android#317]
Csploit is so focused on lan.I think adding a tab only for websites will be awesome , with sqlmap, stress test , admin page finder, etc

**Comment by tux-mind** [comment]
not sure about this feature @hipopcorn .

cSploit it's usually used in local area networks, nothing deny you to have a webserver in your lan, but is very uncommon.

it require a lot of work for something that I personally categorize as unrelated to the cSploit scope.

let's see what @cSploit/android-devs say ...

**Comment by gainan** [comment]
It depends on the kind of lan you' re on. If you are in a lan of a company you can encounter from 1 server to hundreds of them of any kind ... if you are on a wifi hotspot, it'll probably be an isolated lan with access to nothing.

We already have the msf, so I think we can use it, there're plenty of addons for these purposes.
https://www.rapid7.com/db/search?utf8=%E2%9C%93&q=sql+injection&t=m

**Comment by hipopcorn** [comment]
@tux-mind  not for lan, for web, you can already add a website like www.csploit.org and try something's, see this [sqlmap](https://github.com/muodov/sqlmapchik) for android
