### ISSUE TITLE
cannot set packages directories with superuser.

### ISSUE THREAD

**Issue by theobromine** [cSploit/android#32]
Whenever I try to change or set a directory for any of the packages, it tells me that the directory does not support the creation of executables. This leads me to not being able to start meta sploit and etc

**Comment by tux-mind** [comment]
sorry for the late reply.

@WanderingFool yes, a logcat will help.
please report also your device model and android version.

**Comment by sorano** [comment]
Users have not returned with logs for months.
Closing this.
