### ISSUE TITLE
IRC onto csploit

### ISSUE THREAD

**Issue by hipopcorn** [cSploit/android#322]
I think we need an irc in the csploit it will be awesome and we will interage better

**Comment by mcilya** [comment]
@hipopcorn IMHO it will be some useless

**Comment by hipopcorn** [comment]
@mcilya why? Cause we will talk to each other

**Comment by mcilya** [comment]
@hipopcorn In google market "hundreds" of IRC clients + its not related to pen-testing

**Comment by sorano** [comment]
This does not at all follow the spirit of cSploit, and like mcilya said there are lots of irc clients for android.
