### ISSUE TITLE
Cannot restore session

### ISSUE THREAD

**Issue by pgolecha** [cSploit/android#328]
![screenshot_2015-09-29-14-28-02](https://cloud.githubusercontent.com/assets/14873612/10159533/74187d2e-66b6-11e5-92e5-095dff49e87f.png)

**Comment by pgolecha** [comment]
Either it does not save it or cannot restore it properly

**Comment by Rubenoo** [comment]
How to Open an Issue
If you find a bug, weird behaviour, missing translation, a feature not working or anything strange in the application, you are encouraged to open an issue on the appropriate github page here.

For your issue to be considered and solved ASAP please provide the following information while opening it:

Your Device model.
Your ROM name and version.
The version of cSploit your are running if not sure, download the latest release and try to reproduce the problem with it.
As many details as possible on the network you are running cSploit on.
A detailed description of the issue you have:

if it is a MITM feature not working, please specify if the other MITM features and parts of the app are working on your network. For example:
App start ups ok.
Network hosts list appear and are clickable.
Select the MITM module works.
Select the Session hijacker module works.
When clicking on the "Start" button fails (write down the message!) , it says: "Cannot start process".
A logcat (very important!) taken while the application was running and the issue happened. learn what it is and how to use it -- you can also find more information about logcat here.

**Comment by pgolecha** [comment]
http://pastebin.ca/3177985
Here is the log
Android 5.1.1
Xiaomi Redmi 1s

**Comment by tux-mind** [comment]
thanks for the report @pgolecha :blush:
