### ISSUE TITLE
Whatsapp sniffer

### ISSUE THREAD

**Issue by Haxin-hipopcorn** [cSploit/android#330]
Is it possible? Sniffing the chats?

**Comment by Rubenoo** [comment]
It's not, it would be great if it was. But it isnt

**Comment by Tajnymag** [comment]
Even with SSL Split? For example Telegram uses no end-to-end encryption by default. Would it be possible to sniff it then?

**Comment by xaitax** [comment]
Won't work. Telegram uses a proprietary encryption. SSLSplit/SSLStrip focus on HTTPS->HTTP redirection if there is no HTTPS request initiated by the browser.

**Comment by Systenix** [comment]
Maybe you can use SSLSplit/SSLStrip to do a redirection from https to http but what **if the datas are encrypted in the client.**
I saw a project that does something like this.
Peps by MLstate: http://peps.in/

**Comment by maddog9696** [comment]
Whatsapp sniffing CAN be done! 
Check out: https://www.quora.com/Is-it-possible-to-intercept-hack-a-WhatsApp-conversation-between-two-people
and
http://www.youtube.com/watch?v=qbp8-NzO6Rc

I could be wrong, its been a few months since I'v successfully done it! You must be on the same WiFi and must dycrypt the messages before gaining anything from them.

**Comment by xaitax** [comment]
It does _not_ work anymore. Period.

**Comment by sorano** [comment]
Like @xaitax said.

It does not work anymore.

**Comment by tux-mind** [comment]
nothing is impossible.
if you are performing a MitM attack and have the appropriate tools to emulate the server you can get enything.

anyway this can be compared to a CTF challenge IMHO.
WhatsApp protocol is described [here](https://github.com/WhisperSystems/TextSecure/wiki/ProtocolV2).
so if we successfully strip/split SSL and emulate the whatapp server we hsould be able to sniff whatsapp conversations.

it can be a nice feature, but require much work.

**Comment by pgolecha** [comment]
@tux-mind how would you strip ssl if there is no http to https redirection?

**Comment by tux-mind** [comment]
@pgolecha we will not strip it, we will [split it](https://www.roe.ch/SSLsplit) :wink:

**Comment by xaitax** [comment]
And yet it won't work. 
WhatsApp implemented Moxies' TextSecure (end-to-end) encryption end of last year. It verifies each others’ identities based on their cryptographic key plus "forward secrecy" that creates a new encryption key for each message. Not even mentioning other cryptographic & security enhancement that came with it.

**Comment by tux-mind** [comment]
I didn't known that they used end-to-end crypt. I always though that whatsapp stores messages on their servers.

thanks for the info @xaitax , really appreciated :wink:

**Comment by Tajnymag** [comment]
Telegram, Messenger and even Snapchat don't seem to use end-to-end encryption by default...

**Comment by Haxin-hipopcorn** [comment]
@tux-mind  yes, we have a lot of clients of messaging apps, imessenger too!
