### ISSUE TITLE
Bruteforce WiFi!!

### ISSUE THREAD

**Issue by Haxin-hipopcorn** [cSploit/android#333]
You use a wordlist to Try the passwords on the wifi, I think this is not difficulty to do!!

**Comment by domenicoblanco** [comment]
The only problemi is that to bruteforce a Wi-Fi network we need a wordlist that start with ~6 to 25 characters, this way needs a lot of PB and, if we could create a wordlist like that, our mobiles can test about 1000/2000 key every second. It's not so good

**Comment by fat-tire** [comment]
Aside from the storage requirements, there is also the issue of power consumption on a mobile device to at least think about.  Not that it's a deal breaker or anything, but brute forcing millions of words could drain a battery fast.

Just putting it out there.

**Comment by Rubenoo** [comment]
You could just say that is recommended to charge your phone while bruteforcing

**Comment by mcilya** [comment]
@Rubenoo Then it will be more easily to bruteforce from a laptop

**Comment by Haxin-hipopcorn** [comment]
No guys, you dont nerd a big wordlist, you need to craft a great wordlist, just .
@mcilya you will not found a computer with Linux easier than a charger.
Example of a software like it: [here](http://m.al-shaheen.store.aptoide.com/app/market/cz.auradesign.wibrplus/33/3554472/WIBR%2B+WIfi+BRuteforce+)
Download [here](http://m.al-shaheen.store.aptoide.com/app/market/cz.auradesign.wibrplus/33/3554472/WIBR%2B+WIfi+BRuteforce+)

**Comment by mcilya** [comment]
@Haxin-hipopcorn ok, so you plugged your phone for charging, and trying to bruteforce wifi, how many passwords can be tried out per sec by your phone? And how much time will it take?

**Comment by domenicoblanco** [comment]
I mada a test and in an armv7 (Nexus 6) I tested about 3500 keys in 3 hours, in my laptop I test 4000 keys in a second

**Comment by Haxin-hipopcorn** [comment]
Guys, I know that it's obviously , but its not everywhere you will have your pc, its like better than nothing when you are only with your cellphone .

**Comment by tux-mind** [comment]
no no no.
@Haxin-hipopcorn thanks for the suggestion but I have to absolutely reject this.

we can tolerate a WPS bruteforcing, it's "only" 11,000 attempts.

WPA cracking cons:

  1. generating a single key it's a **VERY** cpu-intensive task
  2. for **1** it has a high power requirement **per-key**
  3. for **1** it will make your device unusable
  4. you need to try up to **6,095,689,385,410,820** keys for bruteforcing
  5. on a 5k key/s device you need up to **38658 years** ( and you got a 3500/3h now )

It should be clear enough :wink:

**Comment by Haxin-hipopcorn** [comment]
Yes sure kkkkkkkk
