### ISSUE TITLE
Statusbar color 

### ISSUE THREAD

**Issue by Tajnymag** [cSploit/android#334]
By material design rules, statusbar should be a bit darker colour than actionbar. It's a very low priority, but nobody noticed :) I would fix it by myself, but I'm very busy for this week.

**Comment by fat-tire** [comment]
Yep, this was caught by @s3r1alpari4h who submitted a [commit](https://github.com/cSploit/android/commit/f9db5411ae7acf6f814897826fe1cb8ee8a6099b) which I merged in today.

I'm guessing by now it's fixed in the latest nightly build.

Thanks!

**Comment by ghost** [comment]
![screenshot_20171026-141422](https://user-images.githubusercontent.com/20001886/32072578-a56c830a-ba58-11e7-8b3c-c1f96e07ef9c.png)
I guess I should create another commit for the dark theme
