### ISSUE TITLE
DarkSkin on OnePlusOne

### ISSUE THREAD

**Issue by napitek** [cSploit/android#336]
On my OnePlus the DarkSkin have some problems to visualize
![screenshot_2015-09-30-17-00-33](https://cloud.githubusercontent.com/assets/2965549/10196838/2413e536-6795-11e5-9505-9ff54a15e680.png)

**Comment by sorano** [comment]
Which version of cSploit is this?

**Comment by napitek** [comment]
cSploit v1.5.4

**Comment by sorano** [comment]
That is what I figured.

Try out the latest RC and it should look better:
https://github.com/cSploit/android/releases/download/v1.6.0-rc.2/cSploit-release.apk

**Comment by tux-mind** [comment]
thanks for the report @napitek , nice to see you there :wink:

**Comment by tux-mind** [comment]
duplicate of #284
