### ISSUE TITLE
qui che succede?? ahah

### ISSUE THREAD

**Issue by ac27** [cSploit/android#337]
![screenshot_2015-09-30-18-35-19](https://cloud.githubusercontent.com/assets/14910443/10199829/20cd8cac-67a3-11e5-82d3-a3f4e0fb12c3.png)

**Comment by domenicoblanco** [comment]
Ciao! Basta riavviare l'app e darle i permessi di root

**Comment by fabinhojcr** [comment]
Please use the English language

**Comment by ac27** [comment]
thanks! sorry i will speak only in english

**Comment by fabinhojcr** [comment]
@ac27 ok, alright

**Comment by tux-mind** [comment]
duplicate of #278
