### ISSUE TITLE
Mitm password sniffing. Can't start 

### ISSUE THREAD

**Issue by nivong** [cSploit/android#34]
I just tried password sniffing and it shows a toast that it isn't able to start the sniffing. All the other sniffing works . where are the log files located? 
Running on the oneplus one 4.4.4 AK kernel with stock rom.

**Comment by Mephistophiles** [comment]
I have the same problem. Here is my log.
http://pastebin.com/TuvjQUrF

**Comment by tux-mind** [comment]
@Mephistophiles thanks for the log.
it seems that ettercap is not installed ( or it cannot locate some core library, like libcrypto.so ).

can you do the following from an adb shell:

```sh
cd /data/data/org.csploit.android/files/tools/ettercap
./ettercap --help
```

thanks in advance for your time :blush:

**Comment by Mephistophiles** [comment]
http://pastebin.com/SwvHyrzK

**Comment by tux-mind** [comment]
I found the bug reading carefully the `execvp(3)` man page.

```
...
The execlp(), execvp(), and execvpe() functions duplicate the actions of the  shell  in  searching
       for an executable file if the specified filename does not contain a slash (/) character.  The file
       is sought in the colon-separated list of directory pathnames specified  in  the  PATH  environment
       variable.
...
```

the other commands have a slash in their argv[0], while ettercap does not.
using `./ettercap` instead of `ettercap` solve the problem.
