### ISSUE TITLE
core not installed

### ISSUE THREAD

**Issue by dillitimilsena** [cSploit/android#340]

**Comment by mcilya** [comment]
Please read this: https://github.com/cSploit/android/wiki/How-to-open-an-issue
And add missing info

**Comment by xaitax** [comment]
Not a proper bug. Reopen with the required information.
https://github.com/cSploit/android/wiki/How-to-open-an-issue

**Comment by gainan** [comment]
@dillitimilsena, thank you for the report!  I' m closing it due to lack of information. If you post all the info that the other guys have requested, I'll reopen it.
