### ISSUE TITLE
(idea) Reaver support

### ISSUE THREAD

**Issue by Rubenoo** [cSploit/android#342]
Its really cool if reaver could be merged into csploit for people that have a device that support reaver, or for people that have a external wifi card.

**Comment by PTZema** [comment]
Its a very good idea... And something like "router keygen" that works offline and automatically connects to the wireless

**Comment by Haxin-hipopcorn** [comment]
the problem is the battery, i think changing ideia to suggestion its better, according to tux-mind: "<tux_mind> for the reaver feature I think that iw's quite useless but if you're ( very ) lucky you can get the wpa key before your phone battery will die."

**Comment by Rubenoo** [comment]
Oke i understand

**Comment by tux-mind** [comment]
duplicate of #320 ( even if WPS bruteforcing does not require monitor mode )

an it is **NOT** closed.

I think that this is a minor feature, but it won't require so much work, so let's make it.

obviously it has a low-priority ...
