### ISSUE TITLE
Big font in settings

### ISSUE THREAD

**Issue by Tajnymag** [cSploit/android#343]
After update I see a huge text in settings menu. It's easier to show you the screenshots than explaining, so here they are :)

Yesterday's nightly:
![screenshot 1 10 2015 18_03_58](https://cloud.githubusercontent.com/assets/3985946/10226418/8ff053d4-6867-11e5-83a2-163b73836d2d.png)

Nightly from now:
![screenshot 1 10 2015 18_06_31](https://cloud.githubusercontent.com/assets/3985946/10226419/8ff6aa86-6867-11e5-91a1-97295a6fcc74.png)

**Comment by fat-tire** [comment]
To anyone who has style issues, I'm going to point you to the `[style.xml](https://github.com/cSploit/android/blob/develop/cSploit/res/values/style.xml#L31-L38)` file, and request you submit any alterations you want.  You can change `PrefsTheme` and `PrefsThemeDark` to whatever you want.  This is, as you can see, the correct default theme based on the original theme (`AppTheme` and `DarkTheme`)

The size issue appears to be a [bug](https://stackoverflow.com/questions/32070670/preferencefragmentcompat-requires-preferencetheme-to-be-set) from google.  You can partially address this by changing the overlay to `@style/PreferenceThemeOverlay.v14.Material` and I guess I'll give this a try next.

**Comment by tux-mind** [comment]
I'm not an UI expert, but if a View behave differently from our expectation shouldn't be a bug ?

decision it's up to you @fat-tire :wink:

**Comment by fat-tire** [comment]
This may be a bug, but [it's not our bug](https://stackoverflow.com/questions/32070670/preferencefragmentcompat-requires-preferencetheme-to-be-set).  When Google [fixes it](https://code.google.com/p/android/issues/detail?id=183376), we should get the smaller font back.  That said, I actually don't think it hurts the readability or anything to have it larger.

I think we can close it, and when the support library is improved, this will (hopefully) automatically inherit the smaller style.

**Comment by tux-mind** [comment]
simply great :wink:
