### ISSUE TITLE
Cannot find core on this device

### ISSUE THREAD

**Issue by swerveonem** [cSploit/android#347]
I have tried to update the core and right after am prompted with an error that it does not find the core and force closes ..... Please help

**Comment by gainan** [comment]
Hi @swerveonem , thank you for your report. Please, take a moment to read this page about how to report bugs: https://github.com/cSploit/android/wiki/How-to-open-an-issue

Which version are you using? Have you tried out to restart the app?

**Comment by swerveonem** [comment]
Tried restarting.   Tried reinstalling.   Made sure it has root permission.   Using version 1.6 rc2

**Comment by gainan** [comment]
Please, upload logs using [logcat](https://wiki.cyanogenmod.org/w/Logcat)

**Comment by tux-mind** [comment]
@swerveonem closing for laks of info.

feel free to reopen if you get the logcat with the problem.

thanks for the report :blush:
