### ISSUE TITLE
csploit root 

### ISSUE THREAD

**Issue by BEOWULF74** [cSploit/android#351]
csploit dosent ask for root permission :sweat_smile:

**Comment by BEOWULF74** [comment]
iam using this version 1.6.0 RC2

**Comment by mcilya** [comment]
Can you post additional info in this issue using guide: https://github.com/cSploit/android/wiki/How-to-open-an-issue

**Comment by Haxin-hipopcorn** [comment]
give us more info please, use catlog, or you can close the issue, thanks

**Comment by newbie442** [comment]
Hey BEOWULF74 , check out settings>superuser, and look to see if SU was denied. Denied is the default if you don't grant it quickly, and during installation cSploit can slow things down a bit.

If so, click on the denial, hold, change to accept.

HTH

**Comment by BEOWULF74** [comment]
Solved I reinstalled csploit thx everyone

**Comment by tux-mind** [comment]
cSploit should alert you that root permissions are missing on boot.
so you get a good idea of what is the problem and solve it.

feel free to reopen the issue if the application didn't show you a warning about missing root permissions.

thanks for the report anyway :wink:
