### ISSUE TITLE
Notify and sounds

### ISSUE THREAD

**Issue by Haxin-hipopcorn** [cSploit/android#355]
For example, you got porta scanneds, a notify and a sound appears, ouro service inspetor, or you got a password in password sniffer... It will be awesome!

**Comment by maddog9696** [comment]
Could you please take a look at your post and correct mistakes so devs can hear out your suggestion! Maybe just me, but I don't think that is English ;)

**Comment by Haxin-hipopcorn** [comment]
@maddog9696 sorry automatic corretion... u know...
