### ISSUE TITLE
msf fails to download/install (but app still works)

### ISSUE THREAD

**Issue by akpegr** [cSploit/android#368]
First of all, please excuse me for the lack of a logcat or any other tech info, I'm already trying hard to post this from my device, I will provide more info as requested when I get home.

I am having the following issue with most of the latest versions of cSploit. Right after I install the app, I get the notification that there are new core, ruby and msf versions. I download and install core and ruby, however msn fails to install. It downloads, it extracts itself, and halfway there I get an error message stating that "there was en error while downloading the update" (rough translation from my language). Yes, the error is about downloading it (which, since it's extracting, I guess is false?) not installing the new version.

I'm using an HTC One M7, ViperOne 8.0.0 with Android 5.0.2. I also find a file named msf.tar.xz on my storage, which I presume should not be there after a successful install, right?

This happens in versions 1.5.4, 1.6.0 RC1, 1.6.0 RC2, and 1.6.0 (the one posted today, just a few hours ago) With 1.5.4 and the "old" msf version (which was released with the app a couple of weeks ago) I wasn't facing any problems so I guess in my case it must be an issue of the msf installation file. 

Just out of curiosity the last time I tried, I just pressed ok at the error message and went ahead to test the app. Well, it works! At least some of the features I tested (MITM, session hijacker, images/video replacement to be more specific) work with no issues whatsoever.

I will try to provide a logcat (if needed) ASAP, until then is there anything else I should try? Bare in mind that I don't have access to my computer for now, and my technical knowlegde is minimal, at best, so be gentle!

Thank you in advance :)

**Comment by fat-tire** [comment]
Is it possible that you have run out of room on your device so the download fails?

**Comment by akpegr** [comment]
Thanks for the reply! :)

Hmm doubt it, I've got 507mb free on root (system?) and another 2.5gb on the internal storage. I cleared another 0.5gb just to be sure.

I opened the app, prompted for an update, it checked it, extracted it, completed extraction, it started installing gems and at that exact moment (while installing gems) I got the error again.

**Comment by fat-tire** [comment]
TO be clear the `/system` directory is mounted "read only"-- in other words, you can't write to it, so the amount of space isn't important.

As for the other storage-- 2.5gb does seem to be enough room.  But the strange thing is that I think you said this time it was successful downloading and extracting msf but then got stuck on the next part (the gems).  Are you checking the internal storage (ie, `/data`) or external (`/data/external` or `/sdcard`)?  I'm not sure where the file is downloaded, but wherever you found that `msf.tar.xy` file is where you want to have sufficient space (if it is external), as well as in the internal storage.

Could the problem be damaged storage?

It would be worth getting a [logcat](http://wiki.cyanogenmod.org/w/Doc:_debugging_with_logcat) to know exactly what's wrong.  If you don't have access to a computer to collect the log, you can also use one of the many apps such as [catlog](https://play.google.com/store/apps/details?id=com.nolanlawson.logcat) which admittedly I've never used myself.  But there are [other apps](https://play.google.com/store/search?q=logcat) out there to try too.  If you are able to collect a log, you could post it at https://gist.github.com

**Comment by akpegr** [comment]
Actually all of those times it succeeded in downloading and extracting msf, I just got the download error. I now know it's caused by gems somehow failing to download and/or install and not by the download/extraction of msf itself.

I'm checking both, the file is downloaded in the external storage (the one with the 3GB free). I'll try to post a logcat with aLogcat.

**Comment by fat-tire** [comment]
Yeah, a logcat will be really helpful.  Thanks.

**Comment by akpegr** [comment]
Posted a logcat of the issue here: https://gist.github.com/akpegr/bddc75be48e94abb554e

Please be aware I'm using up the device for pretty much everything and it's full of apps and services running in the background, so apologies for the mess/size :)

I guess the error is around line 619, sadly I can't post the specific part since selecting and copying/pasting from a 1000 line document is problematic on DroidEdit, to say the least.

I'll continue troubleshooting this tomorrow, sleep deprivation has already taken it's toll. Thanks again :)

**Comment by fat-tire** [comment]
I wonder if this is related to #11 -- I see the same parsing issue related to rm.

**Comment by akpegr** [comment]
Apologies for the delay, I had to uninstall the up and start from scratch just to get a clean start.

Well, it turns out I had an obsolete version of busybox (1.23.1) installed. I downloaded BusyBox (stericson.busybox) from Play Store, updated it to 1.23.2 and tried again. Gems were successfully downloaded and installed, although download took a while and froze multiple times for a couple of seconds! I now get a notification stating Metasploit Status: Starting Metasploit RPDC: Standby..." which again took a while to turn to "Connected to Metasploit". Also I now see a "Stop Metasploit RPDC" option in settings. 

I guess the busybox update did the trick! Only "issue" I notice is that it takes a while to get the "Connected to Metasploit" status, about four to five minutes since starting the app. I have no idea if that's the way it works or if something on my device (or settings) could help it connect more quickly, but since I'm not a hardore user it doesn't bother me at all. 

Thanks for your help and guidance. Much appreciated. :)

**Comment by fat-tire** [comment]
Yep, I think the Metasploit RPCd does take a bit longer the first time (I'm assuming it needs to get everything all set up on the back end), but I don't think it will be so bad on subsequent runs.  Let us know tho if it's a continuing problem.

Glad you figured it out!  Enjoy...

**Comment by tux-mind** [comment]
thanks for supporting this gentle guy @fat-tire .

isn't related to #11 .
there was a network error when installing the bundle gem.
a permanent and clean solution is to include the bundle gem into the msf package, solving other similar problems. will do.

thanks for the detailed report and your patience @akpegr , really appreciated :blush:
