### ISSUE TITLE
app abort forced on start up

### ISSUE THREAD

**Issue by gainan** [cSploit/android#371]
On a subnet with ~250 hosts, android forces the app to abort. On the logs I see that network radar scans fine the net, all hosts returned, but after that android closes the app and this is logged:

>Fatal signal 6 (SIGABRT) at 0x0000019b (code=0), thread 30639 (csploit.android)

too much spawned processes maybe?

Edit 1:
If I leave csploit to discover all the subnet without touching the list, it finishes. However if I scroll down while it is discovering hosts is when this problem appear.

**Comment by tux-mind** [comment]
that signal is thrown by dalvik ( or art ) when you make something bad in the JavaVM.
please post the full logcat ( without filters ) :wink: 

thanks for the report :blush:

**Comment by gainan** [comment]
I'll share it with you on a gist on the irc ;)

**Comment by gainan** [comment]
anr output:
[traces_org.csploit.android.txt](https://github.com/cSploit/android/files/7717/traces_org.csploit.android.txt)

**Comment by gainan** [comment]
bug fixed with https://github.com/cSploit/android/commit/21187111a5d24ba4c21f9a1577edf64d110e40b0
