### ISSUE TITLE
java.lang.ArrayIndexOutOfBoundsException: length=3; index=7 : at org.csploit.android.core.System.getTarget(System.java:1032)

### ISSUE THREAD

**Issue by gainan** [cSploit/android#376]
Reported with version 1.6.0*, and still present on all branches.

>java.lang.ArrayIndexOutOfBoundsException: length=3; index=7
at java.util.Vector.arrayIndexOutOfBoundsException(Vector.java:907)
at java.util.Vector.elementAt(Vector.java:328)
at java.util.Vector.get(Vector.java:442)
at org.csploit.android.core.System.getTarget(System.java:1032)
at org.csploit.android.MainActivity$TargetAdapter.getView(MainActivity.java:850)

Under certain situations when scrolling the hosts list, getTarget() can not return a target.

possible fix which returns the cached view:
>\-    Target target = System.getTarget(position);
>\+   Target target = System.getTarget(position);
>\+   if (target == null)
>\+     return row;

**Comment by fat-tire** [comment]
Looks like this was fixed (?) by replacing `Target target = System.getTarget(position)` with `Target target = list.get(position);` in:

https://github.com/cSploit/android/commit/80c612503ead11f2f51007f9baede185edd9c571

**Comment by gainan** [comment]
great finding @fat-tire !, I didn't find this when reporting it. I will take an eye on the reported bugs, and if it is not reported I will close it.

**Comment by tux-mind** [comment]
yep, solved in 80c6125 .
thanks for the report :blush:
