### ISSUE TITLE
Installing gems...

### ISSUE THREAD

**Issue by GhostSamurai** [cSploit/android#38]
My device(GS4) says installing gems for MSF but it has not downloaded it just stays stuck there. Is the file really big? It has been saying downloading for the past 5-10 mins. Should I just let it run or try to start it over? Thank you. Great work I look forward to get this up and working like I had Dsploit working on my GS4.

**Comment by tux-mind** [comment]
@1234xm4321 you are affected by #11 , you can fix it by installing busybox for the moment.

@GhostSamurai i cannot detect the problem from your log.

can you reproduce and post both logcat and cSploitd.log ?
thanks in advance for your time :blush:

**Comment by tux-mind** [comment]
@WanderingFool thanks for your help in helping people there :smiley: 

the `installing gems...` process is slow because it install a lot of gems from rubygems.org

**Comment by Anotherenduser** [comment]
Still same on 1.24, installs gems forever then says Metasploit update available and starts all over. Never finishes.

**Comment by tux-mind** [comment]
@Anotherenduser please provide logcat and cSploitd.log

cSploitd.log can be found in `/data/data/org.csploit.android/files` .

**Comment by WanderingFool** [comment]
Sorry for a late reply (boss is working me to death).
Here is a logcat and cSploitd for what seems to be the same or similar issue http://filebin.ca/1oBDyd3oFt5z

cSploit will download ruby.tar.xz. When it's finished, it will produce a error message "An error occurred while downloading the update.".

Hardware:Galaxy S5 Active, rooted, SuperSU
Model number: SAMSUNG-SM-G870A
Android version: 4.4.2
Baseband version: G870AUCU1ANE4
Kernel version: 3.4.0-2304514 dpi@SWDD5506 #1 
Build number: KOT49H.G870AUCU1ANE4
Busybox version: 1.23.0

A previous cSploit nightly build just before the 1.2.4 release was mostly working on my device, but I don't have the apk for it anymore.

@tux-mind I try to help what I can and when I can. Feel free to ask for something and I'll help if I can.

**Comment by tux-mind** [comment]
@WanderingFool you are affected by #1 ...

you have to wait that I fix that one...

**Comment by tux-mind** [comment]
@Anotherenduser close due to lacks of info.
feel free to reopen when you have the logs that I have requested.
