### ISSUE TITLE
Catalog integration

### ISSUE THREAD

**Issue by Haxin-hipopcorn** [cSploit/android#381]
A catalog our something integrated with csploit, to  report issues automatically by the app(newbies for example don't know how to make issues) .
This can be divided by 2 parts :
1 - make a kind of catlog and save files for every error and some weeks it will be excluded
2- report issue automatically, can be sending by email.

It will improve csploit for sure, and will be easy for @tux-mind

**Comment by tux-mind** [comment]
I was already working on it.

when a native program crashes cSploit will get all your logcat into the crash report.
I suggest to use ACRA to report bugs but I don't known how to connect it to github...

if we can get back the report ID from ACRA we can open the issue with that ID as first message.

**Comment by tux-mind** [comment]
moved to #64
