### ISSUE TITLE
MSF rpcd fail to start

### ISSUE THREAD

**Issue by CreekOne** [cSploit/android#384]
As title says.

Logcat says:
---- 6 Oct 2015 11:59:04 am ----

10-06 11:58:03.725 11676 11676 I Timeline: Timeline: Activity_launch_request id:org.csploit.android time:312576468

10-06 11:58:03.727 11099 15055 I ActivityManager: START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=org.csploit.android/.MainActivity bnds=[536,752][712,982] (has extras)} from uid 10018 on display 0

10-06 11:58:03.876 11099 11983 I ActivityManager: Start proc 20295:org.csploit.android/u0a84 for activity org.csploit.android/.MainActivity

10-06 11:58:05.095 11099 11141 I ActivityManager: Displayed org.csploit.android/.MainActivity: +1s281ms

10-06 11:58:05.095 11099 11141 I Timeline: Timeline: Activity_windows_visible id: ActivityRecord{3960b0ea u0 org.csploit.android/.MainActivity t2978} time:312577838

10-06 11:58:06.444 11408 11408 W PackageManager: Failure retrieving resources for org.csploit.android: Resource ID #0x0

10-06 11:58:07.473 11408 11408 W PackageManager: Failure retrieving resources for org.csploit.android: Resource ID #0x0

10-06 11:58:27.582 11099 11141 I Timeline: Timeline: Activity_windows_visible id: ActivityRecord{3960b0ea u0 org.csploit.android/.MainActivity t2978} time:312600325

10-06 11:58:30.290 20295 20389 I Timeline: Timeline: Activity_launch_request id:org.csploit.android time:312603033

10-06 11:58:30.292 11099 11683 I ActivityManager: START u0 {cmp=org.csploit.android/.ActionActivity} from uid 10084 on display 0

10-06 11:58:31.407 11099 11141 I ActivityManager: Displayed org.csploit.android/.ActionActivity: +1s60ms

10-06 11:58:31.845 11099 11141 I Timeline: Timeline: Activity_windows_visible id: ActivityRecord{197ee9d9 u0 org.csploit.android/.ActionActivity t2978} time:312604588

10-06 11:58:33.052 20295 20295 I Timeline: Timeline: Activity_launch_request id:org.csploit.android time:312605795

10-06 11:58:33.053 11099 11581 I ActivityManager: START u0 {cmp=org.csploit.android/.plugins.Sessions} from uid 10084 on display 0

10-06 11:58:33.443 11099 11141 I ActivityManager: Displayed org.csploit.android/.plugins.Sessions: +364ms

10-06 11:58:33.864 11099 11141 I Timeline: Timeline: Activity_windows_visible id: ActivityRecord{26ff116f u0 org.csploit.android/.plugins.Sessions t2978} time:312606607

10-06 11:58:36.186 11099 11141 I Timeline: Timeline: Activity_windows_visible id: ActivityRecord{197ee9d9 u0 org.csploit.android/.ActionActivity t2978} time:312608929

10-06 11:58:36.903 11408 11408 W PackageManager: Failure retrieving resources for org.csploit.android: Resource ID #0x0

10-06 11:58:38.955 11408 11408 W PackageManager: Failure retrieving resources for org.csploit.android: Resource ID #0x0

---- 6 Oct 2015 11:59:04 am ----

**Comment by CreekOne** [comment]
Forgot to add its version 1.6.0.
I did remove MSF an reinstalled it after updating.. No luck.

Its on lollypop 5.1.1 CM 12.1

**Comment by tux-mind** [comment]
Hi @CreekOne please report a logcat following instructions from [here](https://github.com/cSploit/android/wiki/How-to-open-an-issue).

thanks for the report :blush:

**Comment by pgolecha** [comment]
@tux-mind Same issue after msf update.
Reinstalling didn't help

Log:
http://pastebin.ca/3182904

**Comment by tux-mind** [comment]
thanks for the report @pgolecha , can you also provide `/data/data/org.csploit.android/files/cSploitd.log` ?

thanks in advance :blush:

**Comment by pgolecha** [comment]
@tux-mind 
Here http://pastebin.ca/3183680

**Comment by pgolecha** [comment]
@tux-mind Everything works fine after a reinstall or mayble it is the update

**Comment by tux-mind** [comment]
feel free to reopen @CreekOne if not solved with last versions.

as I can see from the logs you are affected by #1 , but the workaround is not applied...
