### ISSUE TITLE
missing port service name in Port Scanner

### ISSUE THREAD

**Issue by Rubenoo** [cSploit/android#387]
No port information given at the develop branch from 2 hours ago(latest commit:Merge pull request #385 from mcilya/patch-2 ) it use to give information by the ports to explain what the ports are
![device-2015-10-06-172933](https://cloud.githubusercontent.com/assets/13369779/10313706/4465af20-6c51-11e5-8e77-cecbf8235c7d.png)

Samsung galaxy s5 android 5 full rooted/busybox
Logcat: https://gist.github.com/Rubenoo/f9d3ee8acc870601222a

**Comment by Rubenoo** [comment]
Fix: Restart the app and it works again :)

**Comment by tux-mind** [comment]
not a fix

**Comment by fat-tire** [comment]
Ideally I'd like to see the port list be clickable and launch an app w/the corresponding service...

**Comment by gainan** [comment]
I think it's possible already, by long clicking on it. Maybe it could be change to a simple click.

**Comment by tux-mind** [comment]
we can make the port scanner plugin active ( not grayed out ) if services has been loaded.

so we can solve both this and #353

**Comment by gainan** [comment]
@Rubenoo , is this problem fixed?

**Comment by Rubenoo** [comment]
I think so @gain an if not I reopen this issue
