### ISSUE TITLE
MITM Simple Sniff won't write pcap file

### ISSUE THREAD

**Issue by clemensc** [cSploit/android#388]
Sniffing without writing to file shows traffic w/o problems.
Running latest v1.60, tried on 3 different Nexus 7 2013, tried on both stock 4.4.4 as well as Cyanogen 4.4.4. No xposed or other frameworks installed. 
Ran into this problem with all previous csploit versions as well. Writing to file used work with Dsploit for me.

**Comment by gainan** [comment]
thank you for the report @clemensc , could you post what version are you using? as well as the logcat please.

**Comment by tux-mind** [comment]
@clemensc please give us more info, we need your help to fix this bug.
@gainan did you tested it ? does it work for you ?

thanks in advance for testing ;)

**Comment by gainan** [comment]
yeah, working fine for me.

**Comment by gainan** [comment]
@clemensc , try out the latest nightly and check out if the problem is fixed. Feel free to reopen it again if it's not.
