### ISSUE TITLE
suggestion

### ISSUE THREAD

**Issue by PTZema** [cSploit/android#395]
Hey guys, what you think that csploit can read the .pcap files?

**Comment by PTZema** [comment]
And ssl strip ;)

**Comment by mcilya** [comment]
@PTZema SSLstrip already implemented :smile:

**Comment by tux-mind** [comment]
@PTZema cSploit it's becoming an huge suite of pentesting tools, we have too much stuff to work on and we are only 3/5 people.

I remember that there was a pcap file viewer out there on the play store time ago.

rejected.

**Comment by tux-mind** [comment]
thanks for the suggestion anyway :blush: 

keep posting, :wink:

**Comment by PTZema** [comment]
Right ;) how ssl strip works in csploit?
