### ISSUE TITLE
Can't open multiple shell

### ISSUE THREAD

**Issue by 0MazaHacka0** [cSploit/android#402]
I installed metasploitable2 on my virtualbox and sucess pwned it with csploit. Also, csploit open shell to metasploitable and i can send command. But, i am pwned another server and csploit also open new shell. Than i connect to it i am connecting to my metasploitable. So if 1 shell is open, you can't use other.

**Comment by tux-mind** [comment]
we're are working on changing the way the consoles and session works.
but it require some big efforts, some week i bet.

thanks for the report :blush:
