### ISSUE TITLE
Cannot find a core for this device

### ISSUE THREAD

**Issue by werta600** [cSploit/android#404]
I just saw that a new "dsploit" was being developed, so i googled a bit and found this new cSploit. But i couldnt manage to start using it.

When started, csploit pops up a message that says a new core version is available, so i download it, but after downloading and updating, it says: "cannot find a core for this device" and it closes. I tried to not update core, but i closes and wont work without updating core.

Phone: Orange Hi 4g (Rooted), Android KitKat 4.4.2

LogCat log (covers since first start of cSploit till the app closes) (Sorry but github wont allow me upload .txt file, it says "Something went really wrong, and we cant process that file")

HERE IS THE LOGCAT GIST:

https://gist.github.com/1fb013b86a86ce74acff.git

The link above seems not working for me (or im just too noob), so here's pastebin link too:

http://pastebin.com/BdeMQXHD

**Comment by gainan** [comment]
Hi @werta600 , thank you very much for your report :). You can post the logcat to pastebin.com, or create a public [gist](https://gist.github.com/)

**Comment by werta600** [comment]
Okay thanks gainan, i have uploaded it to a public gist... Here's the link:

https://gist.github.com/1fb013b86a86ce74acff.git

**Comment by maddog9696** [comment]
Don't know if issue is the same however on my galaxy tab 8.4 sm-t320 (cm12.1) with any version of Csploit it will always tell me there's a core update available, it downloads and I believe it installs but after that I get a message no core for this device. Click okay, app restarts and updates continue and everything works. Thought I'd share here

**Comment by tux-mind** [comment]
@werta600 can you share a logcat taken after restarting cSploit ?
thank you in advance for your time :wink:

**Comment by gainan** [comment]
just happened after installing the latest 1.6.1:
>10-13 22:36:06.351  11852-11897/org.csploit.android I/CSPLOIT[services.UpdateService.downloadFile]﹕ download finished successfully
10-13 22:36:06.351  11852-11897/org.csploit.android I/CSPLOIT[services.UpdateService.verifyArchiveIntegrity]﹕ verifying archive integrity
10-13 22:36:28.781  11852-11897/org.csploit.android I/CSPLOIT[services.UpdateService.extract]﹕ extracting '/storage/sdcard0/core.tar.xz' to '/data/data/org.csploit.android/files'
10-13 22:36:54.161  11852-11897/org.csploit.android I/CSPLOIT[services.UpdateService.extract]﹕ extraction completed
10-13 22:36:54.161  11852-11897/org.csploit.android I/CSPLOIT[services.UpdateService.extract]﹕ .nomedia created
12108-12108/? W/su﹕ request rejected (10068->0 /system/bin/sh)
10-13 22:37:27.121  11852-11852/org.csploit.android W/CSPLOIT[core.System.startCoreDaemon]﹕ STDERR: Permission denied
10-13 22:37:27.281  11852-12264/org.csploit.android W/CSPLOIT[services.UpdateChecker.getCoreUpdate]﹕ unsupported platform ( android19.armeabi-v7a )

cyanogen 11, 4.4.4.

**Comment by werta600** [comment]
Ok, here u are:

This is the first logcat taken, but somehow the app crashed before start:

http://pastebin.com/cmRQWNSN

This one is the second after the above, and the app runs as it should, it shows the message "cannot find a core for this device" and then closes:

http://pastebin.com/ekSUHvXF

**Comment by gainan** [comment]
@werta600 , I think you are using the 1.6.0 version, and tux-mind released a new version yesterday with a ton of bugs fixes, could you download it and try it out again? Remember to take logs as you already did earlier.
https://github.com/cSploit/android/releases/download/v1.6.1/cSploit-release.apk

Thank you and sorry for the inconveniences :)

**Comment by werta600** [comment]
Oh thanks for the reply, but still i got the same result "cannot find a core for this device", will do new logcats if needed

**Comment by tux-mind** [comment]
just a sec @werta600

**Comment by tux-mind** [comment]
@werta600 just release 1.6.2 .
feel free to reopen if the problem is not solved.

thanks for the report :blush:

**Comment by xaitax** [comment]
FYI everyone: Cronjob is building now every 3 minutes the nightly (if there are new commits) in case you want to test urgent fixes.

**Comment by tux-mind** [comment]
we :heart: @xaitax

**Comment by werta600** [comment]
Well, the problem is half-solved, still cant make the app to work properly... Now it doesnt shows the message "cannot find a core... etc", but it wont scan the network and i cant test any target...

App's background shows: "Heart attack occurred, the application will just check for updates. No hay actualizaciones disponibles" and i cant do nothing.

If i try to select a custom target using IP, the app will crash.
