### ISSUE TITLE
startup crash

### ISSUE THREAD

**Issue by damks** [cSploit/android#41]
Hey tux,

I've got a problem at starting cSploit. It will always crash.
cyanogenmod nigthly (superuser, full busybox)

The log can be found here: http://pastebin.com/7NUq7bm3
(includes installing / uninstalling csploit, removes Appdata etc..)

**Comment by tux-mind** [comment]
thanks for the logcat, can you provide additional info about the device ?
model, android version...

thanks in advance.

**Comment by damks** [comment]
Oh of course....

Moto G
Droid: 4.4.4

**Comment by tux-mind** [comment]
probably it's caused by the hundreds of sockets opened by the network discovery.

will fix with the `network-monitor` utility.

**Comment by tux-mind** [comment]
@damks can you test the latest version ?

open cSploit with a working internet connection, it will prompt you that an update is available.

thanks in advance for your time.

**Comment by damks** [comment]
Works great.
no problems or crashs so far.

Thanks for fixing. :+1:
