### ISSUE TITLE
CSploit on sdcard

### ISSUE THREAD

**Issue by MuradTroll** [cSploit/android#410]
Hello, 

I tried to download csploit.android.msf and csploit.ruby from github and unpacked them in sdcard. Then I loccated their paths in the sdcard, but I get a bug

Wheb I start csploit the function "start metasploit rpcd" in the menu is grayed out.

Also catlog say something like

/path/to/msf/on/sdcard/VERSION: ENONET no such file or directory

I looked by myself and couldnt find a file.called VERSION (not even in the github)

Seems like i cannot just put the packages on sdcard...

Also sorry for not posting logs or catlog but i think it is just because i did sonething wrong. Maybe its related to gems because they will.normaly be installed automatically by the app

Thx in advance

**Comment by h439098** [comment]
Go this way : 
1. Install CSploit
2. Open. Install CORE. And dismiss other installations.
3. Open settings. Change directories for RUBY and MSF to the empty ones.
Example : 
MSF = to the empty folder "1" on sdcard.
RUBY = to the empty folder "2" on sdcard.
4. Restart the app.
5. Accept all installations.
NOW you have CSploit on sdcard.

**Comment by MuradTroll** [comment]
@h439098 does this way really work?

**Comment by h439098** [comment]
yep. I'm doing like that. CSploit will download all files automatically to sdcard.

**Comment by MuradTroll** [comment]
@h439098 thx just tried out works! +++

**Comment by tux-mind** [comment]
@MuradTroll ruby and MSF must be patched after the download.
this because every device has it's own place where the `env` program is installed.

installation isn't only an extraction, it involves other steps that cSploit will do for you.

thanks for the report anyway :blush:
