### ISSUE TITLE
Question about Csploit use

### ISSUE THREAD

**Issue by maddog9696** [cSploit/android#413]
Within the settings there's an option to choose msf branch. By default there doesn't seem to be one selected. I assume this is the place your getting the msf package from?? What should it be set to master, developer, don't touch it??

**Comment by Rubenoo** [comment]
I think that it selects by default the csploit branch, and that's the good one

**Comment by sorano** [comment]
Just dont touch it unless you have a specific reason ;)
csploit is the default.

**Comment by tux-mind** [comment]
it's an old setting @maddog9696 , will remove it ASAP, thanks for pointing it out :wink:
