### ISSUE TITLE
Problem with Ruby download

### ISSUE THREAD

**Issue by Nils001** [cSploit/android#418]
Hello,
I use the LG G4.
Everytime the app tries to upgrade Ruby it says that there was a error.
Can i install ruby manually ?

**Comment by Rubenoo** [comment]
https://github.com/cSploit/android/wiki/How-to-open-an-issue please read that first.  We need more details about the problem to fix it

**Comment by Nils001** [comment]
Im using the Stock Rom.
The app starts and asks for an update of ruby.
If i click yes the update fails but it is possible to scan port and do everything.
The app does not crash.
please tell me if you need further information.

**Comment by xaitax** [comment]
I bet not rooted or if, no busybox installed.

**Comment by Nils001** [comment]
i got both

**Comment by Nils001** [comment]
busybox free from your link

**Comment by Nils001** [comment]
found the bug .. something in my firewall was blocking the install.
