### ISSUE TITLE
Thoughts about zanti3

### ISSUE THREAD

**Issue by maddog9696** [cSploit/android#419]
So @tux-mind, @fat-tire, @gainan, @developpSoft and other amazing devs, what are your thoughts about zanti3 and how it's going to be open source.

Tux on your site youv said: "NOTE: Evilsocket told, that in a far future zANTI2 will be open source, but I don't want to wait for this, I want to finish all original dSploit TODOs." Are your goals with csploit still the same now that zanti is open scource?  

And now that is open scource, are any of you thinking about contributing to that project/applying for a dev spot?

Please share any and all thoughts/commits. 

I'm only asking out of curiosity, however, if you'd prefer me not asking such questions here, please feel free to delete this post! 😉

**Comment by tux-mind** [comment]
where I can find the sources ?

**Comment by xaitax** [comment]
It never went OSS even though announced since July. My bad/good guess it never will. Zimperium wants to make money with it.

**Comment by Settix** [comment]
Yeah, I tried to get zanti's sources but i've never found them..sharing the same opinion as @xaitax.
We have to fill in a form then, be chosen by the entreprise in order to contribute to the project .
link : https://blog.zimperium.com/the-rise-of-zanti3-call-for-developers/

**Comment by Systenix** [comment]
I have the source of an old version version of zAnti (before the release of zANTI2).
By cons I do not know if the code is understandable.
I did not try to compile it. I can provide it if some are curious.

**Comment by DeveloppSoft** [comment]
If we access the sources, it is OK for me.

**Comment by DeveloppSoft** [comment]
And please note I already fill the form some months ago without ANY answer

**Comment by newbie442** [comment]
ISTM cSploit will be heads and tails a better tool. 

Right now mature zANTI may be quicker to load, but cSploit uses leading-edge metasploit techniques; when cSploit gets up to speed zANTI will constantly be trying to keep up with cSploit.

**Comment by Systenix** [comment]
I don't work with Zimperium.
Here is the link to access sources : 
https://www.dropbox.com/s/xs6qbie1q6fkn0w/zAnti_Project.rar?dl=0

**Comment by pgolecha** [comment]
@Systenix It looks like a Decompiled code rather than the orignal source.

**Comment by Systenix** [comment]
I'm not an expert in Java.
Maybe parts of this code can inspired the development of cSploit .
If someone have an adventurer soul and manages to compile this bunch of code, please share your work with us.

**Comment by gainan** [comment]
I think that this is not the place for talk about this, for now at least. I had an answer, but seeing all the work tux-mind is doing, all the app testing to be done and all the bugs that people is reporting, for now I think this is the least of our problems. 

If you guys want to join us on the irc, we can share our opinion on this subject :)

**Comment by Systenix** [comment]
I understand.
What is the channel of the irc ?
(also, thx for the work and for the time that you guys put in this OP project.)
One day, this project will be a reference in the pentest (and hacking) world.

**Comment by gainan** [comment]
irc: https://webchat.freenode.net/?channels=csploit

**Comment by gainan** [comment]
interesting thread. if someone wants to keep discussing about it stop by the irc.

**Comment by prbhtkumr** [comment]
it's 2021 and i still can't find the source code to zANTI.

**Comment by Silur** [comment]
zAnti became a proprietary product of zImperium, and now it's also an abandoned app
