### ISSUE TITLE
1.6.1 crash during core update

### ISSUE THREAD

**Issue by homer2320776** [cSploit/android#424]
Program will install fine. Tried to update core then straight crash

https://gist.github.com/homer2320776/8ee3862fef087a1e49d1

**Comment by fabinhojcr** [comment]
Is going error when installing the core, tested the latest version and previous Csploit, I believe that the error is in the core.

**Comment by homer2320776** [comment]
@fabinhojcr I can use the latest nightly fine. 1.6 and 1.6.1 both crash for me.

**Comment by boo44** [comment]
Not find the core and than Crash?

**Comment by Foul** [comment]
Crash at Start for me..

**Comment by tux-mind** [comment]
OMG, I think that I missed to include jni libs into the apk...

give me a sec

**Comment by tux-mind** [comment]
fixed, please download [1.6.1](https://github.com/cSploit/android/releases/download/v1.6.1/cSploit-release.apk) apk and install it again.

sorry for the inconvenience.

**Comment by boo44** [comment]
Password sniffer Not Work?
And Cookies hack Not work

**Comment by tux-mind** [comment]
@boo44 `Not Work` means ???

**Comment by gainan** [comment]
@boo44 , please, give more details, and proofs. That problem is not related anyway to this issue.

**Comment by boo44** [comment]
J Start the sniffer and not Come traffic please can test This and See

**Comment by tux-mind** [comment]
fixed by rebuilding the apk with jniLibs.

@boo44 feel free to open a bug report on another issue following [this guide](https://github.com/cSploit/android/wiki/How-to-open-an-issue).

we will give it a look anyway, thanks got the report.
