### ISSUE TITLE
Error dsploit 

### ISSUE THREAD

**Issue by LazyBacOn** [cSploit/android#425]
The application said: file is corrupt when i try to update "core"

**Comment by uranium-waffles** [comment]
We can't really tell you anything other than to uninstall and reinstall if you don't provide a logcat.

**Comment by sorano** [comment]
Try again: https://github.com/cSploit/android/releases/download/v1.6.2/cSploit-release.apk

**Comment by pgolecha** [comment]
Just delete the core tar from your root directory and try updating it again

**Comment by tux-mind** [comment]
@pgolecha +1
