### ISSUE TITLE
Heart attack occured, app will just check updates

### ISSUE THREAD

**Issue by werta600** [cSploit/android#428]
Hi again, since i can't reopen last issue #404 i created a new one...

Answer copied from last issue: 

"Well, the problem is half-solved, still cant make the app to work properly... Now it doesnt shows the message "cannot find a core... etc", but it wont scan the network and i cant test any target...

App's background shows: "Heart attack occurred, the application will just check for updates. No hay actualizaciones disponibles" and i cant do nothing.

If i try to select a custom target using IP, the app will crash."

First logcat, shows from app start since i close it, just app starting and then closing. (No crashes):

http://pastebin.com/HviDzxyA

Second logcat, shows from app start till crashes, i tried to tap on Explore option but nothing happens, then i try to select a target via IP and the app crashes:

http://pastebin.com/Ffj6Di6p

**Comment by tux-mind** [comment]
@werta600 thanks for testing, I just fixed the crash bug, try out the nightly build to verify it.
to solve the heart attack problem try to do the following:

  - clear application data
  - open cSploit
  - install the core
  - use cSploit

if you still cannot use cSploit please post the core of the core installation process.

thank you for your precious time :blush:

**Comment by werta600** [comment]
@tux-mind i think im too noob, but i cant find the nightly build, dont know if its in the official website or here in github

**Comment by Megaeloelo** [comment]
Me too .
My logcat : http://pastebin.com/SBmYnhs9

**Comment by TretornESP** [comment]
Same problem here (can't post logcat as i'm on my desktop computer right now)

**Comment by tux-mind** [comment]
that's another issue: #443 
fixed.

**Comment by geohdgio** [comment]
have same problem and cant fix it

**Comment by geohdgio** [comment]
may i know when csploit2 will came out?

**Comment by Rubenoo** [comment]
@geohdgio The development of cSploit2 is a hard and long process, so we can't give a exact ETA. However the team has made alot of progress developing cSploit2. To make sure that your updated on the development of cSploit keep an eye out on the GitHub or go to www.csploit.org once in a while :)

**Comment by tux-mind** [comment]
Thanks Rubenoo, we are reaching an alpha state of the web app. After that
we can start working on a mobile client ( both Android and iOS ) which talk
with the cSploit server ( say your raspberry pi ).

Next step will be to run the server on the same device of the client ( your
phone ), initially only for Android, iOS to check for feasibility.

My apologies for taking so long, but I'm still working and studying, it's
not easy to find the time for my passions, but I'm doing my best.

Il 19 gen 2017 10:48 PM, "Rubenoo" <notifications@github.com> ha scritto:

**Comment by Silur** [comment]
@werta600 What android version are you using? Several people reported this issue my guess is that SELinux prevents the app from starting native ELFs on the system but I need a confirmation that you have at least 6.0 or above android

**Comment by werta600** [comment]
@Silur I have no longer that phone (the issue is from a year ago), it had android 4.4.2

My current phone has 6.0.1 but its not rooted so i cant test the app

**Comment by festimii** [comment]
Hello im having problem with all csploit versions thay fail to install the core or other problem is there any stable version and Congrats to your great job with the Csploit...
