### ISSUE TITLE
Inspector button not working

### ISSUE THREAD

**Issue by Megaeloelo** [cSploit/android#430]
Android : 4.4.2
Rom : Stock
Phone : Blackview Zeta
Problem : I cannot press the button in the Inspector services. I click and the inspector did not want to start work. Sorry for bad english .

**Comment by Megaeloelo** [comment]
Csploit version : 1.6.2

**Comment by gainan** [comment]
Thank you for the report @Megaeloelo It is a known bug, already fixed on the dev branch. @fat-tire

**Comment by Megaeloelo** [comment]
Btw latest nightly crash in installing core .
Logcat: http://pastebin.com/SBmYnhs9 .
Sorry for english .

**Comment by sorano** [comment]
Inspector works in 1.7.0unstable.

Nightly is missing jnilibs, can continue that in #431
