### ISSUE TITLE
Jsi stuff error

### ISSUE THREAD

**Issue by Tajnymag** [cSploit/android#431]
When I open latest nightly, I get error saying: " Hi developer, you missed to build JNI stuff, thanks for playing with me :)  "

**Comment by sorano** [comment]
@xaitax seems like nightly is missing jnilibs.

**Comment by xaitax** [comment]
Try again please.

**Comment by Tajnymag** [comment]
I tried downloading the nightly again. Nothing. So I tried reinstalling, but then cSploit crashes while downloading the core. [Here](https://drive.google.com/file/d/0B-K8l_xTlaFrUWdhQnpzam9ublk/view?usp=sharing) is the log.

**Comment by Megaeloelo** [comment]
Latest nightly crashing .

**Comment by Megaeloelo** [comment]
Here is my log :http://pastebin.com/SBmYnhs9

**Comment by sorano** [comment]
@xaitax still nothing.

If I extract your apk:
find nightly_apk/ -type d -name armeabi* yields nothing

when I compile myself I put them here:

find StudioProjects/csploit/ -type d -name armeabi* 
StudioProjects/csploit/cSploit/src/main/jniLibs/armeabi-v7a
StudioProjects/csploit/cSploit/src/main/jniLibs/armeabi

**Comment by xaitax** [comment]
Please try the last nightly.
Build log is here: http://paste2.org/N8313sH4

**Comment by xaitax** [comment]
I assume the issue is here:
https://github.com/cSploit/android/commit/81473fed1ca83b097fca46833f23fe5c27a5925e

**Comment by 0MazaHacka0** [comment]
Can you make a fix?

**Comment by 0MazaHacka0** [comment]
@tux-mind help us please

**Comment by sorano** [comment]
Use the normal release until nightly works again.

See #443
