### ISSUE TITLE
Login Cracker Crash on start

### ISSUE THREAD

**Issue by uranium-waffles** [cSploit/android#435]
Android  lollipop 5.0
Samsing galaxy s5 G900V rooted
cSploit 1.6.2
Logcat can be found here http://pastebin.com/UG4qnaKK

Whenever I try to use the login cracker a crash notification pops up saying that cSploit has crashed.

**Comment by gainan** [comment]
This is the same problem of #236 . Moving it in order to do the tracking there. Thanks for the report as always :)
