### ISSUE TITLE
Nightly crash when try to install core

### ISSUE THREAD

**Issue by 0MazaHacka0** [cSploit/android#438]
Nightly cSploit crash when try to install core after it downloaded. 
CatLog http://pastebin.com/TeTgL16b

**Comment by gainan** [comment]
>10-15 20:45:03.152 E/ACRA    (2471): java.lang.UnsatisfiedLinkError: Couldn't load cSploitCommon from loader dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/org.csploit.android-1.apk"],nativeLibraryDirectories=[/data/app-lib/org.csploit.android-1, /vendor/lib, /system/lib]]]: findLibrary returned null

Same problem than #431, and presumibly already fixed.
