### ISSUE TITLE
Cannot start Process ? Huawei devices.

### ISSUE THREAD

**Issue by DNBkid** [cSploit/android#44]
Hello tux-mind . First of all i would like to thank you for your great work. 
And to choose to continue developing this great APP called Csploit. 
Im great fan of your work !

My problem is that since version 1.1.3b the program could not install metasploit ,and now after i try installing the latest versions i get this error Cannot start process.  I hope my catlog would be helpfull for you! If you need other information ill be in touch. : )  
I have tried original roms ,and custom roms ,and im still getting the same error.

Here is my catlog   http://dox.bg/files/dw?a=18e5399703

**Comment by DNBkid** [comment]
Rooted, Busybox pro ,TWRP, SU

**Comment by tux-mind** [comment]
my bad with versioning.

will fix ASAP.

as workaround install only releases, not pre-releases.

**Comment by tux-mind** [comment]
ok I understood the problem, will pay more attention with next releases.

`1.2.4` is a release and is considered more recent then `1.2.4-issue1`, which is a pre-release.

i have to use `1.2.5-issue1` next time.

thanks for reporting the problem.

**Comment by DNBkid** [comment]
I`m not sure but i think that you have resolved the issue because i have uninstalled csploit and installed it again and after ruby update then metasploit have downloaded and updated finaly for the first time without errors and i think that now is working fine !  Congratulations ,ill test it couple if days idn ill tel you if everything is fine !

**Comment by DNBkid** [comment]
ups after i restarted the phone still gives me cannot start process but now metasploit is installed finaly ill post my catlog in  MSF update error #43   .
