### ISSUE TITLE
Nightlies are broken...

### ISSUE THREAD

**Issue by fat-tire** [cSploit/android#443]
Because of a recent [commit to the develop branch](https://github.com/cSploit/android/commit/81473fed1ca83b097fca46833f23fe5c27a5925e), the location for the prebuilt libraries has moved from

`./cSploit/src/org/csploit/android/jniLibs/`

to

`./cSploit/src/main/jniLibs/`

I think the build script for the nightlies needs to know this :)

**Comment by xaitax** [comment]
I am on a flight right now but will change the build script whenI arrive inba few hours. :)

**Comment by dexofan23** [comment]
fixed?

**Comment by xaitax** [comment]
Try again please. Had to update the support SDK.
