### ISSUE TITLE
Crash on installing core

### ISSUE THREAD

**Issue by 0MazaHacka0** [cSploit/android#446]
I have intalled night build and it crashed again.

**Comment by mcilya** [comment]
Can you say version of csploit from settings?

**Comment by sorano** [comment]
Nightlies are called nightly for a reason.

There is currently a known issue that its not shipped with jnilibs so please use the standard release (1.6.2) for now. Give it a couple of days and nightly will be working again most likely.

**Comment by xaitax** [comment]
Check again please.

**Comment by 0MazaHacka0** [comment]
All is ok
