### ISSUE TITLE
cSploit

### ISSUE THREAD

**Issue by Zema7th** [cSploit/android#447]
Не работает инспектор, не нажимается кнопка   пуска, а если он не работает, то все остальное тоже не запускается, пишет сначало запустите инспектор. Телефон Galaxy s4  root.
Inspector does not work, do not press the start button, and if it does not work, everything else does not start, the inspector writes first run. Phone Galaxy s4 root

**Comment by dexofan23** [comment]
Same problem
Android 4.2.2 Huawei honor 2
Logcat http://pastebin.com/LTiGSPrC

**Comment by dexofan23** [comment]
the problem is solved by replacing kinguser on supersu. Kinguser seems also not supported.

**Comment by gainan** [comment]
Which version are you using?

**Comment by Zema7th** [comment]
latest version, she herself is updated, supersu I have installed, it does not matter, you are not in the software just press the "start" after the last update, it simply is not active, it's box inspector.

**Comment by mcilya** [comment]
@Zema7th if it's easier for you can you describe problem on russian language.

**Comment by Zema7th** [comment]
В последнем обновлении, не нажимается кнопка инспектор, а точнее не реагирует на нажатие на плай, может вы не прикрутили команду к кнопке, а без нее не удается запустить поиск эксплойтов, такое ощущение, что это не кнопка, а просто картинка

**Comment by fat-tire** [comment]
I believe a fix to this (which only happened for a few people for some reason) was checked in two nights ago, so hopefully when the nightly builds are working, the fix will be included.

**Comment by mcilya** [comment]
@Zema7th Скорее всего рельально забыли привязать действие к кнопке, можешь воспользоваться ночной сборкой там инспектор работает
http://rootbitch.cc/csploit/cSploit-nightly.apk

**Comment by Zema7th** [comment]
Да, эта сборка работает, спасибо
