### ISSUE TITLE
Cannot initialize any interface if ipv6 available

### ISSUE THREAD

**Issue by mcilya** [cSploit/android#448]
Samsung galaxy Note 2 (4.4.2) and Tab 10.1 (4.0.4)
Csploit 1.7.0-unstable+c8434eb
catlog with ipv6 - http://pastebin.com/48StBjZ5
catlog without ipv6 - http://pastebin.com/hZXemSwr

**Comment by tux-mind** [comment]
should be fixed in d026fd70ab69fd80e145ae55eb019a6de95d59c3 .
please check it out.

thanks for the report :blush:

**Comment by Tajnymag** [comment]
It also happens to me, but I don't use ipv6. [Here](http://pastebin.com/k79WntPB) is my log with device info included.

**Comment by mcilya** [comment]
Works fine at least for me now (1.7.0-unstable+be70dcf)

**Comment by gainan** [comment]
fixed. see #454
