### ISSUE TITLE
Bug with encoding in MITM

### ISSUE THREAD

**Issue by 0MazaHacka0** [cSploit/android#451]
I am from Russia, and most of our site have utf-8 encoding. While i use MITM on vulnerable machine all character replace with ?. Also, 30% of page is unvisible ans ome site don't load to end.

**Comment by gainan** [comment]
Many people have reported similar problems but with the cookies. @mcilya mentioned it yesterday  on the irc. By the way, do you refer in particular to the MITM/session hijacker browser?

Thank you for the report @0MazaHacka0 , I/we'll take a look at it.

**Comment by gainan** [comment]
Ok, problem reproduced and probably fixed. The problem is when intercepting connections, we alter the encoding of the output document. I'll post a workaround soon.

**Comment by gainan** [comment]
just as reference, @ddych reported this problem back in January... #50.

**Comment by gainan** [comment]
@0MazaHacka0, @ddych and @mcilya, test today's nightly and let us know if it's fixed.

**Comment by ddych** [comment]
It works correcrly, thanks.

**Comment by 0MazaHacka0** [comment]
Thanks for your great work, guys.
