### ISSUE TITLE
The Inspector won't start

### ISSUE THREAD

**Issue by themydroit** [cSploit/android#455]
When trying to run the inspector service, nothing happens. The blue round play button doesn't have any affect on what's happening. (Tested on two devices (Acer Iconia B1-711 & Doogee Turbo Mini F1)).

Kind regards.

**Comment by gainan** [comment]
Thank you for the report @themydroit. Which version of csploit are you using?
I´ve just tested it on the [nightly](http://rootbitch.cc/csploit/cSploit-nightly.apk) and it works fine.

**Comment by gainan** [comment]
@themydroit , please, try out the nightly (20/10/2015) and let us know if it is solved.

**Comment by sorano** [comment]
Tested on nightly and it works fine.
