### ISSUE TITLE
Error while installing ruby

### ISSUE THREAD

**Issue by 0MazaHacka0** [cSploit/android#458]
When i try to install ruby i see Error while installing ruby. I see in logcat, and there aren't any error. Just child #6 exit with exitcode=255

**Comment by Megaeloelo** [comment]
Same here .

**Comment by 0MazaHacka0** [comment]
@tux-mind need to attach csploit debug?

**Comment by sorano** [comment]
I just compiled develop branch and did not have any problems with installing ruby.
You did not write which version you are using, but I would guess that this is already solved.

Please try nightly and see if this issue persist, then re-open with logs attached.
