### ISSUE TITLE
Service inspector button broke

### ISSUE THREAD

**Issue by Senkaaaa** [cSploit/android#459]
Service inspector does not press on anything

Samsung galaxy s 5  4.4.2

Csploit 1.6.2

**Comment by sorano** [comment]
You need to attach logs in order for us to help.

This is also duplicate of #452

**Comment by gainan** [comment]
Hey @Senkaaaa , it should be fixed on the [latest nightly](http://rootbitch.cc/csploit/cSploit-nightly.apk). Try it out again and let us know if it works.
