### ISSUE TITLE
Tethering support

### ISSUE THREAD

**Issue by ghost251101** [cSploit/android#462]
I suggest to add an option for use cSploit with tethering, like zTether in zAnti (I get an error while I try to start cSploit with tethering turned on).

**Comment by gainan** [comment]
Hi @ghost251101 , which is error is that? could you explain it and post logs?

The unique problem I've seen is that the MITM modules don't work, because we clean the iptables rules when executing them, so when the victims try to access internet they can't.

**Comment by ghost251101** [comment]
I'm reinstalling cSploit. If I get this error again, I post logs.

**Comment by ghost251101** [comment]
I reinstalled cSploit and now I don't get any error, but it's really good idea to add option for using cSploit in a tethered network.

**Comment by gainan** [comment]
@ghost251101, feel free to open a new issue explaining in detail (and posting logs) why cSploit doesn't work on tethered networks (with latest nightly please!).
