### ISSUE TITLE
Inspector doesn't work

### ISSUE THREAD

**Issue by ghost251101** [cSploit/android#464]
I can't run Inspector on any network. When I tap the blue button, there isn't any reaction.
![screenshot_2015-10-23-18-15-50](https://cloud.githubusercontent.com/assets/15250303/10698962/da61a942-79b3-11e5-85d1-44ba3fbfc9b2.png)

**Comment by mcilya** [comment]
Try nightly build
http://rootbitch.cc/csploit/cSploit-nightly.apk

**Comment by PTZema** [comment]
the nightly dont work the network discovery...

**Comment by gainan** [comment]
@PTZema , there's an issue for that problem ... could you post details and logs there please? #454 
@ghost251101 , could you confirm if this problem is fixed on latest nightly?

**Comment by PTZema** [comment]
http://pastebin.com/0JCys7Et
There is it...

**Comment by PTZema** [comment]
But with 3g enabled the last nightly show my cellphone and net work mask, I think that if the network discovery is fixed they can list hosts in a local hotspot

**Comment by ghost251101** [comment]
@gainan Yes, this problem is fixed on nightly, thanks

**Comment by gainan** [comment]
great @ghost251101 , thank you for the feedback :)
