### ISSUE TITLE
Gems error

### ISSUE THREAD

**Issue by Megaeloelo** [cSploit/android#465]
Model : Blackview Zeta
Csploit version : 1.7.0-unstable+18a6395
Logcat : http://pastebin.com/N67fDhGj
Problem : When the application starts to downloading gems then I see " An error occurred while updating. "

**Comment by gainan** [comment]
@Megaeloelo , could you reproduce it and post a full logcat from the app start up? There're no references to cSploit on the logcat you posted.

**Comment by Megaeloelo** [comment]
I just did a hard reset and now it's working .
