### ISSUE TITLE
Cannot run Inspector

### ISSUE THREAD

**Issue by MuradTroll** [cSploit/android#468]
Hello pentesters, 

I encountered a bug. I waited a while until my phone said "connected to metaspkoit rpcd". Then I tried to run the Inspector, but I cannot click the Play-button. It just wont work it makes no pop, its just unpressable. But the other play buttons (for instance the one in portscanner) work fine...

**Comment by fat-tire** [comment]
Are you using the latest nightly?

**Comment by MuradTroll** [comment]
@fat-tire nah, im using 1.6.2 because i dont know if nightlys are stable. Gonne try to use them now.

**Comment by Megaeloelo** [comment]
This is a bug on latest release . BTW , nightly don't work for me .

**Comment by MuradTroll** [comment]
Nightly seem to work, atleast i can now click the button...

**Comment by Megaeloelo** [comment]
Can you download ruby gems without error?

**Comment by gainan** [comment]
we'll merge the fix for the stable release soon.
