### ISSUE TITLE
MSF RPC not connected

### ISSUE THREAD

**Issue by hahanov** [cSploit/android#47]
Hi @tux-mind,
I can not use metasploit writes: MSF RPC not connected
Using version cSploit nightly builds: http://rootbitch.cc/csploit/cSploit-nightly.apk
Video: http://ovrload.ru/f/43641_scr_20150117_155834.mp4
Log cSploit: http://pastebin.com/67w9L6D9
Tried on different devices ...
I hope for your help ...

**Comment by hahanov** [comment]
And more ...
does not allow creation of executable contents (pref_err_executable)
What is this error for some reason I cant locate where MSF

**Comment by Systemad** [comment]
Try to wait in "network mode" (when you see all devices connected to network) until you get ruby and msf update

**Comment by hahanov** [comment]
What should I give it? I already did that ... you about the first or second post?

**Comment by tux-mind** [comment]
Please post also the logcat. The msfrpcd seems start successfully.

**Comment by hahanov** [comment]
Hi!
Right now upload log

**Comment by hahanov** [comment]
tux-mind
Here LogCat: https://ghostbin.com/paste/53sg7

**Comment by hahanov** [comment]
You can not download http://rootbitch.cc/csploit/cSploit-nightly.apk

**Comment by tux-mind** [comment]
@hahanov your rom seems quite buggy. 

I've just made some changes that fixes some bugs that i saw in your logcat.

for the nightly build probably the build fail. I'll investigate this afternoon.

from the logcat i can see a native bug, I have to get home for debug it.

I'll keep you posted.

**Comment by hahanov** [comment]
@tux-mind,
Thank you very much!
Tested the new version (nightly builds) MSF RPC does not work
When you run an application error occurs Heart Attack...

**Comment by tux-mind** [comment]
@xiatax sorry for bother you , I should gain access to the `cSploit/obj/local/armeabi/` folder of the build server ( or get it's content ) to debug native issues.

@hahanov I'll made a debug version of cSploit for you with my workstation, thus to debug the native bug.

**Comment by hahanov** [comment]
Thank you so much!
Thank you very much, how can I download the debug version?

**Comment by tux-mind** [comment]
@hahanov i edited your comment, avoid to publish email addresses of other persons online.
spammer are everywhere :scream: 

you can download the debug version once #48 has been fixed.

**Comment by tux-mind** [comment]
@hahanov can you test cSploit 1.3.0 and report back a logcat ?

I have everything I need to debug the native issue if you use cSploit 1.3.0.

thanks in advance for your time :blush:

**Comment by sorano** [comment]
This should be resolved in 1.5.4.
Closing.

**Comment by asheroto** [comment]
I'm getting this error now too
