### ISSUE TITLE
Error while installing ruby

### ISSUE THREAD

**Issue by 0MazaHacka0** [cSploit/android#470]
Android 4.1.2. Csploit 1.7.0 nightly.  Error while installing Ruby. Log here. 
 http://pastebin.com/LHSYQ5sb

**Comment by Megaeloelo** [comment]
Same here .

**Comment by gainan** [comment]
the error:
>I/CSPLOIT[services.UpdateService.haveLocalFile](30040): file already exists: '/storage/sdcard0/ruby.tar.xz' 10-27 23:34:59.517 
I/CSPLOIT[services.UpdateService.extract](30040): extracting '/storage/sdcard0/ruby.tar.xz' to '/data/data/org.csploit.android/files/ruby' 10-27 23:34:59.517 
D/cSploitClient(30040): parse_cmd: parsing "which env" 10-27 23:34:59.517 
D/cSploitClient(30040): parse_cmd: argument found: start=0, end=5 10-27 23:34:59.517 
D/cSploitClient(30040): parse_cmd: argument found: start=6, end=9 10-27 23:34:59.517 
D/zhangxianjia ,phone statusbar(594): org.csploit.android 10-27 23:34:59.517 
W/cSploitClient(30040): start_command: cannot start command 10-27 23:34:59.517 
**D/CSPLOIT[core.ChildManager.async](30040): { handler='raw', cmd='which env' } => FAILED 10-27 23:34:59.527**
D/cSploitClient(30040): parse_cmd: parsing "rm -rf '/data/data/org.csploit.android/files/ruby'" 10-27 23:34:59.527 
D/cSploitClient(30040): parse_cmd: argument found: start=0, end=2 10-27 23:34:59.527 
D/cSploitClient(30040): parse_cmd: argument found: start=3, end=6 10-27 23:34:59.527 
D/cSploitClient(30040): parse_cmd: argument found: start=8, end=49 10-27 23:34:59.547 
I/cSploitClient(30040): start_command: child #7 started 10-27 23:34:59.547 
D/CSPLOIT[core.ChildManager.onEvent](30040): received an event: StderrNewline: { line='rm failed for -rf, No such file or directory' } 10-27 23:34:59.547 
D/CSPLOIT[core.ChildManager.async](30040): { handler='raw', cmd='rm -rf '/data/data/org.csploit.android/files/ruby'' } => 7 10-27 23:34:59.547 
D/CSPLOIT[core.ChildManager.onEvent](30040): received an event: ChildEnd: { exit_status=255 } 10-27 23:34:59.547 
D/CSPLOIT[core.ChildManager.dispatchEvent](30040): Child #7 exited ( exitValue=255 ) 10-27 23:34:59.567 
D/CSPLOIT[services.UpdateService.finishNotification](30040): deleting notifications 10-27 23:34:59.577
D/zhangxianjia ,phone statusbar(594): org.csploit.android

**Comment by gainan** [comment]
guys, check if you can reproduce it with latest nightly, and if */system/xbin/env* exists on your devices.

**Comment by 0MazaHacka0** [comment]
Have old busybody.  Now it's OK.
