### ISSUE TITLE
Inspector button not working

### ISSUE THREAD

**Issue by phlame64** [cSploit/android#471]
Touching the button to start inspector scan on a specific host does not work.

**Comment by gainan** [comment]
hi @phlame64 , which version are you using? try the latest [nightly](http://rootbitch.cc/csploit/cSploit-nightly.apk), it should be fixed on that version.

**Comment by phlame64** [comment]
Currently using v1.6.2. Will try the nightly and let you know if the issue is still there.

**Comment by PixelPips** [comment]
Inspector only seems to work for me when I turn `focused scan` off.

**Comment by gainan** [comment]
thank you guys, we'll merge soon this fix on the stable release :)
