### ISSUE TITLE
Not requesting root privileges. 

### ISSUE THREAD

**Issue by MilkoIvanov** [cSploit/android#472]
I have king root on Alcatel phone, and I saw that the application is not requesting root rights, so its almost in no use.

**Comment by Megaeloelo** [comment]
Change kingroot to supersu , http://www.w0lfdroid.com/2015/05/How-to-Remove-Replace-KingUser-KingRoot-with-SuperSU.html?m=1 .

**Comment by gainan** [comment]
as suggested by @Megaeloelo , use supersu.
