### ISSUE TITLE
don't initiate interface

### ISSUE THREAD

**Issue by PTZema** [cSploit/android#474]
I have cm 12.1, this happened in lasts nightly's.
If need catalog lately I will post...

**Comment by gainan** [comment]
@PTZema, probably it's related to this issue #454 . Post logs to check it anyway.

**Comment by gainan** [comment]
fixed on https://github.com/cSploit/android/commit/1815524845ced4bff8349855f8fb48acf9236293 and duplicated. post any feedback or problems to #454 please.
