### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by MusicaFM** [cSploit/android#475]
I have the latest version v1.7.0, but it happens with all versions, download and extract but did not install correctly CORE.TAR.XZ not properly scan devices, and can not activate processes, or scan the ports or anything, is problem should be "Core.tar.xz" I think it is not compatible with 
Hisense U961 
Android 4.4.2 Kitkat 
Rooted with: Kingroot 
Solution please :)

**Comment by Rubenoo** [comment]
Use supersu instead of kingroot

**Comment by gainan** [comment]
as suggested by Rubenoo, use supersu.

**Comment by MusicaFM** [comment]
I can not use SuperSU, is not compatible with my phone, I can only use Kingroot
