### ISSUE TITLE
Hi de nuevo

### ISSUE THREAD

**Issue by MusicaFM** [cSploit/android#477]
I have the latest version v1.7.0, but it happens with all versions, download and extract but did not install correctly CORE.TAR.XZ not properly scan devices, and can not activate processes, or scan the ports or anything, is problem should be "Core.tar.xz" I think it is not compatible with 
Hisense U961 
Android 4.4.2 Kitkat 
Rooted with: Kingroot 
I can not use SuperSU, is not compatible with my phone, I can only use Kingroot
Solution please :)

**Comment by sorano** [comment]
Well, the obvious solution would be to use a device that supports supersu.

**Comment by MusicaFM** [comment]
Vale de cuerdo, muchas Gracias :+1:

**Comment by gainan** [comment]
There are a lot of tutorials on internet about how to change kingroot with supersu. 

Hay bastantes tutoriales en internet sobre cómo cambiar kingroot por supersu, échales un vistazo:
http://fandroide.net/como-reemplazar-kinguser-por-supersu-en-android/
