### ISSUE TITLE
Wifi hacking tool

### ISSUE THREAD

**Issue by ericthedreamer** [cSploit/android#483]
I know this is worked on but, maybe its fun to het something like wifite in the app ( on kali linux you have it integrated )

**Comment by Tajnymag** [comment]
Actually we can't do that, because we would need to put WiFi chip to monitor mode which would need a modified kernel. So until the developers find a way how to bypass this, no wifite being integrated.

**Comment by fat-tire** [comment]
Not only a modified kernel, but documented support for the wifi chip itself, which is different on every device (and not supported on many devices).  I've mentioned before that Nethunter provides support for USB Network Adapters that do support monitor mode.  This too requires a modified kernel, but if you're interested, it's supported on a few devices with more coming and you can find it [here](https://www.kali.org/kali-linux-nethunter/) or for more cutting-edge stuff, the source for the new in-progress version is [here](https://github.com/offensive-security/nethunter-app/tree/master-2.1).

**Comment by Tajnymag** [comment]
Would it be possible to use xposed framework for this?

**Comment by IwraStudios** [comment]
Xposed causes trouble for csploit so even if it did the app itself probably wouldn't work
