### ISSUE TITLE
Crash on external MSFRPCD

### ISSUE THREAD

**Issue by Ottavio97** [cSploit/android#49]
Hi @tux-mind,
As I Had issue with MSF, I tried to move msf outside my phone. I installed it with all rubygems on my Ubuntu VPS and I run it with the same command as cSploit (fetched in catlog). So I Moved into cSploit settings and changed RPC Host but right after it , it crash. I tried also to put a random ip and it crash in the same way, so it seems cSploit doesn't allow external addresses but only 127.0.0.1 . If you will solve it, I will love you forever :))

**Comment by tux-mind** [comment]
Hi @Ottavio97 .

please post the logcat. so i can see where is the bug and kill it :wink:

**Comment by tux-mind** [comment]
Hi @Ottavio97 I tested this on my device with no success, no crash.

I need your logcat.

**Comment by sorano** [comment]
User have not returned with any feedback, closing this issue.
