### ISSUE TITLE
MITM not working 

### ISSUE THREAD

**Issue by evertking** [cSploit/android#490]
I'm using the latest nightly and doesn't seem to work on my OPO slimsaber 5.1.1

**Comment by gainan** [comment]
@evertking , what is not working? the MITM functionality has 10 modules .. post logs, and describe the problem in detail please.

**Comment by evertking** [comment]
.0.1 (port 443) after 60000ms: isConnected failed: ECONNREFUSED (Connection refused)
11-06 11:48:14.237 D/CSPLOIT[core.System.setForwarding](3795): Setting ipv4 forwarding to false
11-06 11:48:14.237 D/cSploitClient(3795): parse_cmd: parsing "sh -c 'echo 0 > /proc/sys/net/ipv4/ip_forward'"
11-06 11:48:14.237 D/cSploitClient(3795): parse_cmd: argument found: start=0, end=2
11-06 11:48:14.237 D/cSploitClient(3795): parse_cmd: argument found: start=3, end=5
11-06 11:48:14.238 D/cSploitClient(3795): parse_cmd: argument found: start=7, end=45
11-06 11:48:14.243 I/cSploitClient(3795): start_command: child #48 started
11-06 11:48:14.244 D/CSPLOIT[core.ChildManager.async](3795): { handler='raw', cmd='sh -c 'echo 0 > /proc/sys/net/ipv4/ip_forward'' } => 48
11-06 11:48:14.245 D/audio_hw_primary(260): out_set_parameters: enter: usecase(1: low-latency-playback) kvpairs: routing=2
11-06 11:48:14.253 D/CSPLOIT[core.ChildManager.onEvent](3795): received an event: ChildEnd: { exit_status=0 }
11-06 11:48:14.254 D/CSPLOIT[core.ChildManager.dispatchEvent](3795): Child #48 exited ( exitValue=0 )
11-06 11:48:14.255 D/CSPLOIT[tools.IPTables.undoPortRedirect](3795): Undoing port redirection
11-06 11:48:14.255 D/cSploitClient(3795): parse_cmd: parsing "iptables -t nat -F"
11-06 11:48:14.255 D/cSploitClient(3795): parse_cmd: argument found: start=0, end=8
11-06 11:48:14.255 D/cSploitClient(3795): parse_cmd: argument found: start=9, end=11
11-06 11:48:14.255 D/cSploitClient(3795): parse_cmd: argument found: start=12, end=15
11-06 11:48:14.255 D/cSploitClient(3795): parse_cmd: argument found: start=16, end=18
11-06 11:48:14.258 I/cSploitClient(3795): start_command: child #49 started
11-06 11:48:14.258 D/CSPLOIT[core.ChildManager.async](3795): { handler='raw', cmd='iptables -t nat -F' } => 49
11-06 11:48:14.266 D/CSPLOIT[core.ChildManager.onEvent](3795): received an event: ChildEnd: { exit_status=0 }
11-06 11:48:14.266 D/CSPLOIT[core.ChildManager.dispatchEvent](3795): Child #49 exited ( exitValue=0 )
11-06 11:48:14.266 D/cSploitClient(3795): parse_cmd: parsing "iptables -F"
11-06 11:48:14.255 I/iptables(6005): type=1400 audit(0.0:399): avc: denied { create } for scontext=u:r:init:s0 tcontext=u:r:init:s0 tclass=rawip_socket permissive=1
11-06 11:48:14.255 W/iptables(6005): type=1300 audit(0.0:399): arch=40000028 syscall=281 per=800000 success=yes exit=5 a0=2 a1=3 a2=ff a3=b6f7d234 items=0 ppid=3968 auid=4294967295 uid=0 gid=0 euid=0 suid=0 fsuid=0 egid=0 sgid=0 fsgid=0 tty=(none) ses=4294967295 exe="/system/bin/iptables" subj=u:r:init:s0 key=(null)
11-06 11:48:14.255 W/auditd  (367): type=1320 audit(0.0:399): 
11-06 11:48:14.255 I/iptables(6005): type=1400 audit(0.0:400): avc: denied { getopt } for lport=255 scontext=u:r:init:s0 tcontext=u:r:init:s0 tclass=rawip_socket permissive=1
11-06 11:48:14.255 W/iptables(6005): type=1300 audit(0.0:400): arch=40000028 syscall=295 per=800000 success=yes exit=0 a0=5 a1=0 a2=40 a3=be9c1758 items=0 ppid=3968 auid=4294967295 uid=0 gid=0 euid=0 suid=0 fsuid=0 egid=0 sgid=0 fsgid=0 tty=(none) ses=4294967295 exe="/system/bin/iptables" subj=u:r:init:s0 key=(null)
11-06 11:48:14.266 D/cSploitClient(3795): parse_cmd: argument found: start=0, end=8
11-06 11:48:14.266 D/cSploitClient(3795): parse_cmd: argument found: start=9, end=11
11-06 11:48:14.271 I/cSploitClient(3795): start_command: child #50 started
11-06 11:48:14.272 D/CSPLOIT[core.ChildManager.async](3795): { handler='raw', cmd='iptables -F' } => 50
11-06 11:48:14.289 D/CSPLOIT[core.ChildManager.onEvent](3795): received an event: ChildEnd: { exit_status=0 }
11-06 11:48:14.290 D/CSPLOIT[core.ChildManager.dispatchEvent](3795): Child #50 exited ( exitValue=0 )
11-06 11:48:14.290 D/cSploitClient(3795): parse_cmd: parsing "iptables -t nat -D POSTROUTING -s 0/0 -j MASQUERADE"
11-06 11:48:14.290 D/cSploitClient(3795): parse_cmd: argument found: start=0, end=8
11-06 11:48:14.290 D/cSploitClient(3795): parse_cmd: argument found: start=9, end=11
11-06 11:48:14.290 D/cSploitClient(3795): parse_cmd: argument found: start=12, end=15
11-06 11:48:14.290 D/cSploitClient(3795): parse_cmd: argument found: start=16, end=18
11-06 11:48:14.290 D/cSploitClient(3795): parse_cmd: argument found: start=19, end=30
11-06 11:48:14.290 D/cSploitClient(3795): parse_cmd: argument found: start=31, end=33
11-06 11:48:14.290 D/cSploitClient(3795): parse_cmd: argument found: start=34, end=37
11-06 11:48:14.290 D/cSploitClient(3795): parse_cmd: argument found: start=38, end=40
11-06 11:48:14.290 D/cSploitClient(3795): parse_cmd: argument found: start=41, end=51
11-06 11:48:14.293 I/cSploitClient(3795): start_command: child #51 started
11-06 11:48:14.293 D/CSPLOIT[core.ChildManager.async](3795): { handler='raw', cmd='iptables -t nat -D POSTROUTING -s 0/0 -j MASQUERADE' } => 51
11-06 11:48:14.298 D/CSPLOIT[core.ChildManager.onEvent](3795): received an event: StderrNewline: { line='iptables: No chain/target/match by that name.'  }
11-06 11:48:14.300 D/CSPLOIT[core.ChildManager.onEvent](3795): received an event: ChildEnd: { exit_status=1 }
11-06 11:48:14.300 D/CSPLOIT[core.ChildManager.dispatchEvent](3795): Child #51 exited ( exitValue=1 )
11-06 11:48:14.301 D/cSploitClient(3795): parse_cmd: parsing "iptables -t nat -D PREROUTING -j DNAT -p tcp --dport 80 --to 192.168.254.3:8080"
11-06 11:48:14.301 D/cSploitClient(3795): parse_cmd: argument found: start=0, end=8
11-06 11:48:14.301 D/cSploitClient(3795): parse_cmd: argument found: start=9, end=11
11-06 11:48:14.301 D/cSploitClient(3795): parse_cmd: argument found: start=12, end=15
11-06 11:48:14.301 D/cSploitClient(3795): parse_cmd: argument found: start=16, end=18
11-06 11:48:14.301 D/cSploitClient(3795): parse_cmd: argument found: start=19, end=29
11-06 11:48:14.301 D/cSploitClient(3795): parse_cmd: argument found: start=30, end=32
11-06 11:48:14.301 D/cSploitClient(3795): parse_cmd: argument found: start=33, end=37
11-06 11:48:14.301 D/cSploitClient(3795): parse_cmd: argument found: start=38, end=40
11-06 11:48:14.301 D/cSploitClient(3795): parse_cmd: argument found: start=41, end=44
11-06 11:48:14.301 D/cSploitClient(3795): parse_cmd: argument found: start=45, end=52
11-06 11:48:14.301 D/cSploitClient(3795): parse_cmd: argument found: start=53, end=55
11-06 11:48:14.301 D/cSploitClient(3795): parse_cmd: argument found: start=56, end=60
11-06 11:48:14.301 D/cSploitClient(3795): parse_cmd: argument found: start=61, end=79
11-06 11:48:14.304 I/cSploitClient(3795): start_command: child #52 started
11-06 11:48:14.305 D/CSPLOIT[core.ChildManager.async](3795): { handler='raw', cmd='iptables -t nat -D PREROUTING -j DNAT -p tcp --dport 80 --to 192.168.254.3:8080' } => 52
11-06 11:48:14.325 D/CSPLOIT[core.ChildManager.onEvent](3795): received an event: StderrNewline: { line='iptables: No chain/target/match by that name.'  }
11-06 11:48:14.329 D/CSPLOIT[core.ChildManager.onEvent](3795): received an event: ChildEnd: { exit_status=1 }
11-06 11:48:14.329 D/CSPLOIT[core.ChildManager.dispatchEvent](3795): Child #52 exited ( exitValue=1 )
11-06 11:48:14.330 D/CSPLOIT[tools.IPTables.undoPortRedirect](3795): Undoing port redirection
11-06 11:48:14.330 D/cSploitClient(3795): parse_cmd: parsing "iptables -t nat -F"
11-06 11:48:14.330 D/cSploitClient(3795): parse_cmd: argument found: start=0, end=8
11-06 11:48:14.330 D/cSploitClient(3795): parse_cmd: argument found: start=9, end=11
11-06 11:48:14.330 D/cSploitClient(3795): parse_cmd: argument found: start=12, end=15
11-06 11:48:14.330 D/cSploitClient(3795): parse_cmd: argument found: start=16, end=18
11-06 11:48:14.332 I/cSploitClient(3795): start_command: child #53 started
11-06 11:48:14.333 D/CSPLOIT[core.ChildManager.async](3795): { handler='raw', cmd='iptables -t nat -F' } => 53
11-06 11:48:14.336 D/CSPLOIT[core.ChildManager.onEvent](3795): received an event: ChildEnd: { exit_status=0 }
11-06 11:48:14.336 D/CSPLOIT[core.ChildManager.dispatchEvent](3795): Child #53 exited ( exitValue=0 )
11-06 11:48:14.337 D/cSploitClient(3795): parse_cmd: parsing "iptables -F"
11-06 11:48:14.337 D/cSploitClient(3795): parse_cmd: argument found: start=0, end=8
11-06 11:48:14.337 D/cSploitClient(3795): parse_cmd: argument found: start=9, end=11
11-06 11:48:14.338 I/cSploitClient(3795): start_command: child #54 started
11-06 11:48:14.339 D/CSPLOIT[core.ChildManager.async](3795): { handler='raw', cmd='iptables -F' } => 54
11-06 11:48:14.344 D/CSPLOIT[core.ChildManager.onEvent](3795): received an event: ChildEnd: { exit_status=0 }
11-06 11:48:14.345 D/CSPLOIT[core.ChildManager.dispatchEvent](3795): Child #54 exited ( exitValue=0 )
11-06 11:48:14.345 D/cSploitClient(3795): parse_cmd: parsing "iptables -t nat -D POSTROUTING -s 0/0 -j MASQUERADE"
11-06 11:48:14.345 D/cSploitClient(3795): parse_cmd: argument found: start=0, end=8
11-06 11:48:14.345 D/cSploitClient(3795): parse_cmd: argument found: start=9, end=11
11-06 11:48:14.345 D/cSploitClient(3795): parse_cmd: argument found: start=12, end=15
11-06 11:48:14.345 D/cSploitClient(3795): parse_cmd: argument found: start=16, end=18
11-06 11:48:14.345 D/cSploitClient(3795): parse_cmd: argument found: start=19, end=30
11-06 11:48:14.345 D/cSploitClient(3795): parse_cmd: argument found: start=31, end=33
11-06 11:48:14.345 D/cSploitClient(3795): parse_cmd: argument found: start=34, end=37
11-06 11:48:14.345 D/cSploitClient(3795): parse_cmd: argument found: start=38, end=40
11-06 11:48:14.345 D/cSploitClient(3795): parse_cmd: argument found: start=41, end=51
11-06 11:48:14.349 I/cSploitClient(3795): start_command: child #55 started
11-06 11:48:14.350 D/CSPLOIT[core.ChildManager.async](3795): { handler='raw', cmd='iptables -t nat -D POSTROUTING -s 0/0 -j MASQUERADE' } => 55
11-06 11:48:14.353 D/CSPLOIT[core.ChildManager.onEvent](3795): received an event: StderrNewline: { line='iptables: No chain/target/match by that name.'  }
11-06 11:48:14.354 D/CSPLOIT[core.ChildManager.onEvent](3795): received an event: ChildEnd: { exit_status=1 }
11-06 11:48:14.354 D/CSPLOIT[core.ChildManager.dispatchEvent](3795): Child #55 exited ( exitValue=1 )
11-06 11:48:14.354 D/cSploitClient(3795): parse_cmd: parsing "iptables -t nat -D PREROUTING -j DNAT -p tcp --dport 443 --to 192.168.254.3:8082"
11-06 11:48:14.354 D/cSploitClient(3795): parse_cmd: argument found: start=0, end=8
11-06 11:48:14.354 D/cSploitClient(3795): parse_cmd: argument found: start=9, end=11
11-06 11:48:14.354 D/cSploitClient(3795): parse_cmd: argument found: start=12, end=15
11-06 11:48:14.354 D/cSploitClient(3795): parse_cmd: argument found: start=16, end=18
11-06 11:48:14.354 D/cSploitClient(3795): parse_cmd: argument found: start=19, end=29
11-06 11:48:14.354 D/cSploitClient(3795): parse_cmd: argument found: start=30, end=32
11-06 11:48:14.354 D/cSploitClient(3795): parse_cmd: argument found: start=33, end=37
11-06 11:48:14.354 D/cSploitClient(3795): parse_cmd: argument found: start=38, end=40
11-06 11:48:14.354 D/cSploitClient(3795): parse_cmd: argument found: start=41, end=44
11-06 11:48:14.354 D/cSploitClient(3795): parse_cmd: argument found: start=45, end=52
11-06 11:48:14.354 D/cSploitClient(3795): parse_cmd: argument found: start=53, end=56
11-06 11:48:14.354 D/cSploitClient(3795): parse_cmd: argument found: start=57, end=61
11-06 11:48:14.354 D/cSploitClient(3795): parse_cmd: argument found: start=62, end=80
11-06 11:48:14.356 I/cSploitClient(3795): start_command: child #56 started
11-06 11:48:14.356 D/CSPLOIT[core.ChildManager.async](3795): { handler='raw', cmd='iptables -t nat -D PREROUTING -j DNAT -p tcp --dport 443 --to 192.168.254.3:8082' } => 56
11-06 11:48:14.366 D/CSPLOIT[core.ChildManager.onEvent](3795): received an event: StderrNewline: { line='iptables: No chain/target/match by that name.'  }
11-06 11:48:14.367 D/CSPLOIT[core.ChildManager.onEvent](3795): received an event: ChildEnd: { exit_status=1 }
11-06 11:48:14.368 D/CSPLOIT[core.ChildManager.dispatchEvent](3795): Child #56 exited ( exitValue=1 )
11-06 11:48:14.368 D/CSPLOIT[net.http.proxy.HTTPSRedirector.stop](3795): Stopping HTTPS redirector ...
11-06 11:48:14.368 D/HTTP.PROXY(3795): Stopping proxy ...
11-06 11:48:14.369 D/HTTP.PROXY(3795): Proxy stopped.
11-06 11:48:14.371 D/CSPLOIT[net.http.proxy.HTTPSRedirector.run](3795): HTTPS redirector stopped.
11-06 11:48:16.240 D/WifiService(865): acquireWifiLockLocked: WifiLock{Firepaper type=1 binder=android.os.BinderProxy@fe4762}
11-06 11:48:16.295 D/WifiService(865): releaseWifiLockLocked: WifiLock{Firepaper type=1 binder=android.os.BinderProxy@fe4762}
11-06 11:48:17.346 D/audio_hw_primary(260): out_standby: enter: stream (0xb5880600) usecase(1: low-latency-playback)
11-06 11:48:17.427 D/hardware_info(260): hw_info_append_hw_type : device_name = speaker
11-06 11:48:17.584 D/audio_hw_primary(260): out_set_parameters: enter: usecase(1: low-latency-playback) kvpairs: routing=2
11-06 11:48:17.595 D/audio_hw_primary(260): start_output_stream: enter: stream(0xb5880600)usecase(1: low-latency-playback) devices(0x2)
11-06 11:48:17.595 D/audio_hw_primary(260): start_output_stream: enter: usecase(1: low-latency-playback) devices(0x2)
11-06 11:48:17.595 D/audio_hw_primary(260): select_devices: out_snd_device(2: speaker) in_snd_device(0: )
11-06 11:48:17.595 W/msm8974_platform(260): Codec backend bitwidth 16, samplerate 48000
11-06 11:48:17.595 D/hardware_info(260): hw_info_append_hw_type : device_name = speaker
11-06 11:48:17.595 I/msm8974_platform(260): platform_send_audio_calibration: sending audio calibration for snd_device(2) acdb_id(15)
11-06 11:48:17.595 D/ACDB-LOADER(260): ACDB -> send_audio_cal, acdb_id = 15, path =  0
11-06 11:48:17.595 D/ACDB-LOADER(260): ACDB -> send_adm_topology
11-06 11:48:17.595 D/ACDB-LOADER(260): ACDB -> ACDB_CMD_GET_AUDPROC_COMMON_TOPOLOGY_ID
11-06 11:48:17.596 D/ACDB-LOADER(260): ACDB -> send_asm_topology
11-06 11:48:17.596 D/ACDB-LOADER(260): ACDB -> ACDB_CMD_GET_AUDPROC_STREAM_TOPOLOGY_ID
11-06 11:48:17.596 D/ACDB-LOADER(260): ACDB -> send_audtable
11-06 11:48:17.596 D/ACDB-LOADER(260): ACDB -> ACDB_CMD_GET_AUDPROC_COMMON_TABLE
11-06 11:48:17.596 D/ACDB-LOADER(260): ACDB -> AUDIO_SET_AUDPROC_CAL
11-06 11:48:17.596 D/ACDB-LOADER(260): ACDB -> send_audvoltable
11-06 11:48:17.596 D/ACDB-LOADER(260): ACDB -> ACDB_CMD_GET_AUDPROC_GAIN_DEP_STEP_TABLE
11-06 11:48:17.596 D/        (260): Failed to fetch the lookup information of the device 0000000F 
11-06 11:48:17.596 E/ACDB-LOADER(260): Error: ACDB AudProc vol returned = -19
11-06 11:48:17.596 D/ACDB-LOADER(260): ACDB -> AUDIO_SET_AUDPROC_VOL_CAL
11-06 11:48:17.596 D/ACDB-LOADER(260): ACDB -> send_afe_cal
11-06 11:48:17.596 D/ACDB-LOADER(260): ACDB -> ACDB_CMD_GET_AFE_COMMON_TABLE
11-06 11:48:17.596 D/        (260): Failed to fetch the lookup information of the device 0000000F 
11-06 11:48:17.596 E/ACDB-LOADER(260): Error: ACDB AFE returned = -19
11-06 11:48:17.596 D/ACDB-LOADER(260): ACDB -> AUDIO_SET_AFE_CAL
11-06 11:48:17.601 D/audio_hw_primary(260): select_devices: done
11-06 11:48:17.605 D/CSPLOIT[core.System.setForwarding](3795): Setting ipv4 forwarding to false
11-06 11:48:17.605 D/cSploitClient(3795): parse_cmd: parsing "sh -c 'echo 0 > /proc/sys/net/ipv4/ip_forward'"
11-06 11:48:17.605 D/cSploitClient(3795): parse_cmd: argument found: start=0, end=2
11-06 11:48:17.605 D/cSploitClient(3795): parse_cmd: argument found: start=3, end=5
11-06 11:48:17.605 D/cSploitClient(3795): parse_cmd: argument found: start=7, end=45
11-06 11:48:17.614 I/cSploitClient(3795): start_command: child #57 started
11-06 11:48:17.615 D/CSPLOIT[core.ChildManager.async](3795): { handler='raw', cmd='sh -c 'echo 0 > /proc/sys/net/ipv4/ip_forward'' } => 57
11-06 11:48:17.624 D/CSPLOIT[core.ChildManager.onEvent](3795): received an event: ChildEnd: { exit_status=0 }
11-06 11:48:17.624 D/CSPLOIT[core.ChildManager.dispatchEvent](3795): Child #57 exited ( exitValue=0 )
11-06 11:48:17.624 D/CSPLOIT[tools.IPTables.undoPortRedirect](3795): Undoing port redirection
11-06 11:48:17.624 D/cSploitClient(3795): parse_cmd: parsing "iptables -t nat -F"
11-06 11:48:17.624 D/cSploitClient(3795): parse_cmd: argument found: start=0, end=8
11-06 11:48:17.624 D/cSploitClient(3795): parse_cmd: argument found: start=9, end=11
11-06 11:48:17.625 W/auditd  (367): type=1325 audit(0.0:405): table=nat family=2 entries=9
11-06 11:48:17.625 W/iptables(6025): type=1300 audit(0.0:405): arch=40000028 syscall=294 per=800000 success=yes exit=0 a0=5 a1=0 a2=40 a3=b643ba00 items=0 ppid=3968 auid=4294967295 uid=0 gid=0 euid=0 suid=0 fsuid=0 egid=0 sgid=0 fsgid=0 tty=(none) ses=4294967295 exe="/system/bin/iptables" subj=u:r:init:s0 key=(null)
11-06 11:48:17.625 W/auditd  (367): type=1320 audit(0.0:405): 
11-06 11:48:17.635 W/auditd  (367): type=1325 audit(0.0:406): table=filter family=2 entries=32
11-06 11:48:17.635 W/iptables(6027): type=1300 audit(0.0:406): arch=40000028 syscall=294 per=800000 success=yes exit=0 a0=5 a1=0 a2=40 a3=b644a000 items=0 ppid=3968 auid=4294967295 uid=0 gid=0 euid=0 suid=0 fsuid=0 egid=0 sgid=0 fsgid=0 tty=(none) ses=4294967295 exe="/system/bin/iptables" subj=u:r:init:s0 key=(null)
11-06 11:48:17.624 D/cSploitClient(3795): parse_cmd: argument found: start=16, end=18
11-06 11:48:17.627 I/cSploitClient(3795): start_command: child #58 started
11-06 11:48:17.628 D/CSPLOIT[core.ChildManager.async](3795): { handler='raw', cmd='iptables -t nat -F' } => 58
11-06 11:48:17.635 D/CSPLOIT[core.ChildManager.onEvent](3795): received an event: ChildEnd: { exit_status=0 }
11-06 11:48:17.635 D/CSPLOIT[core.ChildManager.dispatchEvent](3795): Child #58 exited ( exitValue=0 )
11-06 11:48:17.636 D/cSploitClient(3795): parse_cmd: parsing "iptables -F"
11-06 11:48:17.636 D/cSploitClient(3795): parse_cmd: argument found: start=0, end=8
11-06 11:48:17.636 D/cSploitClient(3795): parse_cmd: argument found: start=9, end=11
11-06 11:48:17.640 I/cSploitClient(3795): start_command: child #59 started
11-06 11:48:17.641 D/CSPLOIT[core.ChildManager.async](3795): { handler='raw', cmd='iptables -F' } => 59
11-06 11:48:17.643 D/CSPLOIT[core.ChildManager.onEvent](3795): received an event: ChildEnd: { exit_status=0 }
11-06 11:48:17.643 D/CSPLOIT[core.ChildManager.dispatchEvent](3795): Child #59 exited ( exitValue=0 )
11-06 11:48:17.644 D/cSploitClient(3795): parse_cmd: parsing "iptables -t nat -D POSTROUTING -s 0/0 -j MASQUERADE"
11-06 11:48:17.644 D/cSploitClient(3795): parse_cmd: argument found: start=0, end=8
11-06 11:48:17.644 D/cSploitClient(3795): parse_cmd: argument found: start=9, end=11
11-06 11:48:17.644 D/cSploitClient(3795): parse_cmd: argument found: start=12, end=15
11-06 11:48:17.644 D/cSploitClient(3795): parse_cmd: argument found: start=16, end=18
11-06 11:48:17.644 D/cSploitClient(3795): parse_cmd: argument found: start=19, end=30
11-06 11:48:17.644 D/cSploitClient(3795): parse_cmd: argument found: start=31, end=33
11-06 11:48:17.644 D/cSploitClient(3795): parse_cmd: argument found: start=34, end=37
11-06 11:48:17.644 D/cSploitClient(3795): parse_cmd: argument found: start=38, end=40
11-06 11:48:17.644 D/cSploitClient(3795): parse_cmd: argument found: start=41, end=51
11-06 11:48:17.651 I/cSploitClient(3795): start_command: child #60 started
11-06 11:48:17.652 D/CSPLOIT[core.ChildManager.async](3795): { handler='raw', cmd='iptables -t nat -D POSTROUTING -s 0/0 -j MASQUERADE' } => 60
11-06 11:48:17.658 D/CSPLOIT[core.ChildManager.onEvent](3795): received an event: StderrNewline: { line='iptables: No chain/target/match by that name.'  }
11-06 11:48:17.659 D/CSPLOIT[core.ChildManager.onEvent](3795): received an event: ChildEnd: { exit_status=1 }
11-06 11:48:17.660 D/CSPLOIT[core.ChildManager.dispatchEvent](3795): Child #60 exited ( exitValue=1 )
11-06 11:48:17.661 D/cSploitClient(3795): parse_cmd: parsing "iptables -t nat -D PREROUTING -j DNAT -p tcp --dport 80 --to 192.168.254.3:8080"
11-06 11:48:17.661 D/cSploitClient(3795): parse_cmd: argument found: start=0, end=8
11-06 11:48:17.661 D/cSploitClient(3795): parse_cmd: argument found: start=9, end=11
11-06 11:48:17.661 D/cSploitClient(3795): parse_cmd: argument found: start=12, end=15
11-06 11:48:17.661 D/cSploitClient(3795): parse_cmd: argument found: start=16, end=18
11-06 11:48:17.661 D/cSploitClient(3795): parse_cmd: argument found: start=19, end=29
11-06 11:48:17.661 D/cSploitClient(3795): parse_cmd: argument found: start=30, end=32
11-06 11:48:17.661 D/cSploitClient(3795): parse_cmd: argument found: start=33, end=37
11-06 11:48:17.661 D/cSploitClient(3795): parse_cmd: argument found: start=38, end=40
11-06 11:48:17.661 D/cSploitClient(3795): parse_cmd: argument found: start=41, end=44
11-06 11:48:17.661 D/cSploitClient(3795): parse_cmd: argument found: start=45, end=52
11-06 11:48:17.661 D/cSploitClient(3795): parse_cmd: argument found: start=53, end=55
11-06 11:48:17.661 D/cSploitClient(3795): parse_cmd: argument found: start=56, end=60
11-06 11:48:17.661 D/cSploitClient(3795): parse_cmd: argument found: start=61, end=79
11-06 11:48:17.664 I/cSploitClient(3795): start_command: child #61 started
11-06 11:48:17.664 D/CSPLOIT[core.ChildManager.async](3795): { handler='raw', cmd='iptables -t nat -D PREROUTING -j DNAT -p tcp --dport 80 --to 192.168.254.3:8080' } => 61
11-06 11:48:17.669 D/CSPLOIT[core.ChildManager.onEvent](3795): received an event: StderrNewline: { line='iptables: No chain/target/match by that name.'  }
11-06 11:48:17.669 D/CSPLOIT[core.ChildManager.onEvent](3795): received an event: ChildEnd: { exit_status=1 }
11-06 11:48:17.670 D/CSPLOIT[core.ChildManager.dispatchEvent](3795): Child #61 exited ( exitValue=1 )
11-06 11:48:17.671 D/CSPLOIT[tools.IPTables.undoPortRedirect](3795): Undoing port redirection
11-06 11:48:17.671 D/cSploitClient(3795): parse_cmd: parsing "iptables -t nat -F"
11-06 11:48:17.671 D/cSploitClient(3795): parse_cmd: argument found: start=0, end=8
11-06 11:48:17.671 D/cSploitClient(3795): parse_cmd: argument found: start=9, end=11
11-06 11:48:17.671 D/cSploitClient(3795): parse_cmd: argument found: start=12, end=15
11-06 11:48:17.671 D/cSploitClient(3795): parse_cmd: argument found: start=16, end=18
11-06 11:48:17.674 I/cSploitClient(3795): start_command: child #62 started
11-06 11:48:17.674 D/CSPLOIT[core.ChildManager.async](3795): { handler='raw', cmd='iptables -t nat -F' } => 62
11-06 11:48:17.692 D/CSPLOIT[core.ChildManager.onEvent](3795): received an event: ChildEnd: { exit_status=0 }
11-06 11:48:17.693 D/CSPLOIT[core.ChildManager.dispatchEvent](3795): Child #62 exited ( exitValue=0 )
11-06 11:48:17.693 D/cSploitClient(3795): parse_cmd: parsing "iptables -F"
11-06 11:48:17.693 D/cSploitClient(3795): parse_cmd: argument found: start=0, end=8
11-06 11:48:17.693 D/cSploitClient(3795): parse_cmd: argument found: start=9, end=11
11-06 11:48:17.696 I/cSploitClient(3795): start_command: child #63 started
11-06 11:48:17.697 D/CSPLOIT[core.ChildManager.async](3795): { handler='raw', cmd='iptables -F' } => 63
11-06 11:48:17.702 D/CSPLOIT[core.ChildManager.onEvent](3795): received an event: ChildEnd: { exit_status=0 }
11-06 11:48:17.704 D/CSPLOIT[core.ChildManager.dispatchEvent](3795): Child #63 exited ( exitValue=0 )
11-06 11:48:17.704 D/cSploitClient(3795): parse_cmd: parsing "iptables -t nat -D POSTROUTING -s 0/0 -j MASQUERADE"
11-06 11:48:17.705 D/cSploitClient(3795): parse_cmd: argument found: start=0, end=8
11-06 11:48:17.705 D/cSploitClient(3795): parse_cmd: argument found: start=9, end=11
11-06 11:48:17.705 D/cSploitClient(3795): parse_cmd: argument found: start=12, end=15
11-06 11:48:17.705 D/cSploitClient(3795): parse_cmd: argument found: start=16, end=18
11-06 11:48:17.705 D/cSploitClient(3795): parse_cmd: argument found: start=19, end=30
11-06 11:48:17.705 D/cSploitClient(3795): parse_cmd: argument found: start=31, end=33
11-06 11:48:17.705 D/cSploitClient(3795): parse_cmd: argument found: start=34, end=37
11-06 11:48:17.705 D/cSploitClient(3795): parse_cmd: argument found: start=38, end=40
11-06 11:48:17.705 D/cSploitClient(3795): parse_cmd: argument found: start=41, end=51
11-06 11:48:17.707 I/cSploitClient(3795): start_command: child #64 started
11-06 11:48:17.707 D/CSPLOIT[core.ChildManager.async](3795): { handler='raw', cmd='iptables -t nat -D POSTROUTING -s 0/0 -j MASQUERADE' } => 64
11-06 11:48:17.711 D/CSPLOIT[core.ChildManager.onEvent](3795): received an event: StderrNewline: { line='iptables: No chain/target/match by that name.'  }
11-06 11:48:17.711 D/CSPLOIT[core.ChildManager.onEvent](3795): received an event: ChildEnd: { exit_status=1 }
11-06 11:48:17.712 D/CSPLOIT[core.ChildManager.dispatchEvent](3795): Child #64 exited ( exitValue=1 )
11-06 11:48:17.713 D/cSploitClient(3795): parse_cmd: parsing "iptables -t nat -D PREROUTING -j DNAT -p tcp --dport 443 --to 192.168.254.3:8082"
11-06 11:48:17.713 D/cSploitClient(3795): parse_cmd: argument found: start=0, end=8
11-06 11:48:17.713 D/cSploitClient(3795): parse_cmd: argument found: start=9, end=11
11-06 11:48:17.713 D/cSploitClient(3795): parse_cmd: argument found: start=12, end=15
11-06 11:48:17.713 D/cSploitClient(3795): parse_cmd: argument found: start=16, end=18
11-06 11:48:17.713 D/cSploitClient(3795): parse_cmd: argument found: start=19, end=29
11-06 11:48:17.713 D/cSploitClient(3795): parse_cmd: argument found: start=30, end=32
11-06 11:48:17.713 D/cSploitClient(3795): parse_cmd: argument found: start=33, end=37
11-06 11:48:17.713 D/cSploitClient(3795): parse_cmd: argument found: start=38, end=40
11-06 11:48:17.713 D/cSploitClient(3795): parse_cmd: argument found: start=41, end=44
11-06 11:48:17.713 D/cSploitClient(3795): parse_cmd: argument found: start=45, end=52
11-06 11:48:17.713 D/cSploitClient(3795): parse_cmd: argument found: start=53, end=56
11-06 11:48:17.713 D/cSploitClient(3795): parse_cmd: argument found: start=57, end=61
11-06 11:48:17.713 D/cSploitClient(3795): parse_cmd: argument found: start=62, end=80
11-06 11:48:17.721 I/cSploitClient(3795): start_command: child #65 started
11-06 11:48:17.722 D/CSPLOIT[core.ChildManager.async](3795): { handler='raw', cmd='iptables -t nat -D PREROUTING -j DNAT -p tcp --dport 443 --to 192.168.254.3:8082' } => 65
11-06 11:48:17.735 D/CSPLOIT[core.ChildManager.onEvent](3795): received an event: StderrNewline: { line='iptables: No chain/target/match by that name.'  }
11-06 11:48:17.737 D/CSPLOIT[core.ChildManager.onEvent](3795): received an event: ChildEnd: { exit_status=1 }
11-06 11:48:17.738 D/CSPLOIT[core.ChildManager.dispatchEvent](3795): Child #65 exited ( exitValue=1 )
11-06 11:48:17.738 D/CSPLOIT[net.http.proxy.HTTPSRedirector.stop](3795): Stopping HTTPS redirector ...
11-06 11:48:17.739 D/HTTP.PROXY(3795): Stopping proxy ...
11-06 11:48:17.784 I/Timeline(3795): Timeline: Activity_idle id: android.os.BinderProxy@1fddff5c time:1733626
11-06 11:48:17.827 I/Timeline(865): Timeline: Activity_windows_visible id: ActivityRecord{bb2adbf u0 org.csploit.android/.plugins.mitm.MITM t431} time:1733669

**Comment by gainan** [comment]
same problem than #480 I think. @evertking , dou you have a default gateway on your device? paste the output of -> ip r|grep default

**Comment by evertking** [comment]
Tmp-mksh can't create IP: read only file system.

**Comment by gainan** [comment]
did you execute it as root? also, the output of *cat /proc/net/route* will be useful. Or just simply check if on the hosts list you have the gateway entry (the one with the label "Your network gateway/router").

**Comment by evertking** [comment]
Yes, I have a gateway listed. 
Yes, I ran that command as root. Why am I getting that output?
I switched to the latest stable release and all is well again. Thanks for your help.

**Comment by evertking** [comment]
OK, I see a gateway with the stable release but no on the nightly.

**Comment by gainan** [comment]
ok, thank you very much for the info @evertking ! . It's the same problem reported on #480.
