### ISSUE TITLE
Suggestion: Evil AP // Evil Twin // Rogue AP

### ISSUE THREAD

**Issue by Trig0n** [cSploit/android#494]
Basically a similar thing to zAnti, where you can create a Hotspot and sniff traffic, inject js, etc.
Just with the option to choose a Network and basically clone it (Just set the SSID for tethering).
As the Access Point I'd like to still have the option to scan all connected hosts, which is as far as I know, not possible in zAnti. 
I'd love to see that in further versions.

**Comment by gainan** [comment]
Hi @Trig0n , correct me if I'm wrong, can't you achieve the same by enabling the hotspot on the mobile, choosing the ESSID of an existing network, and selecting the wifi interface from cSploit? Then you should only have to use cSploit as usual. We've added this option recently on the nightly.
btw, is this the same suggestion than #436?

**Comment by Trig0n** [comment]
Hey gainan,
as far as i know,.. I can't even use my WiFi, if I create an AP for other actions. Upto now I used two devices for this kinda stuff. Phone as AP and Tablet for scanning.

DNS Spoofing with loadable HTML templates and a sqlite db for saving credentials would be great in combination with the evil twin.

Yes. Basically the same suggestion, I did not see that one. I did not check out the nightly yet. Thanks for the recommendation.

**Comment by Trig0n** [comment]
I've just tested the nightly out. 
Did not think it would be that easy, but it works great. I love it.
Good job!

**Comment by PTZema** [comment]
Network interfaces option appears in grey and I cannot select ...

**Comment by Trig0n** [comment]
You need to create a Hotspot via your System Settings first, then you can select the "Net Interfaces" option and select "wlan0".
