### ISSUE TITLE
freezing in Settings

### ISSUE THREAD

**Issue by danktx** [cSploit/android#5]
hey tux,

thanks that you forked dsploit.

I got some problems.
 -freezing when opening settings and more
and
 -metasploit install failed

Part1
http://pastebin.com/EYshJmff

Part2
http://pastebin.com/diKeAWPz

Moto G
cm11 nigthly

**Comment by sorano** [comment]
Closing this almost one year old issue.
If this still is a problem I think the hardware acceleration workaround should be put in a wiki or FAQ.
