### ISSUE TITLE
1.6.2 Core Problem

### ISSUE THREAD

**Issue by devimauz** [cSploit/android#500]
Core is not installed the application will just check for updates. no updates available.
Moto X 2014 / 5.1

I seen it maybe Kingroot problem? I'll change to superSU

**Comment by gainan** [comment]
hi @devimauz , the error related with kingroot/supersu is that the app can only run on rooted devices.
If the core has not been installed on your device, post logs to see what's going on.
https://github.com/cSploit/android/wiki/How-to-open-an-issue

**Comment by devimauz** [comment]
Thank You it was rooted but with Kingroot! After I installed CM and works great!

**Comment by gainan** [comment]
great @devimauz !
