### ISSUE TITLE
Feature request: ip lookup

### ISSUE THREAD

**Issue by ghost** [cSploit/android#504]
When using traceroute it'd be nice have the abillity to tap the address and see extended information. In fact it'd be nice to see a little country flag next to the adresses without even tapping it aswell. 
The details should be simmilar to http://whatismyipaddress.com/ip-lookup

P.s AMAZING app!! Have been waiting for something like this.

**Comment by fat-tire** [comment]
I'll just leave this [here](http://stackoverflow.com/questions/4453328/get-location-of-wifi-ip-in-android)  One thing about this feature is security-- you're using a third party service to do your geolocation, meaning you'd be passing the IP out of your network, giving it to someone, then getting a response.. that's a lot of traffic you might want to avoid (or not have if you're on a firewalled LAN)...

That said, it's a super-cool idea... so what do you all think as far as involving/depending on third parties and such..?

**Comment by blackwat3r** [comment]
@fat-tire, doesn't using traceroute/dig/other similar utilities already contact third party hosts to obtain the data you see output anyways
