### ISSUE TITLE
Unable to download MSF - Nexus 5

### ISSUE THREAD

**Issue by PixelPips** [cSploit/android#511]
Having some issues. MSF downloads, but once it's finished "extracting", it just tells me there was an error downloading.

Info:

Phone Type: Nexus 5
OS: Marshmallow 6.0 (rooted)
Kernel version: 3.4.0-g0acc96d
Rom: Chroma (can't find version number)
cSploit Version: v1.6.2
MSF Branch: csploit
Logcat (grep -i "csploit"): http://pips.rocks/sGpW

Anyone know what's going on? It'd be nice to test MSF out on a Metasploitable device.

**Comment by evertking** [comment]
I also am having the same issue. Oneplus one running android 6.0 unable to install MSF/ gems.

**Comment by PixelPips** [comment]
@evertking I recommend posting the required info for creating an issue [(here)](https://github.com/cSploit/android/wiki/How-to-open-an-issue)

**Comment by fat-tire** [comment]
This issue appears to be identical to #503 -- please re-open if I'm wrong about this.
