### ISSUE TITLE
Inspector

### ISSUE THREAD

**Issue by CrashByte23** [cSploit/android#512]
Hi to all, I have a Huawei mate 7, I find the inspector are not working or searching. 
Thanks.

**Comment by Rubenoo** [comment]
Hey @CrashByte23. Thank you for pointing out this bug. But before we can fix it we need more information. I suggest you read this page carefully :https://github.com/cSploit/android/wiki/How-to-open-an-issue
Because we stil need logcat and more information

Thank you
