### ISSUE TITLE
Router keygen

### ISSUE THREAD

**Issue by poutros** [cSploit/android#517]
Perhaps you could integrate router keygen (http://routerkeygen.github.io) into csploit?

**Comment by fat-tire** [comment]
I haven't yet really looked at this, but is there a workflow or other reason to integrate the code into csploit as opposed to having both app side-by-side?  They are both active GPL projects, so what are you thinking might be the advantage of doing this?  (I could see a potential downside might be keeping the source up to date...)

**Comment by poutros** [comment]
Router keygen does one of the things you want csploit to do (more or less), which is to find network passwords so it could be useful to integrate it into csploit.
