### ISSUE TITLE
Use USB WiFi dongles via OTG

### ISSUE THREAD

**Issue by Interneedus** [cSploit/android#52]
Basically my phone has (now) USB OTG capabilities and I have a USB WiFi dongle that allows listening. I have modified my phone's kernel to include the driver and the dongle should work. Is there a way you could provide a GUI for the tools? (Running a debian image with the tools shouldn't be impossible)

**Comment by tux-mind** [comment]
Hi @Interneedus , thanks for the suggestion.

look at the first point of [cSploit target](http://www.csploit.org/).

I've already scheduled this feature, but without using the aircrack suite.

it will require a lot of work but capturing WPA handshakes ( or cracking WEP ) is a too-cool feature that I'm looking forward to implement!

sadly I have to fix a lot of bugs and lead the MSF to a stable state before working on new features.

but I will certainly do it :wink:

**Comment by Interneedus** [comment]
@tux-mind That would also add WPS pin cracking and much more. This is a toolkit that would add so much features to cSploit. Also, I'd suggest you'd advertise this project on reddit and other places to get more contributors and users.

**Comment by Avamander** [comment]
@tux-mind There's no need to reinvent the wheel. It wouldn't be hard to run a debian image (loop device) and the tools on it. Providing a terminal + optional gui would be really nice.

**Comment by tux-mind** [comment]
@Avamander I think you're wrong.
Yes, it require a lot of work but aircrack and other tools aren't user friendly like an android application.

The target of cSploit is to made the super-standard hacking jobs easy and portable on your hand.

Furthermore parsing other tools output is problematic.
BTW I will take some time to analyze the aircrack approach when I'll implement this feature.

As always thanks for your suggestions :smiley:

**Comment by Avamander** [comment]
@tux-mind 
But displaying Aircrack suite output directly, but creating shortcuts to execute commands faster. It is much more work creating properly working "aircrack" suite than giving the user a terminal with working Ubuntu(it's easier than others .-.) build.

**Comment by Avamander** [comment]
PS
I get it that it is not that user friendly, but it has much more features than (unfortunately) you could never implement because it takes too much effort. I would really appreciate if you'd atleast build a terminal into your app.

**Comment by MuradTroll** [comment]
Yes a terminal would be really cool. That you can activate it under "advanced settings" or so. A terminal could help debugging and using features that arent 
In csploit.

**Comment by sorano** [comment]
If we stick to the original issue, external interfaces will be supported when #245 gets merged.
