### ISSUE TITLE
Problème de fonctionnement

### ISSUE THREAD

**Issue by val777** [cSploit/android#521]
Ce message apparaît et l'application ne fonctionne pas :"heart attack occured, the application will juste check for udapte . aucune mise à jour disponible."
Comment résoudre ce problème ?
Merci d'avance

**Comment by fabinhojcr** [comment]
Please use the English language

**Comment by val777** [comment]
ok, sorry :/

This message appears and the application does not work:"heart attack occured, the application will juste check for udapte . aucune mise à jour disponible."

how to solve this problem?
thanks

**Comment by fat-tire** [comment]
Do you have a logcat?  Which device/version of android are you using?  What version of the app?  Have you tried the latest nightly?

[Please read this](https://github.com/cSploit/android/wiki/How-to-open-an-issue) and then re-open the issue with the requested information.

Thank you!

**Comment by val777** [comment]
No, i don't have this
I use Android 4.4.2 wich a 3.4.67 core
The version of the app is 1.6.2
Yes but the message appears
