### ISSUE TITLE
Inspector+Vulnerability finder 

### ISSUE THREAD

**Issue by pahapoika** [cSploit/android#525]
I have Samsung galaxy s4 mini (gt19195) Kitkat 4.4.2
Latest "stable" version of cspoit.
No custom ROM. 
When i go to inspector and press that play button nothing happens. Inspector works on dspoit.  And other think is that the vulnerability finder doesn't show on menu. Everything else is working.

**Comment by fat-tire** [comment]
Hey-- offtopic question about "this site can be hacked" you added/removed to the wiki.  What was the point of that?

Anyway, try the latest nightly and see if your problem is fixed.

**Comment by pahapoika** [comment]
Theres my logcat when i open cSpoit and go to inspector and try to run it. https://mega.nz/#!gswG0Bpa!TWm_f4yEXC753YWM2ligQ0j5TMfXH37Th-4QP2oD1HE

**Comment by pahapoika** [comment]
Fat-tire point of that was that github is vulnerability for cross site scripting attack. But github fixed it.

**Comment by pahapoika** [comment]
Thanks fat-tire (what a wonderful name) . Nightly worked.

**Comment by tux-mind** [comment]
just a foot note about this issue: the vulnerability finder has been deleted long time ago.
