### ISSUE TITLE
Metaspoilt meterpreter 

### ISSUE THREAD

**Issue by pahapoika** [cSploit/android#535]
There could be meterpreter in your metasploit. Meterpreter allows you to control the screen on victim using VNC.

**Comment by tux-mind** [comment]
not only VNC @pahapoika , clear windows event logs, install backdoors, take snapshots of the screen.... it's an awesome program!

as now I'm working on redesigning the app, adding some new cool features like a msfconsole UI :wink: 

taking advantage of all the features of the MSF it's already planned and we are still working on it ( see msf_restyling branch ).

closing, feel free to reopen if you need more info :wink: 

OT:

I saw that you are pretty active in this project @pahapoika , would you like to join the team ?
Even a guy that answer to the issues will be helpful :blush:

**Comment by pahapoika** [comment]
@tux-mind cool. Of course i can be. I think it would be awesome to be a part of your project.

**Comment by tux-mind** [comment]
great :smile: 

I sent you an invitation for the android-dev team.

Even just closing invalid issues and finding duplicate ones it's a very helpful task for us!

If you find an invalid or not-clear issue redirect them to [this page](https://github.com/cSploit/android/wiki/How-to-open-an-issue).

feel free to contact me if you have any doubt about managing issues.

thank you for helping us making cSploit better :wink:
