### ISSUE TITLE
inspector button fail

### ISSUE THREAD

**Issue by biderchurch** [cSploit/android#536]
hi ! thank you for your work guys csploit is an amazing app but since the last update I have th blue button issue. I've already found some git topic on it but no solution for me.. on the other menu like Trace or Port scanning everything is ok :(
I've tried to open the apk to modify the plugin_inspector.xml but no succes for me. 
So can you help me with this issue (if I have to post some log tell me, but I don t think it will help..) or will you fix it in the next update of csploit ? (in that case when will it be released ?)
bye !

**Comment by biderchurch** [comment]
sorry I forgot to tell I use an galaxy s4 mini on android 4.3.1 !

**Comment by pahapoika** [comment]
Try nightly version. http://www.csploit.org/downloads.html

**Comment by tux-mind** [comment]
duplicate of #546 .

fixed in [v1.6.3](https://github.com/cSploit/android/releases/tag/v1.6.3).
