### ISSUE TITLE
http://rootbitch.cc/csploit/cSploit-nightly.apk not working 

### ISSUE THREAD

**Issue by pahapoika** [cSploit/android#538]
https://mega.nz/#!g4RDDB5K!MBs4iXPIhQHRbPXh5QDJj-5LxSiinGpj563yxYrJkvs

**Comment by pahapoika** [comment]
And does someone know when are the cSploit 2.0 coming? 25.12? 😊

**Comment by Systemad** [comment]
No ETA asking as this is a open source project

**Comment by xaitax** [comment]
Sorry, there is an issue in the nightly build-script that will delete files older than x and there wasn't a build a while ago so it will delete it. I will put in a pull-request and just build the nightly again manually. Which will be online again in 2 minutes.

**Comment by pahapoika** [comment]
Thank you
