### ISSUE TITLE
cSploit 2

### ISSUE THREAD

**Issue by pahapoika** [cSploit/android#542]
Does anyone know when the cSploit 2 is coming? It sounds amazing upgrade. http://www.csploit.org/preparing-csploit-2/
And does the cSploits msf start postgresql automatically?

**Comment by pahapoika** [comment]
@tux_mind can you tell me when the cSploit 2 is ready. And i can be betatester.

**Comment by pahapoika** [comment]
@tux-mind

**Comment by DeveloppSoft** [comment]
@pahapoika, this is an open source project, don't ask.
If you want to test use nightly releases.

**Comment by tux-mind** [comment]
@DeveloppSoft thank you for answering :blush: 

@pahapoika as @DeveloppSoft said this is an open source project, there is no ETA or release date.

actually I'm working on another repo of a collaborator, we are working on re-design the whole app.
there is much work left, I bet that we will not be ready in one month.

BTW, a **very** kindness guy ( the same that gave me the T60 ), is about to give me another notebook, more powerful, that will speed up my work when I'm not at home.

about your question on the MSF...actually there is no DB support, I recently rewrote the MSF client and I'll work on enabling DB support if we think that this will be useful for our purposes.

thank you for following the project :blush:
