### ISSUE TITLE
cleanmaster detects csploit as a virus

### ISSUE THREAD

**Issue by blackwat3r** [cSploit/android#543]
this isn't very much of a serious issue but I think it should be brought to the attention of the developers that cleanmaster by cheetah mobile is invalidly detecting csploit as a virus

ive attempted to contact them and have them fix this false positive with no answer, perhaps the devs can try to contact them and have them resolve this issue as their apps are more of a sham than csploit is

**Comment by tux-mind** [comment]
Just sent though their contact form.

> Hi.
> your program detect my app (cSploit) as a virus.
> 
> The purpose of the app is to find vulnerabilities on networks on which you are allowed to perform those tests.
> It is not a threat for the phone.
> 
> I hope to read from you soon, tux_mind.

thank you for pointing it out @blackwat3r :blush:
