### ISSUE TITLE
Inspector Bug

### ISSUE THREAD

**Issue by Omega36** [cSploit/android#544]
Hello,

I run cSploit (last update, msf, ruby,...installed) on my Moto G XT132 (w Android 4.4.4 stock, rooted, busybox ok. ) Everything works fine except the 'Inspector'. Indeed, i can't press the 'play' button to start the scan to get advanced information about devices on my network: pressing it doesn't start anything. 
I tried some basic things like uninstall reinstall, force stop some running apps.. It didn't work.
Any tips?

Thx for helping,

M. C.

**Comment by pahapoika** [comment]
Try nightly build http://rootbitch.cc/csploit/cSploit-nightly.apk

**Comment by blackwat3r** [comment]
perhaps the readme should be updated to tell users to search issues before making duplicate issues because im currently seeing numerous users with this same issue posted whom seem to noy know how to use the search before submitting duplicate content

**Comment by tux-mind** [comment]
@blackwat3r that is a good suggestion, a search for opened issue function. but as now it's the last of our problem :laughing: 

feel free to open another issue with that suggestion, so we can label it with a low priority and work on it as we can.

we are making big changes to the app to move into a new design with new features.
stay tuned :wink:

**Comment by tux-mind** [comment]
duplicated of #546
