### ISSUE TITLE
v1.6.3 = wonderful Christmas present!  Thank You for all of the extra work!!!!

### ISSUE THREAD

**Issue by newbie442** [cSploit/android#549]

**Comment by pahapoika** [comment]
Say it to @tux-mind

**Comment by newbie442** [comment]
Indeed....... IIUC, He did a major rewrite. 

I'm guessing he worked extra hard to complete it by Christmas!

We users are very fortunate - and grateful!

THANK YOU, @tux-mind!!!

**Comment by tux-mind** [comment]
you're welcome @newbie442 :blush: 

I'm glad that you enjoy your present :laughing:
