### ISSUE TITLE
suggestions 

### ISSUE THREAD

**Issue by cyclex25** [cSploit/android#552]
this is less of an issue as more of a suggestion of the things i´d love to see included into csploit. the only things i could add to the already existing list would be 

• a dedicated rogue AP section (wifi)
• badusb function (badandroid)
• HID attack function utilizing ducky scripts 

looking forward to speak soon, cheers

**Comment by DPFH** [comment]
I'd love to have an interactive metasploit console (msfconsole)

**Comment by pahapoika** [comment]
Hey, @DPFH
csploit 2 will include msfconsole. 
http://www.csploit.org/preparing-csploit-2/

**Comment by pahapoika** [comment]
@cyclex25 
badusb function needs Selinux modification as well as HID. But those features are in Kali Nethunter. I suggest you to use it if you have Nexus-device or oneplus 1/2. And of course you can build your own image.

Im running Kali Nethunter in my Oneplus One as secondary ROM 

+Kali Nethunter includes cSploit as default. Your man +fat-tire are Nethunters developer.

https://github.com/offensive-security/kali-nethunter/wiki

https://www.kali.org/kali-linux-nethunter/

**Comment by DPFH** [comment]
@pahapoika , is there a release date (or period) ? Or will we have to wait?

**Comment by pahapoika** [comment]
@DPFH About month ago @tux-mind said that it will took over month. So we need to just wait.
