### ISSUE TITLE
INSTALL_FAILED_UPDATE_INCOMPATIBLE

### ISSUE THREAD

**Issue by maximilianKoeper** [cSploit/android#554]
Can not update to Version 1.6.3 RC0 neither to latest release.
CyanogenOS  12.1

**Comment by pahapoika** [comment]
https://github.com/cSploit/android/wiki/How-to-open-an-issue

**Comment by maximilianKoeper** [comment]
[alogcat.2015-12-27-17-07-39+0100.txt](https://github.com/cSploit/android/files/72729/alogcat.2015-12-27-17-07-39.0100.txt)


- Device: OnePlus One (64Gb)
- OS: CyanogenOS 12.1 (cm-12.1 YOG4PAS3JL)
    - rooted
- No Xposed Framework and Modules

Problem: I can not install or update to Version 1.6.3 RC0 (older Versions are working fine). After trying to install it over adb or emulated terminal it shows following Error: "Failed [INSTALL_FAILED_UPDATE_INCOMPATIBLE]".

**Comment by BitpopCoin** [comment]
The signing key has changed.

**Comment by tux-mind** [comment]
I just tried installing cSploit 1.6.1 and then update to 1.6.3, it went fine.

probably you installed cSploit from Android Studio.

@maximilianKoeper feel free to reopen the issue if the problem is different.
