### ISSUE TITLE
Metasploit RPCD Won't start.

### ISSUE THREAD

**Issue by ApolloGods** [cSploit/android#557]
Metasploit RPCD.. do not start.
In Vers. 1.62 it goes. Please fix. Thanks a lot, hope you had good Chrismas.

**Comment by ApolloGods** [comment]
Port 55553 forwarding is done

**Comment by ApolloGods** [comment]
Now is connection failed to MSF RPC deamon

**Comment by pahapoika** [comment]
https://github.com/cSploit/android/wiki/how-to-open-an-issue

**Comment by pahapoika** [comment]
Duplicate with https://github.com/cSploit/android/issues/553

**Comment by ApolloGods** [comment]
Happy new year! 

http://pastebin.ca/3311747

Here is my error log uploaded.
