### ISSUE TITLE
HEART ATTACK OCCURRED...THE APPLICATION WILL JUST CHECK FOR UPDATES

### ISSUE THREAD

**Issue by OrDoR** [cSploit/android#559]
Hi,

This is the problem, i can´t use the program. i open the apk (v 1.6.3) , download de Core (v 1.0.11) , unzip but a message in blanck screen: "Core is not installed, the application will just check for updates. No hay actualizaciones disponibles"

Model: Vodafone 890n
Rom: Original rom, itkat 4.4.4

With nightly the same error.

Tahnks in advace.
Rodrigo

**Comment by pahapoika** [comment]
Try to unistall and then install again. And if that doesnt help would you please take logcat. http://forum.xda-developers.com/showthread.php?t=1726238

**Comment by OrDoR** [comment]
Hi all,

I resolved the problem. It was caused by the root method (KingRoot). I uninstall KingRoot and install SuperSu and the app CSPLOIT works like a charm!!

Thanks a lot.
Rodrigo
