### ISSUE TITLE
Not updated 

### ISSUE THREAD

**Issue by jess1825** [cSploit/android#561]

**Comment by fabinhojcr** [comment]
Need more info

**Comment by pahapoika** [comment]
For your issue to be considered and solved ASAP please provide the following information

1.Your Device model

2. Your ROM name and version.

3.your cSploit version number.    

4. As many details as possible on the network you are running cSploit on.

5. Whether or not you are using Xposed or any Xposed modules. (By the way, if you are-- don't)

NOTE. Don't use Kingroot. Download SuperSU from Google Play store
