### ISSUE TITLE
WiFi scan deletes the key of the currently connected AP

### ISSUE THREAD

**Issue by Interneedus** [cSploit/android#57]
Pressing the WiFi scan button results in nothing and if the device is connected to a hotspot, the key is deleted. This is really annoying.

**Comment by Interneedus** [comment]
Device: LG D605
Software: CyanogenMod 11

**Comment by rigid** [comment]
i can confirm this. also cm11 here.

**Comment by tux-mind** [comment]
Yeah guys,
this bug is there from a lot of time.

but I have to rewrite the WiFi part as I start working on the USB OTG compatibility.

will give a look for a possible hotfix. thanks for the report.

**Comment by Avamander** [comment]
Can confirm. Hotfix would be really appreciated.

**Comment by Avamander** [comment]
Would it be possible to fix this? As I am unable to find the dictionary for Penetrate app any more, I would really appreciate if I could still check if the hotspot is using a password that can be reversed based by the SSID.

**Comment by tux-mind** [comment]
lemme fix it.
with some :heart:

**Comment by Avamander** [comment]
Whoa, thanks. I'll try it in as soon as cSploit suggests me to update.

**Comment by Rubenoo** [comment]
@Avamander It doesn't exactly work like that, you can better download the nightly version of csploit tomorrow from www.csploit.org :)

**Comment by Avamander** [comment]
@Rubenoo The patch will be in the next stable release so I could either wait for the update notification on my phone or download a nightly, both options are valid.
