### ISSUE TITLE
Kingroot

### ISSUE THREAD

**Issue by BEOWULF74** [cSploit/android#573]
(question) So if i have kingroot i cant install csploit ? tell me plz to stop trying to install the app 😅😅

**Comment by pahapoika** [comment]
Yes. You need SuperSU. Csploit wont work with kingroot.

**Comment by Megaeloelo** [comment]
But why?

**Comment by pahapoika** [comment]
I think that cSploit has coded to communicate with SuperSu binary.

**Comment by BEOWULF74** [comment]
Ok thx 😔

**Comment by DeveloppSoft** [comment]
@BEOWULF74, that there are some tutorials on the web to switch kingo to
supersu.
@papahoika, you're right, in order to get root we call the 'su' binary
which pop a root shell (like in 'normal' linux distros).

**Comment by BEOWULF74** [comment]
I tried but no luck because i cant mount system

**Comment by BEOWULF74** [comment]
Rw

**Comment by pahapoika** [comment]
@BEOWULF74 Delete Kingroot. Theres option to delete Kingroot in-app. So after you deleted it flash SuperSu in custom recovery like TWRP. I can give you link to SuperSu zip that you just flash.

**Comment by BEOWULF74** [comment]
Thanx bro but there's no custom recovery for my device huawei g play mini (chc-u01) and i tried to delete king root but alwais fail @pahapoika

**Comment by pahapoika** [comment]
@BEOWULF74 Theres link to SuperSu that you need to flash with recovery like TWRP. But first delete Kingroot.
https://mega.nz/#!3pthgCIT!uYbAL3uPKRdo-txamxR3varw0YQsYYcrKAzLDmak2Dc

**Comment by BEOWULF74** [comment]
I cant remove kingroot cuz the system partition become ro (read only) after i installd kingroot i tried to remount it rw but no luck now u know why kingroot fail at removing process and there's no custom recovery for my device 😞

**Comment by pahapoika** [comment]
Tell me about your phone.

**Comment by pahapoika** [comment]
@BEOWULF74 Model and ROM.

**Comment by pahapoika** [comment]
And theres guide for Kingroot deleting. http://androidmtk.com/remove-kinguser-application

**Comment by BEOWULF74** [comment]
Huawei g play mini (chc-u01)
Rom:4.4.2(emui)

**Comment by pahapoika** [comment]
@BEOWULF74 
1.Download TWRP manager from google play and flash it from app. 
2.Download SuperSu from my link above. 
3.Uninstall Kingroot. Watch the guide above.
4. Flash SuperSu.zip with TWRP Recovery.
5.Reboot. You should see SuperSu app on your phone. Download root checker and verify that you are rooted.

Thats how i deleted Kingroot and flashed SuperSu. In my old phone. Now im smarter and i dont touch Kingroot.

**Comment by Megaeloelo** [comment]
http://androidforums.com/threads/script-replace-kingoroot-with-supersu.919175/ - tutorial .
PS:His phone is not on the list of devices supported by the recovery .

**Comment by VasilisKos** [comment]
@pahapoika 
I didn't know it was that simple! I did it as you say and now I have a rooted Xperia Z1 Compact WITHOUT the Kingroot! Thanks a lot mate!
But, I wonder: how does the phone stay rooted after that procedure? Uninstalling kingroot is supposed to unroot the device, and SuperSU is not supposed to root devices? Right? So, how does that happen?

**Comment by Systemad** [comment]
@VasilisKos What do you mean? SuperSU is a root method (and tool).

**Comment by VasilisKos** [comment]
@Systemad 
So, I guess that flashing it through recovery also roots the device, right?
I didn't think so, because in the xda thread, 1st post, chainfire mentions:
"!!! SuperSU requires a rooted device !!!"

**Comment by Systemad** [comment]
@VasilisKos Flashig SuperSU zip will root the device, that's the basic (and most common) root method.
