### ISSUE TITLE
Hello guys

### ISSUE THREAD

**Issue by DemianWolf** [cSploit/android#580]
I really like the idea of cSploit but sadly it doesn't work on my device. I use Huawei G6 U10  with kernel 3.4.0+ and Android version 4.3, busy box version 1.24.1 by meefik and SuperSu. I tried installing both standard version and nightly, both install smoothly in both cases app, core, Ruby and msf install, msf initialize but when I wanna start service scan it say "cannot start process" and basically all processes say that. Thank you guys in front.

**Comment by fat-tire** [comment]
Please read the wiki on the best way to report an issue: 

https://github.com/cSploit/android/wiki/How-to-open-an-issue

Without a logcat, this kind of like describing a dream you had.  It sounds terrible, but there's not much anyone can do about it right now.

Please include a logcat showing the issue in action.  Thanks

**Comment by fat-tire** [comment]
No response for 18 days.  Closing.  Feel free to reopen w/a log...
