### ISSUE TITLE
CSploit CA Sertificate

### ISSUE THREAD

**Issue by elpaxdota** [cSploit/android#584]
There was the post (on official blog):
http://www.csploit.org/working-on-ssl/

Is it already implemented on 1.6.5 version ? Or its on nighty ? Or its not implemented yet ?

**Comment by evertking** [comment]
Hmmm.. Just downloaded the nightly. Let's test!!

**Comment by IwraStudios** [comment]
There is neither but plans for HSTS might be coming
https://github.com/cSploit/android/issues/680: HSTS bypass; sslstrip 2

**Comment by IwraStudios** [comment]
This issue will be merged into https://github.com/cSploit/android/issues/520
