### ISSUE TITLE
exam session

### ISSUE THREAD

**Issue by tux-mind** [cSploit/android#588]
isn't a real issue, just a little post with my apologize.

I went out for a while due to both work and study, btw I'll give the last exam of this session on 24/02.

I made an agreement with my current boss, so my salary it's higher and I can left over some extra work, having more time to spend on cSploit.

I have great ideas and I'll have the required time to make them real shortly, thank you for your patience guys :)

**Comment by xaitax** [comment]
Take your time mate! Finish your work and studies - we all know you are dedicated to this project and your this baby of yours! ;)

**Comment by Rubenoo** [comment]
Fully agree with @xaitax
Take your time friend

**Comment by elpaxdota** [comment]
come back quickly ) we all need csploit )

**Comment by maddog9696** [comment]
Take your time but do it quickly! ;) jk thanks for all your work @tux-mind

**Comment by tux-mind** [comment]
If I do them quickly I have to do them twice or more :joy: 

Probably an exam ( distributed systems ) has gone bad ( I want at least 25/30 ), I'm waiting the mark.
I have another chance on 26/02, this will make you wait a couple of days more.

I'll keep you posted :wink: 

Thank you for you support guys, especially to @xaitax , the hoster of our nightly build system :heart:

**Comment by tux-mind** [comment]
exam session terminated, will resume ASAP.
with love :heart:
