### ISSUE TITLE
How to build

### ISSUE THREAD

**Issue by Silur** [cSploit/android#594]
Your documentation is incomplete, you have several repos for 1 project, the android repo cannot build due to missing native libs, the source tarball cannot build due to missing tools directory this sucks, please make one, working repo like normal people on github don't give us little chunks that need to be put together like an IKEA product, or provide a documentation for that.... like IKEA does.

**Comment by xaitax** [comment]
Well, it's pretty straightforward and retrieves all modules on building. I don't have any special setup on my server for that.

**Comment by Silur** [comment]
ERRNO libCsploitCore.so => `java.lang.UnsatisfiedLinkError: Couldn't load cSploitCommon from loader dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/org.csploit.android-2.apk"],nativeLibraryDirectories=[/data/app-lib/org.csploit.android-2, /vendor/lib, /system/lib]]]: findLibrary returned null` => crash
I want to contribute to the code so nightly wont do if I want to recieve updates.

**Comment by Silur** [comment]
same as #431 but you closed the issues saying it is "presumibly" fixed, I just cloned git, encountered #593, fixed it and then encountered this

**Comment by Silur** [comment]
I had to decompress the release apk and adb push the .so files to the app-lib directory but I still don't know why do I have to do this to make an android repo work :confused:

**Comment by fat-tire** [comment]
>  you have several repos for 1 project

...as do many, many projects, including Android itself.  Seriously.  The concept of a single project that uses multiple memos blows your mind?

![boom](https://i.imgur.com/DWrI2JY.gif)

> normal people on github don't give us little chunks that need to be put together like an IKEA product, or provide a documentation for that.... like IKEA does.

Are you really holding up IKEA as a [model](https://twitter.com/NickBossRoss/status/191572771313164290) of good documentation?  I thought everyone hated IKEA instructions to the point it is a cliche.

> I had to decompress the release apk and adb push the .so files to the app-lib directory but I still don't know why do I have to do this to make an android repo work :confused:

Yeah cuz...

https://github.com/cSploit/android/tree/develop/cSploit/src/main/jniLibs

It tells you this is where the prebuilt libs go.

```
cd path_to_cSploit_git_root
git pull
git submodule update --init
(cd cSploit/jni; ./build.sh) || cat cSploit/build.log
./gradlew assembleDebug
```

Or see the [nightly build script](https://github.com/cSploit/android/blob/master/nightly-build.sh). 

Or feel free to contribute documentation that meets your standards, cranky.  It's open source.  Go to it.

**Comment by Silur** [comment]
My apologies I didn't know about the git submodule workaround for this sorry,  feel free to close this "issue"
