### ISSUE TITLE
tcpdump failed to write pcap file

### ISSUE THREAD

**Issue by Silur** [cSploit/android#595]
MITM simple sniffing works fine when no pcap file is selected but fails to start tcpdump when pcap writing is enabled.
Overridden methods from TcpDump.java produce the following logcat:
```
I/sniffbug onStart tcpdump -nvs 0 -Uw '/storage/sdcard0/cSploit/csploit-sniff-1456623561618.pcap' not '(src host localhost or dst host localhost or arp)'

E/sniffbug﹕ onError tcpdump: /storage/sdcard0/cSploit/csploit-sniff-1456623561618.pcap: No such file or directory

I/sniffbug﹕ onEnd 1
```
The file written above exists at the location but is always 0bytes in size.
Directory permission is rwxrwx, the app can write files to the directory (I've successfully written files from code to this dir).

**Comment by tux-mind** [comment]
Hi @Silur thank for detailed report, I really appreciate it and I need people like you to achieve a stable version of the App :smile: 

Giving a quick look to the Java side I see no errors...

Can you spot the problem launching the command from a su shell ?
Also give a look to the daemon log ( `/data/data/org.csploit.android/files/cSploitd.log` )

Thank you for your precious time :heart:

**Comment by Silur** [comment]
running the command `tcpdump -nvs 0 -Uw '/storage/sdcard0/cSploit/csploit-sniff-1456623561618.pcap' not '(src host localhost or dst host localhost or arp)'` manually successfully creates the file, can write and cSploit can read from it (with custom-made read from pcap feature).
cSploitd.log does not provide anything useful, still working on the issue

**Comment by Silur** [comment]
fixed, it was a permission issue, made a [pull request](https://github.com/cSploit/android/pull/625)
