### ISSUE TITLE
Downloads Page removed? 

### ISSUE THREAD

**Issue by Cursewords** [cSploit/android#600]
Why was the downloads page removed?

**Comment by xaitax** [comment]
It was not?!
http://www.csploit.org/downloads/

**Comment by pahapoika** [comment]
@xaitax
![img_20160307_100836](https://cloud.githubusercontent.com/assets/15216654/13563703/b81fb46a-e44c-11e5-9333-b155b60fcc02.jpg)

**Comment by pahapoika** [comment]
That link doesn't work

**Comment by xaitax** [comment]
Well, the change of the URL was made quite a while ago. The issue is that google didn't seem to have updated their index yet. We could embed something like Google Webmaster Tools to force them to recrawl. Till then ... not much one can do.

**Comment by Cursewords** [comment]
Go to http://www.csploit.org/

Click "Get started"

404 error page not found.

That's what I meant. Seems there are a few pages not working.

**Comment by xaitax** [comment]
True. Missed that link. Fixed.

**Comment by tux-mind** [comment]
@xaitax thank  youuuuu :heart:
