### ISSUE TITLE
Heart attack

### ISSUE THREAD

**Issue by ghost** [cSploit/android#601]
hi i have a samsung s5 mini ( sm- g800f ) and before the new update 1.6.5 app worked but now that I've upgraded says "an heart attack occurred" can solve?
Ps . my sm- g800f has the root and has the TWRP.

**Comment by WolfServer** [comment]
Can you run the app again but run logcat as well to get us a log please?

**Comment by InsideBall** [comment]
Same issue on ematic egq377

**Comment by Megaeloelo** [comment]
Use SuperSu not kingroot .

**Comment by IwraStudios** [comment]
This issue has been merged into https://github.com/cSploit/android/issues/636
