### ISSUE TITLE
MSF UPDATE ERROR

### ISSUE THREAD

**Issue by NooBhere** [cSploit/android#602]
Sir i installed core .
then it asked for ruby ezily installed.
then it asked for msf update i accepted and some error came file is corupter like this pls help

**Comment by sorano** [comment]
What makes you think it is ok to spam open issues? Just because you are a noob does not mean you can act like a tard.

Read this and come back with proper issue reporting:
https://github.com/cSploit/android/wiki/How-to-open-an-issue

**Comment by fat-tire** [comment]
Heh.. what I think sorano is saying is thank you so much for your contribution and bug report, but everyone would like more detailed info :)
