### ISSUE TITLE
Again sir MSF UPDATE ERROR

### ISSUE THREAD

**Issue by NooBhere** [cSploit/android#604]
i have downloaded and installed gems then msg comes in notification abour MSF RPC DAEMON  failed to start :(

**Comment by jonniex7** [comment]
Busybox is installed in your device??

**Comment by sorano** [comment]
What makes you think it is ok to spam open issues? Just because you are a noob does not mean you can act like a tard.

Read this and come back with proper issue reporting:
https://github.com/cSploit/android/wiki/How-to-open-an-issue
