### ISSUE TITLE
Cannot start process. 

### ISSUE THREAD

**Issue by bmiddha** [cSploit/android#613]
Anything I run I get the error cannot start process
I am using nethunter 3 on one plus one

**Comment by OctAg0nO** [comment]
same problen, on nexus 6,  android 6, nethunter 3.

**Comment by IwraStudios** [comment]
Read https://github.com/cSploit/android/wiki/How-to-open-an-issue and upload a logcat

**Comment by IwraStudios** [comment]
Make sure you have root acces and that you have busybox installed
