### ISSUE TITLE
Ettercap ERROR : 2, ERROR : 2, No such file or directory /home/max/Documenti/cSploit/android/cSploit/jni/ettercap-ng/

### ISSUE THREAD

**Issue by sgeto** [cSploit/android#614]
Hi guys,

This is not necessarily an issue with the app in the usual sense, but am facing some issues while tying to use the ettercap binary supplied with csploit separately from the app itself (from a terminal). 
When I invoke it from the command line i am presented with a variety of error messages:

1. ettercap can't find its default config file etter.conf located at ever though it's located at /data/data/org.csploit.android/files/tools/ettercap/share/etter.conf. 
I can fix that by just adding the -a option and pointing at the file

2. Normally the default syntax for adding an entire subnet to your target is // //. This version except this and this only ////. 
It took me a while to figure that out but this is also no big deal...

3. But after executing this command I am getting the following error:

ettercap -i wlan0 -Tq -M arp:remote -a /data/data/org.csploit.android/files/tools/ettercap/share/etter.conf ////

←[1mettercap 0.8.0←[0m copyright 2001-2013 Ettercap Development Team

Dissector "napster" not supported (etter.conf line 102)
Dissector "napster" not supported (etter.conf line 102)
WARNING: [/home/max/Documenti/cSploit/android/cSploit/jni/ettercap-ng/src/os/ec_linux.c:disable_interface_offload:183]

 cannot disable offload on wlan0, do you have ethtool installed?

Listening on:
 wlan0 -> 00:37:6D:61:38:05
          192.168.1.111/255.255.255.0

SSL dissection needs a valid 'redir_command_on' script in the etter.conf file
Privileges dropped to UID 0 GID 0...

   0 plugins
  39 protocol dissectors
  53 ports monitored

ERROR : 2, No such file or directory
[/home/max/Documenti/cSploit/android/cSploit/jni/ettercap-ng/src/ec_manuf.c:manuf_init:125]

 Cannot open etter.finger.mac
___________________________________________________________

It is clear that the errpr lays in the binary is constantly looking for the directory /home/max/Documenti/cSploit/android/cSploit/jni/ettercap-ng/src/ for all it's files (including etter.conf; ERROR : 19). I think if it knew that the it should look in /data/data/org.csploit.android/files/tools/ettercap/share instead most if not all error would be resoved.
I am a fairly new to android, but have been using ettercap for years.I had never any severe issues with it on Linux. 
I always very much disliked compiling applications from source. But I guess if I cant find help for problem here, I am just going to take that road....

Any thoughts are appreciated.
Again: I have no idea regarding android. Maybe everything I just wrote is completely wrong.

Thanks in advance

______________________
Phone: Samsung Galaxy S II
ROM: Resurrection Remix (based on ASOP 5.1.1 and CM 12.1)
Csploit version; 1.6.3
no Xposed module was used at the time of error and I don't think a logcat is really necessary for this issue (if it is please let me know)

**Comment by tux-mind** [comment]
hi @sgeto , thank for your post :blush: 

As far as I remember my version of ettercap supports ipv6, which leads ettercap to use the syntax with 3 slashes.

so your command should be:

```
ettercap -i wlan0 -Tq -M arp:remote -a /data/data/org.csploit.android/files/tools/ettercap/share/etter.conf /// ///
```

btw I'm working on changing our building system and I've recentry re-ported ettercap in a more elegand and clean way, please cehck out our [botbrew](https://github.com/cSploit/botbrew) repo :wink:

I'm sure that you'll find it extra useful :grin:

**Comment by tux-mind** [comment]
you should also run the tool in it's directory as described from the [handler interface](https://github.com/cSploit/android.native/blob/master/cSploitHandlers/ettercap.c#L45).

sorry if it is not well documented, but it's meant to be used internally cSploit :grin:

**Comment by sgeto** [comment]
Wow I didn't know about the syntax change in IPv6. Thanks for the clarification.

BotBrew sounds amazing and I already came across it many months before but it never seemed to work for me. I don't recall the exact error I got back then but it was so weird that I assumed the software was abandonware. 
Trying to install the package manager again today is returned a 404 error. Your web sever seems to be down. Would you mind taking a look at this issue?

**Comment by tux-mind** [comment]
readme comes from upstream ( abbandonware :grin: ), sorry :wink:

just [fixed] :sunglasses: 

[fixed]: https://github.com/cSploit/botbrew/commit/4913025d8a809c21372fd0659f37027ae91e3929

**Comment by tux-mind** [comment]
basically clone the repo and follow the readme :yum:

**Comment by sgeto** [comment]
Thank you very much for your support. 
Please excuse me if I am being rude, but I have one more request:
If it's not too much to ask, would you mind building ettercap for me? I am for financial reasons currently unable to set-up a building environment.
Thanks and sorry.

**Comment by tux-mind** [comment]
Enjoy it :blush: 

[repo.tar.gz](https://github.com/cSploit/android/files/201333/repo.tar.gz)

**Comment by tux-mind** [comment]
Sorry, I've left the other packages, give me a while....

**Comment by tux-mind** [comment]
this should contains all the dependencies of ettercap.
let me known if some 2nd level dep are missing :grimacing: 

[repo.tar.gz](https://github.com/cSploit/android/files/201347/repo.tar.gz)

**Comment by sgeto** [comment]
I was really trying hard to avoid this question but: what am i looking at? They don't seem to be executable...

**Comment by sgeto** [comment]
Did I say something wrong?

**Comment by tux-mind** [comment]
Sorry i didn't saw your post, I'm busy with the daemon right now.

Isn't the README enough ?

Please tell me your questions.

Botbrew is a software that build UNIX tools for Android.
Il 12 mag 2016 3:48 AM, "sgeto" <notifications@github.com> ha scritto:

**Comment by sgeto** [comment]
i am very sorry for the late reply. The executable files you kindly build for me don't seem to work. The have an extension I am not familiar with (opk). I would very much appreciate if you could explain the steps required to actually run them. 

Good luck with the daemon btw...

**Comment by tux-mind** [comment]
Hi, i'm heading to the office right now, but the following thread should help you enough: http://forum.xda-developers.com/showthread.php?t=1446541

Let me known if you need any further help :)
