### ISSUE TITLE
Cant find any targets

### ISSUE THREAD

**Issue by and313** [cSploit/android#623]
I dont know whats going on on my 6p but i think since the mm update csploit could not find any targets. I downloaded core, ruby and msf and it installed ok. Does it even work on mm?

**Comment by and313** [comment]
I had the same issue on the n5 since the mm update

**Comment by tux-mind** [comment]
Hi @and313 , can you provide a logcat ?

thank you in advance for your time :blush:

**Comment by and313** [comment]
https://drive.google.com/file/d/0Bx_H00kDXlWPU2o0R0h6clE3UnM/view?usp=docslist_api

Here you go :)

**Comment by tux-mind** [comment]
uh.... I see that cSploit find targets... really it do not show them ?

I have to reproduce this on my side, have to setup an emulator with android 6.0 .

thank you for the report :blush:

**Comment by and313** [comment]
I found the problem. I updated to latest supersu library and now it works. Somehow i messed up the files, i am very sorrh
