### ISSUE TITLE
[BUG] Update Failed!

### ISSUE THREAD

**Issue by agucova** [cSploit/android#628]
Similar to #626 
I open the app, it says the core is not installed, a update available shows, I click "yes". Then in just 2 seconds or less, it shows "**Update Cancelled**"

![combine_images](https://cloud.githubusercontent.com/assets/4694408/14335574/aca32b00-fc32-11e5-955f-f60d4f39c18c.png)

```
Specs:
OS: Android 5.0.0
Model: Blu Studio Energy 2
ROM: Stock
Rooted via: Kingroot, but I uninstalled it, and installed SuperSU
No xposed
```

_EDIT: I tried with the latest pre-release, and the same._
**Logcat (Info): http://hastebin.com/wafuhadovi.avrasm**

**Comment by agucova** [comment]
Similar to #626, but this includes more information.

**Comment by agucova** [comment]
Sorry for not assigning it as a Bug!

**Comment by Silur** [comment]
Hi
Can you show us the contents of  `/data/data/org.csploit.android/files/cSploitd.log` too? that could hold valuable info :)

**Comment by venus342** [comment]
Hi, The problem is that it doesnt get enough permission/ something is blocking.
When does that pop-up appear (Update failed)?
After you grant root access or before?
Thanks
