### ISSUE TITLE
rootbitch.cc

### ISSUE THREAD

**Issue by pahapoika** [cSploit/android#630]
Hey. It's me again :)

Well i have spent my time coding Android rom and kernel to my op2 and op1. I get my op2 rom and kernel done (based to unofficial cm13) and i were starting to write rom and kernel to op1. But the phone fell out from my jackets pocket (Fail) and now the screen isin't responsing cuz the little scrach top of the screen. Now i sent it to repair so i hope it will be ready in 2016 :) (Lol i heard that oneplus sucks at RMA)
And now the op2 rom is overdated and i dont have time to update it.

But to the issue. http://rootbitch.cc/csploit/cSploit-nightly.apk wont push any file. Tried refresh, open in new tab etc. 
@xaitax

**Comment by xaitax** [comment]
Hi @pahapoika, my mistake, sorry. I resetup the webserver and introduced an issue while trying to make it more secure. Now it's fixed and working again.
Thanks for letting me know.
