### ISSUE TITLE
Heart attack occured

### ISSUE THREAD

**Issue by narkasis** [cSploit/android#636]
I recently installed csploit (latest version) downloaded everything the app asked me to, and I tested it everything worked great, but the next day I opened the app and it showed me that heart attack occured I tried clearing data, reinstalling the app but every time I download the core it says heart attack occured I tried nighty version after installing the core the app won't show anything just a csploit logo in the middle

**Comment by AdLindsay** [comment]
That usually happens when people are using KingRoot/Kinguser. If you have these then you need to replace them with supersu. Search google for "replace kingroot with supersu"

**Comment by venus342** [comment]
Hey! Can i please get a Logcat?
You can try updating busybox & updating supersu (other root apps wont work).
Thanks.

**Comment by IwraStudios** [comment]
this issue will be merged into https://github.com/cSploit/android/issues/533

**Comment by kriswesselmann** [comment]
Replace kinguser with superuser

**Comment by kriswesselmann** [comment]
Oops, first post was me typing a search in the reply box.

**Comment by kriswesselmann** [comment]
Oops, first post was me typing a search in the reply box.
