### ISSUE TITLE
How to compile

### ISSUE THREAD

**Issue by kodingeg** [cSploit/android#641]
I won't to know how to compile a nightly build on linux or better on android

**Comment by pahapoika** [comment]
Why would you compile?  But > https://github.com/cSploit/android/blob/master/nightly-build.sh
If you want just want to download latest nightly head to http://rootbitch.cc/csploit/cSploit-nightly.apk

**Comment by kodingeg** [comment]
I would like to make a few changes so is there is any way to compile on android it self ?

**Comment by DeveloppSoft** [comment]
@kodingeg, a long time ago I tried what you want to do (for example with AIDE), unfortunately such apps were not able to find all the dependencies...

**Comment by kodingeg** [comment]
Right now I'm building the project with aide pro but it take a very long time in 'Dexing' the librarys stage

**Comment by pahapoika** [comment]
@kodingeg maybe this is what you are looking for? 
https://github.com/cSploit/android.native/blob/master/README.md
