### ISSUE TITLE
Cannot access to app {

### ISSUE THREAD

**Issue by ghost** [cSploit/android#643]

**Comment by Xmashine** [comment]
I cannot start app, i jeep me in the start screen

**Comment by Xmashine** [comment]
I'm running andrioid 4.4.4 on GT-S7500

**Comment by pahapoika** [comment]
Hey, please read:
https://github.com/cSploit/android/wiki/How-to-open-an-issue

Are you rooted? Is your superuser app supersu?
Do you have busybox installed?

Thanks.
