### ISSUE TITLE
Cannot find a core for this device

### ISSUE THREAD

**Issue by super-n00b** [cSploit/android#645]
Hi,

I just tried to run csploit on several Android phones and versions via genymotion (last Nexus 4 and Galaxy S4 both with Android 4.4.4). I have installed the ARM Translation v1.1.zip for Genymotion and also BusyBox. I'm running into the same error as described in an earlier issue (#75: https://github.com/cSploit/android/issues/75). The error pop-up says it cannot find a core for my device. I tried an old version that still includes the core and here I run into the error that it believes I have no ARM.

Unfortunately I cannot reproduce the solution of the OP in #75. Whatever I do, it does not work - nightly-build included. Logcat is the following:

[logcat.txt](https://github.com/cSploit/android/files/241183/logcat.txt)

Many thanks already!

**Comment by pahapoika** [comment]
Hey. 
Is your genymotion rooted? And is supersu the superuser app. Maybe cSploit doesn't regonize your phone cause it doesnt have build.prop? Or it still regonizes that your "phone" has x86 as its cpu architect. Cant say cause the logcat does just provide connection errors. Maybe @tux-mind can help you more?

If you take logcat you should filter it to org.csploit.android. Then you will see just csploit related events.

Thank you

**Comment by super-n00b** [comment]
Many thanks already @pahapoika ! @tux-mind is it possible to simply download the core and what else is missing separately and then make the app getting it local from my "phone" instead of trying to download it.
Concerning the x86 build: That indeed might be a problem as I'm running into exactly this when trying to install dsploit (sorry for being unfaithful^^). I installed the ARM Translation v1.1.zip which kind of should fix that, right. How can it be it doesn't?
Best regards and keep up the good work.

**Comment by IwraStudios** [comment]
This issue is resolved and "moved" to https://github.com/cSploit/android/issues/650
