### ISSUE TITLE
Ruby update 

### ISSUE THREAD

**Issue by LeoDaVinci-336sec** [cSploit/android#646]
When i start the app it says a new update for ruby is available. But when i press it it waits a bit then says it failed. I have a htc one m7

**Comment by pahapoika** [comment]
Hey, please read:
https://github.com/cSploit/android/wiki/How-to-open-an-issue

Are you rooted? Is your superuser app supersu?
Do you have busybox installed?

Thanks.

**Comment by sherpya** [comment]
I had the same problem, my device has busybox but not correct links like `which`, `env`, I suggest to call `busybox which` and `busybox env` (etc) instead
