### ISSUE TITLE
Heart attack occured!

### ISSUE THREAD

**Issue by venus342** [cSploit/android#647]
Please help as soon as possible.
Already tried clear data and many things.
Tried nightly build.
Nothing works.
Root permission granted through SuperSU
Using Samsung Galaxy S6 Edge.
Android 5.0.2 Lollipop

**Comment by pahapoika** [comment]
Hey.
 please read:

https://github.com/cSploit/android/wiki/How-to-open-an-issue
You should provide logcat

Do you have busybox installed?

Thanks.

**Comment by venus342** [comment]
Hello.
I have busybox installed. But not sure how to run logcat.
Thanks.

**Comment by pahapoika** [comment]
Heres guide: http://forum.xda-developers.com/showthread.php?t=1726238

Also make sure that you have installed latest version of cSploit https://github.com/cSploit/android/releases

Download latest:
https://github.com/cSploit/android/releases/download/v1.6.6-rc.1/cSploit-release.apk

**Comment by venus342** [comment]
Just solved the problem! If you are having same problem, try these :-
1. Using Latest version of csploit
2. Updating your busybox (Solved my problems)
3.Updating SuperSU
4. Clear Dalvik Cache (If required)
5. Uninstall and reinstall 
Thanks @pahapoika
