### ISSUE TITLE
Cant start MSF RPCD ; Installed Ruby, MSF & Gems properly.

### ISSUE THREAD

**Issue by venus342** [cSploit/android#648]
Hi, i installed everything properly but when i click on start MSF RPCD, nothing happens. After some time a notification comes MSF RPCD starting. Standby
After waiting for 20 minutes, Nothing happens.

Here is the log
https://drive.google.com/file/d/0B1txj8cm8i-XZXB3NXMtVnYxWk0/view?usp=drivesdk
Device info is included.

**Comment by Frnk7** [comment]
Same for me

**Comment by venus342** [comment]
@Frnk7 i have just founded out to fix that issue!
Uninstall Csploit
Reinstall latest version 
Update busybox and supersu.
ONLY SUPERSU will work, king root/king user wont work/
Try again. It fixed my problem
