### ISSUE TITLE
cSploit unable to install MSF gems

### ISSUE THREAD

**Issue by dimakx** [cSploit/android#65]
Good Morning, I've got a new issue on my gt-i8190 (S3 mini).

cSploit doesn't install MSF gems.

I've the stock firmware with BusyBoxPro fully installed.

I've looked at every issue already posted here in github, but none of 'em has helped me resolving this problem.

Here is my catlog: https://mega.co.nz/#!aJxTzAyZ!CI0FWcZeGAQCjVg3dvPDSyHnbaWMcB57f7N7EXn4IVc

(I know that you, tux-mind, prefer pastebin but I wasn't allowed to load the log cause it exceeded the maximum limit of words)

I kindly ask you to check what a possible problem could be from analyzing this catlog and wish you a good day.

Yours Sincerely,
dimakx

**Comment by rigid** [comment]
next time, https://gist.github.com should work ;)

**Comment by tux-mind** [comment]
@dimakx so gentleman :heart_eyes: 

I'm cloning the repo and building version 1.3.0 to debug a `network-radar` error on your device.
probably a double-free bug.

**Comment by tux-mind** [comment]
@dimakx the following problems has occurred on your device:

  - a download error when installing `meterpreter_bins` the first time ( a component of the MSF )
  - your device is affected by #11 and msf directory hasn't been deleted on error.
  - every time you retry the corrupted gem is there.

>**hotfix:** remove the `/data/data/org.csploit.android/files/msf` directory manually

let me known if it works.

**Comment by tux-mind** [comment]
@dimakx will check it tomorrow. have to go out for dinner with my lady, we celebrate the first year of relationship today :blush:

**Comment by dimakx** [comment]
I've already tried that hotfix dozens of time but nothing worked :(. I wish you and your Lady a happy night of celebration. I really appreciate your help, thanks.

**Comment by sorano** [comment]
Duplicate of #205
Try the latest version.
