### ISSUE TITLE
Cannot start process

### ISSUE THREAD

**Issue by Teopan** [cSploit/android#657]
When I try to start a command, a message appears telling me that "cannot start process"

**Comment by Teopan** [comment]
I am superuser and I have busybox fully installed

**Comment by Teopan** [comment]
http://pastebin.com/EsyrRmZs here's the log file

**Comment by xkvnn** [comment]
same here, when update core then crash app.

**Comment by Teopan** [comment]
I found a solution. I just had to update root binaries and install SuperSu.
