### ISSUE TITLE
Help me with new core. It not work!

### ISSUE THREAD

**Issue by mihakrut** [cSploit/android#660]
My logcat on my site http://plcr.tk/crashlogs.txt , because pastebin dont copy big text. Csploit show "Heart attack occured. app only check for updates. Updates not fount." when I install core. Csploit all versions (I test all) dont work with new core 1.0.11. I remoe csploit data, reinstall app. It doesnt help me. Please fix it.

**Comment by venus342** [comment]
Hey, 
Are you using SuperSU?
Kingroot/KingUser wont work.
And how did you root your phone?
Thanks

**Comment by mihakrut** [comment]
I use Kingroot, in /data/data it is com.kingroot.kinguser. What should I do?

**Comment by mihakrut** [comment]
I remove KingRoot and install SuperSU. Csploit works. Thanks.
