### ISSUE TITLE
CSploit pls help

### ISSUE THREAD

**Issue by KaustubS** [cSploit/android#664]
hey guys so I just intalled nethunter, it got stuck at 90% so i booted phone back up. All the apps show up and I tried CSploit but it says Cannot Start Process____Please help me out?

**Comment by DeveloppSoft** [comment]
Is your phone rooted? (with __super su__)
Did you installed busybox?
By the way, please read: [how to submit an issue](https://github.com/cSploit/android/wiki/How-to-open-an-issue) next time...
