### ISSUE TITLE
When target disconnects no tool reports an error.

### ISSUE THREAD

**Issue by Avamander** [cSploit/android#67]
I tried tracerouting, scanning the ports, basically every tool and every tool yielded no results. I suggest you'd check if the device is still on the network.

**Comment by mcilya** [comment]
Device that disconnected from network becomes grey, but doesnt removes from list

**Comment by Avamander** [comment]
But if you click on it while it's not grey and then it disconnects? It does not tell you.

**Comment by sorano** [comment]
moved this to #229
