### ISSUE TITLE
Is SSL strip working???

### ISSUE THREAD

**Issue by HumanManGuy** [cSploit/android#689]
I enabled SSL stripping but I see no results and all devices still go to HTTPS, please help!

**Comment by HumanManGuy** [comment]
Nexus 5x running Cyanagenmod 13.

**Comment by evertking** [comment]
Nopr

**Comment by pahapoika** [comment]
Hey @HumanManGuy
It only works from http to https. So if you are in http://www.example.com and u click something that redirects to https://www.anotherexample.com it will get hijacked.

**Comment by HumanManGuy** [comment]
But what if someone goes to "Google.ca" will that get hijacked? (Will they continue to Https://ca or not)

**Comment by pahapoika** [comment]
Sites that uses tsl or ssl it will not be hijacked, __ if __ you didnt were redirected to that site from http site.

**Comment by IwraStudios** [comment]
https://github.com/cSploit/android/issues/680 related post maybe a feature for the future
