### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by Yous34** [cSploit/android#690]
Csploi won't work on android 4.4.4 kitkat o tryed bothe the stable and the unstable versions, when i try to run a function it sais "cannot start process" "cannot execute commands"

**Comment by IwraStudios** [comment]
please read: https://github.com/cSploit/android/wiki/How-to-open-an-issue
post a logcat

**Comment by Yous34** [comment]
my phone is salaxy grand neo plus (gt-i9060i) 4.4.4 kitkat 1gb ram quadcore 1.2ghz
This is the logcat:
[Uploading CSPLOIT_ISSUE.txt…]()

**Comment by IwraStudios** [comment]
From what i have seen your using Xposed wich can cause trouble: https://github.com/cSploit/android/wiki/Known-incompatibilities
there was also an SocketException but I dont know if that's related to the Xposed issue

**Comment by Yous34** [comment]
@IwraStudios i use kingoroot too, is the only solution to remove xposed ?

**Comment by IwraStudios** [comment]
if you using both.... yeah you need to remove xposed and go to supersu

**Comment by Yous34** [comment]
@IwraStudios but i really need xposed can't the devs fix this isssue?

**Comment by IwraStudios** [comment]
i don't think we can. if we could we would have fixed it a few hunderd issues ago

**Comment by Yous34** [comment]
I can tell that kingoroot it's not causing issues cuz u have it on my tablet (5.0.1 lollipop) an csploit is running fine
