### ISSUE TITLE
Wifi scans refuse to connect

### ISSUE THREAD

**Issue by phillipc93** [cSploit/android#695]
Freshly downloaded v1.6.5 tonight after being told cSploit is better than dSploit. I'm running an LG L22C Power on 5.0.1 Lollipop, rooted via Kingroot and managed with both Kinguser and SuperSU. _Why do I have Kinguser and SuperSU? I dunno._

First thing I'm presented with is "Heart attack occurred, the application will just check for updates. No updates available."

Next, I try a WiFi scan and am presented with the router I'm already connected to. I put in the *correct* key only to get "Connection to XYZ FAILED." I'd really like to be able to connect so that I can actually start a session, though.

**Comment by IwraStudios** [comment]
Could be kingroot causing trouble (https://github.com/cSploit/android/wiki/Known-incompatibilities)
that causes the heart attack for the other stuff i'll need a logcat

**Comment by phillipc93** [comment]
I'll hook you up with a logcat as soon as I turn my phone on.

Assuming Kingroot is the "root" of the problem (tee-hee), would I simply just have to remove it? I've seen 8 million tutorials on how to replace Kinguser with SuperSU with no explanation why I should; I guess now I know.

**Comment by IwraStudios** [comment]
yeah i think people found that kingroot is incompatible with a lot of apps

**Comment by phillipc93** [comment]
Hey there, sorry about the long delay. I eventually gave up because I couldn't give you an effective logcat on the matter. Yeah, I know :P

The issue has been resolved, however! All I had to do was find an alternative method of replacing Kinguser with SuperSU; more specifically, I installed SuperSUme instead of that one method with the whole terminal emulator and the sh /sdcard/mrw/root.sh method.

**Comment by IwraStudios** [comment]
glad it's resolved
