### ISSUE TITLE
Changelogs should also display previous changes.

### ISSUE THREAD

**Issue by Avamander** [cSploit/android#70]
Changelogs should be nicely formatted and should feature changes from previous versions.

**Comment by Systemad** [comment]
If you download for github you can see the changes and if you download in app and install new version a new window will pop-up with changes. I don't think this is needed. let's see what tux-mind says.

**Comment by sorano** [comment]
IMO changelog history for older releases on github is enough.

If tux_mind disagrees he can re-open and assign this ticket :)
