### ISSUE TITLE
FAQ for "Detected as virus"

### ISSUE THREAD

**Issue by hackerb9** [cSploit/android#701]
It'd be nice if the cSploit project had a little FAQ listing which antivirus warnings are okay to ignore. I suggest a list because it seems like very bad practice to teach people to ignore all warnings. Here's a sample to start from:

### A: Don't panic.
Many antivirus tools will flag cSploit as malware simply because of what it can be used to do. If you read the source code, you'll see that cSploit doesn't do anything malicious to you on its own, it is simply a tool malicious people might use. So, as long as you're not malicious, you're (probably) okay.

We are *not* saying to disregard your antivirus, though. Even with trusted programs like cSploit you should only ignore the threats that you are sure are false alarms. Here is a list of the ones we know so far (courtesy [virustotal.com](https://www.virustotal.com/en/file/40f2baaffd5fdc5e03b42cb9cddf80752d4071a85fa47c22930262c901f83e3b/analysis/1466504404/)).

Antivirus Program | Virus Detected
--------------------------|----------------------
AVG | Android/Deng.REK | 20160621
AhnLab-V3 |Android-AppCare/DSploit.1a0cb
Alibaba |A.H.Sys.HacktoolDSploit.A
Antiy-AVL |HackTool[:HEUR]/Android.DSploit.2
Avast |Android:DSploit-D [PUP]
Avira (no cloud) |SPR/ANDR.DSploit.70
CAT-QuickHeal |Android.DSploit.B (PUP)
Cyren |AndroidOS/GenPua.33B08F3A!Olympus
ESET-NOD32 |a variant of Android/HackTool.DSploit.C potentially unsafe
Fortinet |Riskware/DSploit!Android
K7GW |Hacktool ( 004d314b1 )
Kaspersky |HEUR:HackTool.AndroidOS.DSploit.b
McAfee |Artemis!33B08F3A9177
McAfee-GW-Edition |Artemis!33B08F3A9177
Qihoo-360 |Android mobile malware

**Comment by hackerb9** [comment]
Oh, and if you want to include the false positives [detected](https://www.virustotal.com/en/file/4b462453b1332c3ed9bcda44d701eeff05a46373f952ef1fe5db3d8aa58e462c/analysis/1465403948/) from the binary that's on F-droid.org, there is one more:

Antivirus Program | Threat detected
----------------------|---------------------------------
AegisLab |Hacktool.Androidos.Dsploit!c

**Comment by IwraStudios** [comment]
thanks for the Q/A
i have added a FAQ page in the github wiki youre Q/A is the first one

**Comment by hackerb9** [comment]
Thanks! I've added the list of "threats" and removed the props to me. (I appreciate it, but don't need the recognition.)
