### ISSUE TITLE
Core fail to download

### ISSUE THREAD

**Issue by Norwegianw** [cSploit/android#707]
OS: YunOS 3.1.6
Model:Meizu M3
Cesploit version:1.6.5
Rom:Flyme 5.1.4.2Y

Detailed info:After the app starts,it asks the user to download the core.At first ,after you choose the "yes",the system reminds you the start of the downloading.But the process stops at 1% or 2%.Personally I think it's a network problem (I am in China) However,after three tries,the app says "文件已损坏”（document damaged) or even doesn't pop up at the information bar.
Perhaps you can provide a network-dish link with the latest core.tar.zx.
Forgive me if my English confuses you.i am just a Chinese high schooler.

**Comment by Norwegianw** [comment]
okay,now after more tries, the core is successsfully download. But it says 致命错误. i will show the catlog.

**Comment by Norwegianw** [comment]
07-31 07:22:42.234 E/CSPLOIT[core.System.errorLogging](20117): Attempt to invoke virtual method 'android.support.v4.app.NotificationCompat$Builder android.support.v4.app.NotificationCompat$Builder.setContentText(java.lang.CharSequence)' on a null object reference
07-31 07:22:42.234 E/CSPLOIT[core.System.errorLogging](20117): java.lang.NullPointerException: Attempt to invoke virtual method 'android.support.v4.app.NotificationCompat$Builder android.support.v4.app.NotificationCompat$Builder.setContentText(java.lang.CharSequence)' on a null object reference
07-31 07:22:42.234 E/CSPLOIT[core.System.errorLogging](20117): 	at org.csploit.android.services.UpdateService.downloadFile(UpdateService.java:576)
07-31 07:22:42.234 E/CSPLOIT[core.System.errorLogging](20117): 	at org.csploit.android.services.UpdateService.onHandleIntent(UpdateService.java:945)
07-31 07:22:42.234 E/CSPLOIT[core.System.errorLogging](20117): 	at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:65)
07-31 07:22:42.234 E/CSPLOIT[core.System.errorLogging](20117): 	at android.os.Handler.dispatchMessage(Handler.java:111)
07-31 07:22:42.234 E/CSPLOIT[core.System.errorLogging](20117): 	at android.os.Looper.loop(Looper.java:192)
07-31 07:22:42.234 E/CSPLOIT[core.System.errorLogging](20117): 	at android.os.HandlerThread.run(HandlerThread.java:61)

**Comment by Norwegianw** [comment]
07-31 07:25:34.990 E/cSploitClient(20117): connect_unix: connect: No such file or directory
07-31 07:25:38.590 W/CSPLOIT[services.UpdateChecker.getCoreUpdate](20117): unsupported platform ( android22.armeabi-v7a )

**Comment by Norwegianw** [comment]
Thank you if you read the info. The problem is solved by rebooting the device.

**Comment by IwraStudios** [comment]
thanks for the info
