### ISSUE TITLE
<3 So Glad <3

### ISSUE THREAD

**Issue by ClanTag** [cSploit/android#716]
Sorry to clutter up the issues thread, but I am so happy that You are continuing to develop this application. I was severely disappointed when I found out that dSploit had been "merged"  with zANTI. 

I am absolutely impressed with the work you've done so far.  The application is much faster and doesn't crash or hang at all.  I've used the application both on my HTC One M8 and RemixOS. I'm an IT Security student, so my programming skills aren't anywhere adequate enough to contribute.  Otherwise, keep up the fantastic work!

**Comment by supercyanhero** [comment]
I agree with you!

**Comment by supercyanhero** [comment]
I agree with you!

**Comment by IwraStudios** [comment]
apology accepted. Also cSploit 2 is coming up so look forward to that. cSploit(this repos) is actually not **THAT** actively worked on, as in mostly fixes and improvements on existing features

Thanks for the support
