### ISSUE TITLE
Port scanner results could be used to speed up inspector.

### ISSUE THREAD

**Issue by Avamander** [cSploit/android#72]
If I have ran the port scanner, why can't it be used to speed up inspector?

**Comment by tux-mind** [comment]
in the `Inspector` You have a `focused scan` option.
that option will run the inspector only on the found opened ports.

this feature is there from about 2 years :sweat_smile:

**Comment by Avamander** [comment]
Clearly it was really easily found feature.

**Comment by tux-mind** [comment]
you're right @Avamander , my apologizes, we need to improve the docs.
