### ISSUE TITLE
core not installing and i reqst u to change for kingo root 

### ISSUE THREAD

**Issue by devrajashwin** [cSploit/android#720]
Ima using night csploit verion .on my android phone plz help me 
core was downloaded but not extracted ,
plz trouble shoot this problem ,
amd make compitable with kingo root , my device is samsung grand duos 4.2.2 
plz man

**Comment by pahapoika** [comment]
Noob read readme.

**Comment by devrajashwin** [comment]
fuck u @pahapoika  ,
dont teach me ....what to do and what to not

**Comment by devrajashwin** [comment]
i finnaly soved my porblem by own adn intsalled SUPER SU ,
fuck u man @pahapoika

**Comment by pahapoika** [comment]
You are welcome.
