### ISSUE TITLE
metasploit

### ISSUE THREAD

**Issue by ATOPJC** [cSploit/android#739]
Metasploit isn't starting I know it's in  pre release and there are a lot of bug's and stuff and this is one of them fix it please

**Comment by IwraStudios** [comment]
what prerelease did you take mine works fine. also Metasploitd always takes a long time to start so you should test if it starts at all after a long time keeping the app open
if it doesn't please read: https://github.com/cSploit/android/wiki/Known-incompatibilities and https://github.com/cSploit/android/wiki/How-to-open-an-issue
