### ISSUE TITLE
Cannot start process and etc.

### ISSUE THREAD

**Issue by LuLaBy** [cSploit/android#74]
Here list of problems
-cannot start network discovery
-cannot start meta rpcd
-crash when trying to refresh host list
-cannot update ruby
-wifi scan delete wifi pass

Add info
kitkat 4.4.2
samsung sm-t211

Log:
http://pastebin.com/YigFzuG2

**Comment by SelfDestruct68** [comment]
Same issue :(

Android 4.4.2
Samsung Galaxy S4 I9505

**Comment by mcilya** [comment]
There is only 1 issue not listed on github its "crash when trying to refresh host list"
Other issues is
Cannot start something - #1
Cannot update ruby - #42
Wifi password delete when scan for networks - #57

**Comment by sorano** [comment]
Duplicate of #205
Try the latest version.
