### ISSUE TITLE
Doesn't Work

### ISSUE THREAD

**Issue by CortexPE** [cSploit/android#744]
It always says: "unable to start process"
or "cannot start commands"

Specs:
Android 4.2.2 AllivOS v2.1
MTK6572
SDKVer 17
RAM: 512MB
VRAM:500MB

**Comment by pahapoika** [comment]
You have rooted your phone with super su?
Do you have busybox.

Also logcat would be helpful.

**Comment by CortexPE** [comment]
I do have root and busybox but csploit doesn't detect it... Idk why.

**Comment by CortexPE** [comment]
PS: I granted it su access.

**Comment by pahapoika** [comment]
Aand it works!
