### ISSUE TITLE
[1.4.0] Cannot find a core for this device 

### ISSUE THREAD

**Issue by CHEF-KOCH** [cSploit/android#75]
Hi,
I just upgraded from build v1.2.4-issue1+v2 to the latest stable 1.4.0 release [here](https://github.com/cSploit/android/releases/download/v1.4.0/cSploit-release.apk) from GitHub an got the following error popup: _cannot find a core for this device_.
The log can be found over [here](http://pastebin.com/raw.php?i=2JxFXDXv).

And another question is why is this release only 2.63 MB and all other releases before 1.4.0 are around 10 MB? Maybe there was an error during the upload or something?!

Thanks, fantastic work! 
:+1:

**Comment by tux-mind** [comment]
Hi @CHEF-KOCH , reduced size if one of the benefits of [moving the core outside the apk](http://www.csploit.org/Behind-android-5/).

your shared cSploitd.log, can you share a logcat ?

thanks in advance :smile:

**Comment by CHEF-KOCH** [comment]
Thanks for the link.
Yes I can share a logcat, but it seems empty (same under v1.4.1), filtered org.csploit.android aaaand nothing to see there. This error is directly on first app start initialization (I'm not under 5.0). So I don't know what todo now.

**Comment by CHEF-KOCH** [comment]
I tried several options now, cleaned everything, looked at issue 1 and such but the answer was much easier (oh my!), my firewall simply blocked the core download - that's all. But anyway strange that there is no log or a _better_ description of these error popup. I hope this may help others with the same _problem_.

**Comment by tux-mind** [comment]
thanks for reporting @CHEF-KOCH .

I think that I will not change the shown error, it's quite clear for me.
