### ISSUE TITLE
MSF Fails to Update/Install

### ISSUE THREAD

**Issue by 4k-developer** [cSploit/android#751]
Everything else can install/update but when it comes to MSF it fails after extracting it.

BLU Advance 5.0
Stock Rom 5.1
v1.6.6-rc.2

**Comment by IwraStudios** [comment]
could you post a logcat while it extracts/gives the error

**Comment by 4k-developer** [comment]
Figured it out my phone just ran out of space. Wow logcats are really helpful.

**Comment by himasaed8** [comment]
Good
