### ISSUE TITLE
Is cSploit dead?

### ISSUE THREAD

**Issue by evertking** [cSploit/android#756]
Has dev on this ended?

**Comment by maddog9696** [comment]
Nope! Dev tweeted a while back:
tux_mind @tux_mind
Some good news: finished my first level degree. cSploit 2 planned for December ;)
Thank to all contributors for making it possible! <3

**Comment by maddog9696** [comment]
As well as: 
Hi @evertking , i Can proudly tell you that you're wrong 😊

As you can see from the daemon project we are actively working on cSploit and, as I tweet some week ago, cSploit 2 is planned for december.

In the next few weeks I'll start searching for component testers ( people who can test the single components of cSploit, like wifi or network scanner ).

See you soon ;)
