### ISSUE TITLE
MITM has no effect - and sniffing is never device specific

### ISSUE THREAD

**Issue by MikeCroall** [cSploit/android#757]
Tried on multiple target devices, there was simply no effect.
Separately, when a target is selected and sniffed, it goes to sniff the whole network, instead of just that target.

**Comment by pahapoika** [comment]
This is strange.

Logcat would help.
Also some info about your phone is necessary.

**Comment by MikeCroall** [comment]
It was a Samsung Galaxy S4 running Cyanogenmod nightly builds. I do not yet have a logcat, as the phone got bricked by an OTA and I haven't gotten round to fixing it yet.

**Comment by pahapoika** [comment]
Hey.
Hard bricked or soft bricked?
Hardbricked doesnt boot to recovery.
If it's just soft bricked use twrp.
Wipe system and dalvik/cache.
Then just flash working rom. (Use computer to transfer the rom to ur phone.)(usb transfer works in twrp)

**Comment by MikeCroall** [comment]
It doesn't boot to recovery - it shows warranty bit: recovery and shuts off. Supposedly fixable with Odin, but I'll have to get onto windows for that.

**Comment by MikeCroall** [comment]
UPDATE: 
I have been following [this](http://forum.xda-developers.com/showthread.php?t=2265477) XDA thread on saving a bricked S4, and it's making no difference, so unfortunately I can't provide any additional information.
