### ISSUE TITLE
Cannot start process

### ISSUE THREAD

**Issue by jeancarlosg93** [cSploit/android#76]
Csploit 1.4.1
Cm12 android 5.0.2
One plus one (bacon)

Errors when dowloading core update and metasploitframework
Cannot start inspector

**Comment by mcilya** [comment]
Can you post logcat and /data/data/org.csploit.android/files/csploitd.log

**Comment by jeancarlosg93** [comment]
Here are the logs you requested http://goo.gl/MI1GzV

**Comment by mcilya** [comment]
You're affected by #1 there is no solution right now. Msf doesnt updates for me so youre not alone :wink:

**Comment by jeancarlosg93** [comment]
Ok, thanks for the info ☺

**Comment by sorano** [comment]
Duplicate of #205
Try the latest version.
