### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by tvlpirb** [cSploit/android#761]
I see my laptops ip but when I click it and choose sevice inspector it takes a while to load but it doesn't show the services and when I select port scanner it says no open ports detected on current target, run the device inspector first

**Comment by ALoGeNo** [comment]
HI Talhah, I'm using this one, looks like runs ok, http://rootbitch.cc/csploit/cSploit-nightly.apk

Cheers.

**Comment by Talhah-Peerbhai** [comment]
Thanks but when I download and install it say parse error
