### ISSUE TITLE
Heart attack ocurred

### ISSUE THREAD

**Issue by KatsuShooter** [cSploit/android#765]
Hi. I have Meizu pro 6. I installed root from settings because kingoroot doesn't work. So I installed csploit yesterday too. It worked good. But today when I get upped and opened csploit I saw text "heart attack occurred etc. " if do you know answer write please!

**Comment by IwraStudios** [comment]
make sure you have the latest version of busybox and cSploit
also could you supply some more info

**Comment by KatsuShooter** [comment]
I update but I have that problem. In nightly version it's work, but it's not found devices. I saw my telephone and router.

**Comment by IwraStudios** [comment]
and does the newest RC (https://github.com/cSploit/android/releases) not work?

**Comment by KatsuShooter** [comment]
No

**Comment by pannzh** [comment]
This problem is caused by KingUser or KingRoot. You may want to replace it with SuperSU or other root permission managers.

**Comment by pahapoika** [comment]
Closing since duplicated.
All futher messages should be sent in
#828
