### ISSUE TITLE
[Off-Topic]

### ISSUE THREAD

**Issue by eflen** [cSploit/android#766]
Yeah I know this is not the place...
Didn't found any way to contact tux mind...other than twitter...dont like to spread my phone number.

Let's start...
I have Xperia Z3 Compact and i love csploit...helps me in most cases...

So i wanted to donate some bitcoins (2 maybe) to the project...but
I have a request too...2 bitcoins means like 1400$ now and I want my phone to be nearly fully supported...
So here is the deal:
I send the 2 bitcoins,and you buy a Xperia Z3 Compact with 400 of it and spend the other 1K for the project and test the app after final build on the Z3C so i be sure it's compatible with my phone.

I don't think it bugs you much...
You get 1K for the project
Plus and acme phone to work with....

Agree?

**Comment by IwraStudios** [comment]
so I'm no @tux-mind  but I'm very confused by the proposition
just to be clear it will be like this

1. 2B to tux
2. then tux gives back ~0,75B to buy the phone

so why not do this:

1. Give tux 1,25B and a phone

**Comment by eflen** [comment]
Well that's a good option too if @tux-mind isn't concerned about his private info too much ( well I am and dont like to give personal information to someone on the Internet).

Giving 1.25BTC and my phone from Amazon or giving the 2BTC... Your choice tux mind...

Its just a matter of time until I prepare for transfer, also it takes some time to transfer that much.

**Comment by eflen** [comment]
Well he not really gives back...he will pay that to Amazon...not giving back to me :D

**Comment by eflen** [comment]
@tux-mind so whats the deal?

**Comment by pahapoika** [comment]
Gimme 2-bitcoins and i think i can sort this with tux-mind :D

**Comment by IwraStudios** [comment]
so im a bit late with this but you can donate bitcoins at http://www.csploit.org/donate/
