### ISSUE TITLE
MSFRPC Error downloading update.

### ISSUE THREAD

**Issue by Msrpc** [cSploit/android#77]
cSploit:1.4.1
Samsung Galaxy S3 CM12 Lollipop 5.0.2

"cannot start process"
"Error:An error occurred while downloading the update." 

cSploit debug:http://pastebin.com/Nuuqwz7r

catlog:http://pastebin.com/N34tsZye

**Comment by rigid** [comment]
same here on CM11

**Comment by tux-mind** [comment]
Duplicate of #43
