### ISSUE TITLE
Metasploit can't run

### ISSUE THREAD

**Issue by JoLiKs** [cSploit/android#774]
Metasploit RPCD can't load.

**Comment by pahapoika** [comment]
What phone are you using?
Do you have root?
What rom you are using?
Are you rooted with supersu?
Do you have busybox.

Also logcat is necessary.

**Comment by pahapoika** [comment]
What phone are you using?
Do you have root?
What rom you are using?
Are you rooted with supersu?
Do you have busybox.

Also logcat is necessary.
