### ISSUE TITLE
Enhancement | use material lists to show actions

### ISSUE THREAD

**Issue by AndreaCioccarelli** [cSploit/android#775]
Instead of using cSploit default lists in MITM or targetActivity you can implement material design list following the material design guideline. It will improve the general App UI and it will make the list more easy to load and explore on every device because a listView is very fast and smooth.

![components_lists_keylines5](https://cloud.githubusercontent.com/assets/23010471/20064056/a4ea26e0-a509-11e6-8e37-19f3599b084d.png)

**Comment by IwraStudios** [comment]
in https://github.com/cSploit/android/projects/2 I've already added the full material design
