### ISSUE TITLE
Galaxy S6/S7(Edge) arpspoof error

### ISSUE THREAD

**Issue by notmika** [cSploit/android#784]
Hi there, on Galaxy S6 and S7 (both running 6.0.1 Android) ARP spoofing doesn't seem to work. All it says is "arpspoof error", while the JS injection works fine. I hope this can be fixed! I've read a similar issue too, is there any updates on that?

Thanks in advance! :)

**Comment by pahapoika** [comment]
arp spoofing work fine in my oneplus one and s4 mini.
If you can give logcat it would help.
