### ISSUE TITLE
Csploit Website!?

### ISSUE THREAD

**Issue by maddog9696** [cSploit/android#788]
Is the csploit website down? And if so is it down for good? Are you moving solely to github?

THANK YOU SO MUCH DEVS for all of your hard work! I can NOT wait for csploit 2.0!!

**Comment by maddog9696** [comment]
Nvm... Found it avian. That was strange!

**Comment by IwraStudios** [comment]
the site hasn't been updated since Oct 9 though, so you could call it "down" in a way
