### ISSUE TITLE
Installing MSF fails

### ISSUE THREAD

**Issue by Avamander** [cSploit/android#79]
Device: LG D605
Software: CM11

Latest cSploit

https://www.dropbox.com/s/56ep5c02q223796/cSploitd.log?dl=1

**Comment by Interneedus** [comment]
Duplicate of https://github.com/cSploit/android/issues/77

**Comment by tux-mind** [comment]
Thanks for the report @Avamander and sorry for the late reply. Exams period.

Happy to have you on board again :blush: 

Duplicate of #43
