### ISSUE TITLE
Cyka blyat

### ISSUE THREAD

**Issue by oleg6995** [cSploit/android#797]
Произошёл какой то приступ не идёт обновления

**Comment by pahapoika** [comment]
Okay. You know me
Me is Dimitri. I'm a ruski with a big P90
When I rush B, it's always for free
Fat americans will never stop me
If you have AWP it's not for me
A vodka bottle, i take directly
Putin is great, Putin is life
Cyka Blyat is my big kayf
(Kayfe = A state of complete pleasure, enjoyment)
When I want to fight,
I use my karambit knife
But if it's not alright
I will call my wife 
Drinking vodka is my routine
Everyday, with my friend Putin
If you mess with us
We rape your ans
If you're also my friend
You can take my hand
But I'm not homo
I love moloko
If you american fat
Don't say cyka blyat
If you a ruski
Rush B with me
take your P90
and don't be a pussy
Put some Harbass
with your Adidas 
Together we go
plant the potato
Potato Potato
Cyka blyat Rush B and go
Potato Potato
Cyka blyat Rush B and go
Come on join me 
To be a ruski
We have money
And a dynasty
If you sxy lady
You can Rush B
If you Americanski
You can’t Rush B
So be ruski
And take a P90
Today we go
Plant the potato
Potato
Potato
Cyka blyat rush b and go

**Comment by IwraStudios** [comment]
cabbage

**Comment by DeveloppSoft** [comment]
@oleg6995 english please :smile: 
I do not think there was an attack...

**Comment by oleg6995** [comment]
What happened the attack does not install the kernel what to do

**Comment by oleg6995** [comment]
there was an attack, it does not set the kernel what to do?

**Comment by pahapoika** [comment]
What tf are u talking about kernel

**Comment by IwraStudios** [comment]
@pahapoika  we got another one in #811

**Comment by pahapoika** [comment]
@iwraStudios
Lmao putin hired some trolls.
Do we have anyone that speaks russia?

**Comment by DeveloppSoft** [comment]
@pahapoika google does :smile: 
I wonder if we shall close any non english issues...

**Comment by IwraStudios** [comment]
@MasterHelper can speak Russian or has used google translate and has translated #811 to english
