### ISSUE TITLE
Too much heart attack!

### ISSUE THREAD

**Issue by dosattacker** [cSploit/android#803]
When launching app, it's writing "heart attack occured, check for updates" and after that stop working. Lenovo A-35000H. Rooted and have busybox pro

**Comment by pahapoika** [comment]
You really need to get to hospital.


Just kidding.
But you need to provide more information such as logcat.

**Comment by Silur** [comment]
as I remember from the *several duplicates* of this issue, most people resolved it with replacing their root app. Please search for your issue before making a 200th duplicate of the same :)

**Comment by pahapoika** [comment]
Closing since duplicated.
All futher messages should be sent in
#828
