### ISSUE TITLE
Login cracker

### ISSUE THREAD

**Issue by JSBmanD** [cSploit/android#805]
Login cracker doesn't work on android >=6. Just infinity starting. Using nexus 5x, but xiaomi too.

**Comment by pahapoika** [comment]
Upload logcat and other important details. (Rom, supersu/kingroot and xposed for example)

**Comment by JSBmanD** [comment]
PixelROM 4.0.1, super su 2.79. No xposed. Just now it's ok. And suggestion: how about skipping combinations and improving this module? Now its writing some credentials, but it doesn't suite.

**Comment by JSBmanD** [comment]
3C Toolbox Pro (logcat)
======================
W/09:46:56.313 Binder_2( 4236)
type=1400 audit(0.0:74024): avc: denied { ioctl } for path="socket:[2744178]" dev="sockfs" ino=2744178 ioctlcmd=7704 scontext=u:r:system_server:s0 tcontext=u:r:system_server:s0 tclass=unix_stream_socket permissive=0
W/09:46:56.313 Binder_2( 4236)
type=1400 audit(0.0:74023): avc: denied { ioctl } for path="socket:[2744178]" dev="sockfs" ino=2744178 ioctlcmd=7704 scontext=u:r:system_server:s0 tcontext=u:r:system_server:s0 tclass=unix_stream_socket permissive=0
W/09:46:56.270 Binder_9( 5284)
type=1400 audit(0.0:74022): avc: denied { ioctl } for path="socket:[2753781]" dev="sockfs" ino=2753781 ioctlcmd=7704 scontext=u:r:system_server:s0 tcontext=u:r:system_server:s0 tclass=unix_stream_socket permissive=0
W/09:46:56.270 Binder_9( 5284)
type=1400 audit(0.0:74021): avc: denied { ioctl } for path="socket:[2753781]" dev="sockfs" ino=2753781 ioctlcmd=7704 scontext=u:r:system_server:s0 tcontext=u:r:system_server:s0 tclass=unix_stream_socket permissive=0
W/09:46:55.253 Binder_B( 5297)
type=1400 audit(0.0:74020): avc: denied { ioctl } for path="socket:[2744178]" dev="sockfs" ino=2744178 ioctlcmd=7704 scontext=u:r:system_server:s0 tcontext=u:r:system_server:s0 tclass=unix_stream_socket permissive=0
W/09:46:55.253 Binder_B( 5297)
type=1400 audit(0.0:74019): avc: denied { ioctl } for path="socket:[2744178]" dev="sockfs" ino=2744178 ioctlcmd=7704 scontext=u:r:system_server:s0 tcontext=u:r:system_server:s0 tclass=unix_stream_socket permissive=0
W/09:46:53.530 Binder_6( 5096)
type=1400 audit(0.0:74018): avc: denied { ioctl } for path="socket:[2744178]" dev="sockfs" ino=2744178 ioctlcmd=7704 scontext=u:r:system_server:s0 tcontext=u:r:system_server:s0 tclass=unix_stream_socket permissive=0
W/09:46:53.530 Binder_6( 5096)
type=1400 audit(0.0:74017): avc: denied { ioctl } for path="socket:[2744178]" dev="sockfs" ino=2744178 ioctlcmd=7704 scontext=u:r:system_server:s0 tcontext=u:r:system_server:s0 tclass=unix_stream_socket permissive=0
W/09:46:52.068 InputMethodManagerService( 4216)
Window already focused, ignoring focus gain of: com.android.internal.view.IInputMethodClient$Stub$Proxy@eb75754 attribute=null, token = android.os.BinderProxy@697aa79
W/09:46:52.010 InputEventReceiver(  734)
Attempted to finish an input event but the input event receiver has already been disposed.
W/09:46:50.496 Binder_C( 5315)
type=1400 audit(0.0:74016): avc: denied { ioctl } for path="socket:[2753698]" dev="sockfs" ino=2753698 ioctlcmd=7704 scontext=u:r:system_server:s0 tcontext=u:r:system_server:s0 tclass=unix_stream_socket permissive=0
W/09:46:50.496 Binder_C( 5315)
type=1400 audit(0.0:74015): avc: denied { ioctl } for path="socket:[2753698]" dev="sockfs" ino=2753698 ioctlcmd=7704 scontext=u:r:system_server:s0 tcontext=u:r:system_server:s0 tclass=unix_stream_socket permissive=0
W/09:46:47.356 Binder_B( 5297)
type=1400 audit(0.0:74014): avc: denied { ioctl } for path="socket:[2744178]" dev="sockfs" ino=2744178 ioctlcmd=7704 scontext=u:r:system_server:s0 tcontext=u:r:system_server:s0 tclass=unix_stream_socket permissive=0
W/09:46:47.356 Binder_B( 5297)
type=1400 audit(0.0:74013): avc: denied { ioctl } for path="socket:[2744178]" dev="sockfs" ino=2744178 ioctlcmd=7704 scontext=u:r:system_server:s0 tcontext=u:r:system_server:s0 tclass=unix_stream_socket permissive=0
W/09:46:47.303 Binder_A( 5285)
type=1400 audit(0.0:74012): avc: denied { ioctl } for path="socket:[2744178]" dev="sockfs" ino=2744178 ioctlcmd=7704 scontext=u:r:system_server:s0 tcontext=u:r:system_server:s0 tclass=unix_stream_socket permissive=0
W/09:46:47.303 Binder_A( 5285)
type=1400 audit(0.0:74011): avc: denied { ioctl } for path="socket:[2744178]" dev="sockfs" ino=2744178 ioctlcmd=7704 scontext=u:r:system_server:s0 tcontext=u:r:system_server:s0 tclass=unix_stream_socket permissive=0
W/09:46:47.022 OpenGLRenderer( 3881)
Incorrectly called buildLayer on View: FixedSizeImageView, destroying layer...
W/09:46:46.640 Binder_9( 5284)
type=1400 audit(0.0:74010): avc: denied { ioctl } for path="socket:[2450134]" dev="sockfs" ino=2450134 ioctlcmd=7704 scontext=u:r:system_server:s0 tcontext=u:r:system_server:s0 tclass=unix_stream_socket permissive=0
W/09:46:46.640 Binder_9( 5284)
type=1400 audit(0.0:74009): avc: denied { ioctl } for path="socket:[2450134]" dev="sockfs" ino=2450134 ioctlcmd=7704 scontext=u:r:system_server:s0 tcontext=u:r:system_server:s0 tclass=unix_stream_socket permissive=0
W/09:46:44.396 Binder_A( 5285)
type=1400 audit(0.0:74008): avc: denied { ioctl } for path="socket:[2642089]" dev="sockfs" ino=2642089 ioctlcmd=7704 scontext=u:r:system_server:s0 tcontext=u:r:system_server:s0 tclass=unix_stream_socket permissive=0
W/09:46:44.396 Binder_A( 5285)
type=1400 audit(0.0:74007): avc: denied { ioctl } for path="socket:[2642089]" dev="sockfs" ino=2642089 ioctlcmd=7704 scontext=u:r:system_server:s0 tcontext=u:r:system_server:s0 tclass=unix_stream_socket permissive=0
W/09:46:44.246 OpenGLRenderer( 3881)
Incorrectly called buildLayer on View: FixedSizeImageView, destroying layer...
W/09:46:43.830 Binder_9( 5284)
type=1400 audit(0.0:74006): avc: denied { ioctl } for path="socket:[2450134]" dev="sockfs" ino=2450134 ioctlcmd=7704 scontext=u:r:system_server:s0 tcontext=u:r:system_server:s0 tclass=unix_stream_socket permissive=0
W/09:46:43.830 Binder_9( 5284)
type=1400 audit(0.0:74005): avc: denied { ioctl } for path="socket:[2450134]" dev="sockfs" ino=2450134 ioctlcmd=7704 scontext=u:r:system_server:s0 tcontext=u:r:system_server:s0 tclass=unix_stream_socket permissive=0
W/09:46:34.103 Binder_5( 5094)
type=1400 audit(0.0:74004): avc: denied { ioctl } for path="socket:[2744178]" dev="sockfs" ino=2744178 ioctlcmd=7704 scontext=u:r:system_server:s0 tcontext=u:r:system_server:s0 tclass=unix_stream_socket permissive=0
W/09:46:34.103 Binder_5( 5094)
type=1400 audit(0.0:74003): avc: denied { ioctl } for path="socket:[2744178]" dev="sockfs" ino=2744178 ioctlcmd=7704 scontext=u:r:system_server:s0 tcontext=u:r:system_server:s0 tclass=unix_stream_socket permissive=0
W/09:46:34.003 Binder_E( 5318)
type=1400 audit(0.0:74002): avc: denied { ioctl } for path="socket:[2744178]" dev="sockfs" ino=2744178 ioctlcmd=7704 scontext=u:r:system_server:s0 tcontext=u:r:system_server:s0 tclass=unix_stream_socket permissive=0
W/09:46:34.003 Binder_E( 5318)
type=1400 audit(0.0:74001): avc: denied { ioctl } for path="socket:[2744178]" dev="sockfs" ino=2744178 ioctlcmd=7704 scontext=u:r:system_server:s0 tcontext=u:r:system_server:s0 tclass=unix_stream_socket permissive=0
W/09:46:33.429 OpenGLRenderer( 3881)
Incorrectly called buildLayer on View: FixedSizeImageView, destroying layer...
W/09:46:33.380 Binder_E( 5318)
type=1400 audit(0.0:74000): avc: denied { ioctl } for path="socket:[2450134]" dev="sockfs" ino=2450134 ioctlcmd=7704 scontext=u:r:system_server:s0 tcontext=u:r:system_server:s0 tclass=unix_stream_socket permissive=0
W/09:46:33.380 Binder_E( 5318)
type=1400 audit(0.0:73999): avc: denied { ioctl } for path="socket:[2450134]" dev="sockfs" ino=2450134 ioctlcmd=7704 scontext=u:r:system_server:s0 tcontext=u:r:system_server:s0 tclass=unix_stream_socket permissive=0
W/09:46:32.103 Binder_8( 5266)
type=1400 audit(0.0:73998): avc: denied { ioctl } for path="socket:[2642089]" dev="sockfs" ino=2642089 ioctlcmd=7704 scontext=u:r:system_server:s0 tcontext=u:r:system_server:s0 tclass=unix_stream_socket permissive=0
W/09:46:32.103 Binder_8( 5266)
type=1400 audit(0.0:73997): avc: denied { ioctl } for path="socket:[2642089]" dev="sockfs" ino=2642089 ioctlcmd=7704 scontext=u:r:system_server:s0 tcontext=u:r:system_server:s0 tclass=unix_stream_socket permissive=0
W/09:46:31.822 OpenGLRenderer( 3881)
Incorrectly called buildLayer on View: FixedSizeImageView, destroying layer...
W/09:46:31.440 Binder_D( 5316)
type=1400 audit(0.0:73996): avc: denied { ioctl } for path="socket:[2450134]" dev="sockfs" ino=2450134 ioctlcmd=7704 scontext=u:r:system_server:s0 tcontext=u:r:system_server:s0 tclass=unix_stream_socket permissive=0
W/09:46:31.440 Binder_D( 5316)
type=1400 audit(0.0:73995): avc: denied { ioctl } for path="socket:[2450134]" dev="sockfs" ino=2450134 ioctlcmd=7704 scontext=u:r:system_server:s0 tcontext=u:r:system_server:s0 tclass=unix_stream_socket permissive=0
W/09:46:30.840 Binder_B( 5297)
type=1400 audit(0.0:73994): avc: denied { ioctl } for path="socket:[2744178]" dev="sockfs" ino=2744178 ioctlcmd=7704 scontext=u:r:system_server:s0 tcontext=u:r:system_server:s0 tclass=unix_stream_socket permissive=0
W/09:46:30.840 Binder_B( 5297)
type=1400 audit(0.0:73993): avc: denied { ioctl } for path="socket:[2744178]" dev="sockfs" ino=2744178 ioctlcmd=7704 scontext=u:r:system_server:s0 tcontext=u:r:system_server:s0 tclass=unix_stream_socket permissive=0
W/09:46:29.396 Binder_5( 5094)
type=1400 audit(0.0:73992): avc: denied { ioctl } for path="socket:[2746800]" dev="sockfs" ino=2746800 ioctlcmd=7704 scontext=u:r:system_server:s0 tcontext=u:r:system_server:s0 tclass=unix_stream_socket permissive=0
W/09:46:29.396 Binder_5( 5094)
type=1400 audit(0.0:73991): avc: denied { ioctl } for path="socket:[2746800]" dev="sockfs" ino=2746800 ioctlcmd=7704 scontext=u:r:system_server:s0 tcontext=u:r:system_server:s0 tclass=unix_stream_socket permissive=0
W/09:46:29.366 Binder_B( 5297)
type=1400 audit(0.0:73990): avc: denied { ioctl } for path="socket:[2744178]" dev="sockfs" ino=2744178 ioctlcmd=7704 scontext=u:r:system_server:s0 tcontext=u:r:system_server:s0 tclass=unix_stream_socket permissive=0
W/09:46:29.363 Binder_B( 5297)
type=1400 audit(0.0:73989): avc: denied { ioctl } for path="socket:[2744178]" dev="sockfs" ino=2744178 ioctlcmd=7704 scontext=u:r:system_server:s0 tcontext=u:r:system_server:s0 tclass=unix_stream_socket permissive=0
W/09:46:28.181 ResourceType( 5026)
Overlay is broken
E/09:46:28.181 ResourceType( 5026)
idmap: no mappings
W/09:46:28.026 Binder_D( 5316)
type=1400 audit(0.0:73988): avc: denied { ioctl } for path="socket:[2744178]" dev="sockfs" ino=2744178 ioctlcmd=7704 scontext=u:r:system_server:s0 tcontext=u:r:system_server:s0 tclass=unix_stream_socket permissive=0
W/09:46:28.026 Binder_D( 5316)
type=1400 audit(0.0:73987): avc: denied { ioctl } for path="socket:[2744178]" dev="sockfs" ino=2744178 ioctlcmd=7704 scontext=u:r:system_server:s0 tcontext=u:r:system_server:s0 tclass=unix_stream_socket permissive=0
W/09:46:27.454 art     (30345)
Native thread exiting without having called DetachCurrentThread (maybe it's going to use a pthread_key_create destructor?): Thread[20,tid=30438,Native,Thread*=0xdb2f1900,peer=0x32e3e280,"CL--603723472"]
W/09:46:23.076 Binder_F(14228)
type=1400 audit(0.0:73986): avc: denied { ioctl } for path="socket:[2744178]" dev="sockfs" ino=2744178 ioctlcmd=7704 scontext=u:r:system_server:s0 tcontext=u:r:system_server:s0 tclass=unix_stream_socket permissive=0
W/09:46:23.076 Binder_F(14228)
type=1400 audit(0.0:73985): avc: denied { ioctl } for path="socket:[2744178]" dev="sockfs" ino=2744178 ioctlcmd=7704 scontext=u:r:system_server:s0 tcontext=u:r:system_server:s0 tclass=unix_stream_socket permissive=0
W/09:46:22.853 Binder_4( 4452)
type=1400 audit(0.0:73984): avc: denied { ioctl } for path="socket:[2744178]" dev="sockfs" ino=2744178 ioctlcmd=7704 scontext=u:r:system_server:s0 tcontext=u:r:system_server:s0 tclass=unix_stream_socket permissive=0
W/09:46:22.853 Binder_4( 4452)
type=1400 audit(0.0:73983): avc: denied { ioctl } for path="socket:[2744178]" dev="sockfs" ino=2744178 ioctlcmd=7704 scontext=u:r:system_server:s0 tcontext=u:r:system_server:s0 tclass=unix_stream_socket permissive=0

Logcat

Dirty Unicorns 10.6, ElementalX(from nethunter).
