### ISSUE TITLE
Csploit 2

### ISSUE THREAD

**Issue by madScript01** [cSploit/android#808]
Hey how is csploit 2 going?? hope its going well.
Any ideia of the first release date?? Im bvery curious

**Comment by maddog9696** [comment]
Im really exited to try out csploit 2. Hey @tux-mind  can we mabey get another update on development/progress. And like a rough estimate agian of when you think it might be testable? Days, weeks or months still.... (hopefully not :p).

Thankyou so much devs!!! Can't thankyou smart people enough!! <3

**Comment by cliffordfixederror** [comment]
Hey, CAN WE PLEASE GET AN UPDATE ON CSPLOIT 2??? TUXMIND told that we can expect Csploit 2 to release in december!! Now it's January and still no news?

**Comment by DeveloppSoft** [comment]
Hey, did you read [this](http://www.csploit.org/csploit_2-updates/)?
BTW, we have done a __lot__ of work on the new daemon, but we are looking for a web developer to work on the UI.

**Comment by pahapoika** [comment]
Woop Woop

**Comment by Silur** [comment]
@DeveloppSoft I am sad, I'm the frontend guy :D

**Comment by DeveloppSoft** [comment]
@Silur, sorry I thought you wanted to focus on your riffle implementation :smile:

**Comment by xaabi6** [comment]
@DeveloppSoft I think that I could be the one you are looking for. The only problem it's that I have less spare time than I would like. Nevermind, we could talk about what kind of UI you are looking for and discuss it.

**Comment by DeveloppSoft** [comment]
@xaabi6 thanks for your interest!
@Silur joined us back, so now have an ui dev, but maybe you could work together...

**Comment by xaabi6** [comment]
@DeveloppSoft no problem, I think that's better to work with somebody rather than being alone, at least for solving bugs 😅

**Comment by DeveloppSoft** [comment]
@xaabi6, we may push soon [there](https://github.com/cSploit/client), so you'll be able to make pull requests :smile:

**Comment by xaabi6** [comment]
Thanks for notifying me @DeveloppSoft . I'll have a look when you upload something 😉
