### ISSUE TITLE
Don't see devices and don't want update

### ISSUE THREAD

**Issue by xxxcrow** [cSploit/android#809]
Don't see devices and don't want update
Only on my new smartphone

**Comment by pahapoika** [comment]
Your new phone is rooted and it has busybox installed?

Can you provide More information about your phone. Such as Android version, are you using xposed and are you using custom rom.

Also you should provide logcat log.

**Comment by xxxcrow** [comment]
all installed,
android 5.1
stock firmware
(it's chinesephone))

**Comment by Ray37** [comment]
same for me. Everything was working at first then I went to routerpwn and when i came back, cSploit is only showing my phone, the subnet mask, and the router.

**Comment by plant7403** [comment]
i've already resolve this problem, but i already forget how xDDD sorry ^_^

**Comment by plant7403** [comment]
OOOH remember, replace your KINGROOT to SuperSU
Csploit working only with SuperSU!!!! REMEMBER!!!
