### ISSUE TITLE
Heart attack occured

### ISSUE THREAD

**Issue by xDeNx** [cSploit/android#811]
при самом первом запуске всё работало но потом телефон перезагрузил и при в ходе в cSploit пишет:
Heart attack occured, приложение только проверит обновления. Обновления не найдены.
Помогите пожалуйста,заранее спасибо

**Comment by MasterHelper** [comment]
at the first start it worked but then the phone rebooted and when in the course of in cSploit writes:
Heart attack occured, the app only checks for updates. No updates found.
Please help, thanks in advance

**Comment by IwraStudios** [comment]
@MasterHelper thanks for the translation

**Comment by MasterHelper** [comment]
No problem :) I don't speak russian but I know American-Russian translations are very good on Google Translate. I noticed the guy said спасибо and felt sorry :D it means thanks..

**Comment by MasterHelper** [comment]
Also @developpsoft your avatar is very cute, mind telling me where you got it? Linux right? :D

**Comment by DeveloppSoft** [comment]
@MasterHelper, thanks :blush:
I made it with gimp, and yes, that's tux (which represents Linux)

**Comment by pahapoika** [comment]
Closing since duplicated.
All futher messages should be sent in 
#828
