### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Agent47ua** [cSploit/android#816]
java.lany.NullPointenException: Attempt to invoke virtual method ' void org.csploit.android.MainActivity$TargetAdapter.notifDataSetChardet ( )' on a null object reterence

Lenovo P70-A
Android 5.1
KingRoot

**Comment by pahapoika** [comment]
KingRoot is no no.
Use supersu instead

**Comment by pahapoika** [comment]
Closing since no answer in 18-days and because error caused by incompatibility.
