### ISSUE TITLE
cannot start process/commands

### ISSUE THREAD

**Issue by micdot** [cSploit/android#817]
I keep getting those errors when trying to port scan or use service inspector. I am on v1.6.6-rc.2. The weird thing is that everything ran perfect until one day, I am not aware of anything I could have done to cause it. 

Nexus 7 tablet 2012
Supersu + busybox installed
Android 5.1.1
Kernel 3.1.10

One weird thing I did notice is that since it stopped working when I try to apt-get upgrade I'm showing that 300+ updates were kept back (not sure if related). Please help me logcat, I have aLogcat installed but it seems to only output minimal logs mainly details about admob. Not sure what I'm doing with that app.

**Comment by IwraStudios** [comment]
not related, but are you running kali nethunter?

**Comment by micdot** [comment]
Yea I'm on 3.15

**Comment by micdot** [comment]
seriously, there's nobody who can help me?

Another thing if it helps, since csploit stopped working it no longer even displays my subnet mask which is kind or weird
