### ISSUE TITLE
ruby unpacking archive error

### ISSUE THREAD

**Issue by H6LS1S** [cSploit/android#833]
##DEVICE: nomi i451

##OS version: 5.1 lmy47d

##cSploit version: all

##busybox (installed or not): not

##Rooted with supersu?
Yes

##logcat (filter it!):

**Daemon specific questions**

##Go version:

##OS:

##Using Docker (incase of unofficial build.)

##Actions performed:

#Logs:

##Issue:
*Remember to search for issues alike before creating new one.

**Comment by Nobody83** [comment]
Uhh install busybox?!?
