### ISSUE TITLE
Spoil cookies

### ISSUE THREAD

**Issue by osysltd** [cSploit/android#836]
Dear devs,
First of all thank you very much for the development, very nice soft! Is it feasible to spoil cookies so that websites trigger authentication again in the MITM module?
Regards.

**Comment by pahapoika** [comment]
Hey @osysltd 
Thank you for compliment and for nice idea. 
It should Be possible with mitm>JavaScript injection> `var deleteCookie = function (name)
{
  document.cookie = name + '=; path=/; expires=Thu, 01 Jan 1970 00:00:01 GMT;';
};`

Please let me know if you success.
~pahapoika91

**Comment by osysltd** [comment]
Thanks for the response, works fine.  A todo for collection of js injection bundles?)

**Comment by pahapoika** [comment]
@osysltd 
Actually i have few JavaScripts already made in:
https://mediafire.com/folder/z553a49pjbil5/javascripts

**Comment by osysltd** [comment]
@pahapoika 
WOW, what a nice collection, thank you very much ;) I guess the issue can be closed, meanwhile it would be nice to have a kind of shared bundles repo that could be filled in by the community easily.
