### ISSUE TITLE
Bug auto reboot 

### ISSUE THREAD

**Issue by hackerkidz** [cSploit/android#837]
##DEVICE: samsung galaxy s7

##OS version: 7.0

##cSploit version: v 1.7.0 

##busybox (installed or not): installed

##Rooted with supersu? No with magisk

##logcat (filter it!):

**Daemon specific questions**

##Go version:

##OS:

##Using Docker (incase of unofficial build.)

##Actions performed:

#Logs:

##Issue: auto reboot device when use all functions 
*Remember to search for issues alike before creating new one.

**Comment by Rubenoo** [comment]
Install SuperSU, that should fix the problem. If it doesn't make a new issue.

**Comment by hackerkidz** [comment]
Thank you very much.
