### ISSUE TITLE
MSF

### ISSUE THREAD

**Issue by ATOPJC** [cSploit/android#838]
The connection to the MSF RPC deamon keeps failing the whole time no matter what I do I have busybox installed the latest version of everything including newest busybox version and I don't know what to do now

**Comment by Rubenoo** [comment]
Do you have SuperSU installed? If not install SuperSU.  If you have SuperSU would you please send us a logcat?

**Comment by ATOPJC** [comment]
@Rubenoo don't have much logs but this is the one that popped up when the error occurred 02-19 00:04:51.971 D/CSPLOIT[core.ChildManager.onEvent](19694): received an event: StderrNewline: { line='	from /data/data/org.csploit.android/files/msf/lib/rex/socket/tcp_server.rb:29:in `create''  }02-19 00:04:51.971 D/CSPLOIT[core.ChildManager.onEvent](19694): received an event: StderrNewline: { line='	from /data/data/org.csploit.android/files/msf/lib/rex/socket/tcp_server.rb:39:in `create_param''  }02-19 00:04:51.961 D/CSPLOIT[core.ChildManager.onEvent](19694): received an event: StderrNewline: { line='	from /data/data/org.csploit.android/files/msf/lib/rex/socket.rb:47:in `create_param''  }02-19 00:04:51.961 D/CSPLOIT[core.ChildManager.onEvent](19694): received an event: StderrNewline: { line='	from /data/data/org.csploit.android/files/msf/lib/rex/socket/comm/local.rb:33:in `create''  }02-19 00:04:51.961 D/CSPLOIT[core.ChildManager.onEvent](19694): received an event: StderrNewline: { line='	from /data/data/org.csploit.android/files/msf/lib/rex/socket/comm/local.rb:192:in `create_by_type''  }02-19 00:04:51.961 D/CSPLOIT[core.ChildManager.onEvent](19694): received an event: StderrNewline: { line='/data/data/org.csploit.android/files/msf/lib/rex/socket/comm/local.rb:198:in `rescue in create_by_type': The address is already in use or unavailable: (127.0.0.1:55553). (Rex::BindFailed)'  }02-19 00:04:51.961 D/CSPLOIT[core.ChildManager.onEvent](19694): received an event: StderrNewline: { line='[*] MSGRPC starting on 127.0.0.1:55553 (NO SSL):Msg...'  }02-19 00:04:51.961 D/CSPLOIT[core.ChildManager.onEvent](19694): received an event: StderrNewline: { line='WARNING: Nokogiri was built against LibXML version 2.7.8, but has dynamically loaded 20708.3.58'  }02-19 00:04:51.961 D/CSPLOIT[core.ChildManager.onEvent](19694): received an event: StderrNewline: { line='WARNING: linker: /data/data/org.csploit.android/files/ruby/lib/ruby/gems/1.9.1/gems/nokogiri-1.6.0-arm-linux/lib/nokogiri/nokogiri.so: unused DT entry: type 0xf arg 0x12dc5'  }02-19 00:04:51.731 W/CSPLOIT[services.MsfRpcdService.connect](19694): java.net.SocketException: recvfrom failed: ECONNRESET (Connection reset by peer)02-19 00:04:51.991 D/CSPLOIT[core.ChildManager.dispatchEvent](19694): Child #48 exited ( exitValue=1 )02-18 23:59:58.581 D/ApplicationPolicy(2748): isStatusBarNotificationAllowedAsUser: packageName = org.csploit.android,userId = 0

**Comment by pahapoika** [comment]
Why cant you guys fill the fking template there is when you are opening issue

**Comment by pahapoika** [comment]
Closing.

Open new with the template filled of issue persists.

**Comment by xaitax** [comment]
It's also possible to just write **one** message instead of 238974234 in each thread.
