### ISSUE TITLE
If user goes back to main screen there is no information or warning if current processes are running.

### ISSUE THREAD

**Issue by Interneedus** [cSploit/android#84]
a) Warn the user if anything will be closed(/killed) if the user leaves the screen
b) Make it possible to leave a process (scanner etc.) running when leaving the screen
c) Display the loading bar alinged properly and instead of throwing the user back to previous view, display the log (what is executed and what's the result, the same output you'd get when doing this on a linux machine).

**Comment by 0MazaHacka0** [comment]
I dont know. On 1.5.0 version if i go back and return i see all information.

**Comment by Interneedus** [comment]
Most of them lose the state or stop running properly.
