### ISSUE TITLE
DNSpoof Error

### ISSUE THREAD

**Issue by ghost** [cSploit/android#844]
##DEVICE: SM-920F (galaxy s6)

##OS version:6.0.1

##cSploit version:1.6.6-rc.2

##busybox (installed or not): installed

##Rooted with supersu? Yes

I don't know if it's an error or it just got fixed, but after i input the dns spoof and run it my pc starts giving and error on the target website. I used credential harvester and used a twitter template on my nethunter terminal and then spoofed the dns, with Twitter link and with my local ip, but when i go to twitter on my computer, it says "connection refused".

P.S: I've kali nethunter running on my device

Any fix??
Thanks in advance

**Comment by pahapoika** [comment]
No logcat no help.

It's not so hard to install logcat Extreme, Grant it root permission and the filtering it to "csploit".

**Comment by ghost** [comment]
Ok, I've learned how to actually use dnsspoof module, the app don't have any problems, sorry my bad :(
