### ISSUE TITLE
Isnt install core

### ISSUE THREAD

**Issue by veka0** [cSploit/android#845]
##DEVICE: samdung i9300i

##OS version: amdroid 4.4(rooted)

##cSploit version:

##busybox (installed or not):

##Rooted with supersu?

##logcat (filter it!):

**Daemon specific questions**

##Go version:

##OS:

##Using Docker (incase of unofficial build.)

##Actions performed:

#Logs:

##Issue:
*Remember to search for issues alike before creating new one.

**Comment by pahapoika** [comment]
Provide more info (like whether you have BusyBox and SuperSU installed or not.)

Also Logcat is crucial when we are analyzing error(s).
