### ISSUE TITLE
Problem with cSploit

### ISSUE THREAD

**Issue by veka0** [cSploit/android#846]
##DEVICE: samdung i9300i

##OS version: amdroid 4.4(rooted)

##cSploit version: 1.6.6-rc.2

##busybox (installed or not):install

##Rooted with supersu? No, with KingRoot

##logcat (filter it!):??

**Daemon specific questions**

##Go version:??

##OS: android 4.4

##Using Docker (incase of unofficial build.)

##Actions performed:

#Logs:

##Issue:
*Remember to search for issues alike before creating new one.

**Comment by veka0** [comment]
Pls help!!

**Comment by veka0** [comment]
*samsung

**Comment by veka0** [comment]
*android

**Comment by sorano** [comment]
Use SuperSu instead of KingoRoot and learn how to create a proper bug report.
