### ISSUE TITLE
Nexus 5 MITM

### ISSUE THREAD

**Issue by ghost** [cSploit/android#848]
##DEVICE:
Nexus 5

##OS version:
6.0.1

##cSploit version:
1.7.0

##busybox (installed or not):
Y

##Rooted with supersu?
Y

##logcat (filter it!):

**Daemon specific questions**

##Go version:

##OS:

##Using Docker (incase of unofficial build.)

##Actions performed:

#Logs:

##Issue:
Everything I read makes me believe my device should be avle to use csploit but I cannot perform any MITM attacks .

I know its because it cannot activate monitor mode. For my device I have to use LD_PRELOAD ioctl_interceptor to activate monitor mode in the terminal which does work. I also use hijacker/reaver fine.

I have nexmon installed which I can't seem to get even airodump to work in it. Is nexmon suppose to activate monitor mode system wide or justin the app? Not sure if this is why csploit can't capturr and inject packets.

**Comment by pahapoika** [comment]
@mic-dot Hey!
cSploit uses ARP-poisoning.
So activating monitor mode (which is usually impossible on Qualcomm chips) is not required and may cause errors.

I suggest to uninstall nexmon and not to active monitor mode when you use cSploit.

Can you take Logcat (Download Logcat Extreme from Google play store and filter csploit so we can analyze the error.


Thank you!

Edit: Also how you are using cSploit 1.7.0 since 1.6.6 RC2 is latest?

**Comment by IwraStudios** [comment]
@pahapoika monitor mode is enabled by the nexmon project, a patch for the drivers
but putting it into monitor mode is indeed not reqeuired

**Comment by pahapoika** [comment]
@IwraStudios Sounds pretty neat.

But anyways. It shouldnt affect MiTM on cSploit since on my understanding cSploit uses ARP-poisoning?

**Comment by ghost** [comment]
@pahapoika

Well that is very interesting to hear, so i downloaded 1.6.6 and installed and everything is perfect now. Very odd...

Just to prove I'm not crazy:
http://i64.tinypic.com/28am96s.jpg
(Sorry on mobile)

Thanks all for the quick replies

**Comment by mic-dot** [comment]
@pahapoika

Well that is very interesting to hear, so i downloaded 1.6.6 and installed and everything is perfect now. Very odd...

Just to prove I'm not crazy:
[IMG]http://i64.tinypic.com/28am96s.png[/IMG]

Thanks all for the quick replies

**Comment by pahapoika** [comment]
@ghost where did you download the 1.7.0 app from?
