### ISSUE TITLE
Core does not install ZTE

### ISSUE THREAD

**Issue by Sadrien** [cSploit/android#852]
##DEVICE:ZTE dous core will not install.

##OS version:

##cSploit version:

##busybox (installed or not):

##Rooted with supersu?

##logcat (filter it!):

**Daemon specific questions**

##Go version:

##OS:

##Using Docker (incase of unofficial build.)

##Actions performed:

#Logs:

##Issue:
*Remember to search for issues alike before creating new one.

**Comment by pahapoika** [comment]
No information regarding SuperSU, Busybox, cSploit or Android OS.

Closing...

Feel free to open with necessary information included.
