### ISSUE TITLE
cSploit 2 Update!?

### ISSUE THREAD

**Issue by maddog9696** [cSploit/android#853]
Hey wonderful devs!!
To start, you deserve so many thanks from the community! So on behalf of the community, I THANK YOU SO MUCH! We love you guys!
I'm writing today to see if we can get an update on the development process. Are we nearing a usable cSplot 2 build yet? Any time estimations or expected dates for anything? Its been a while since the last update so im very curios! I'm very exited to start playing with the app! Also how did/is your studying going @tux-mind ?

**Comment by tux-mind** [comment]
Hi Michael, I've just wrote to a blogger about me and cSploit, i'll copy here few words of that email:

> Actually I'm working on cSploit few hours per week ( ~2 ).
> Starting from this month ( April ) I've reduced my weekly working hours from 24 to 16.
> Thus I expect to find more time for cSploit in the next weeks :)
> 
> ...
>
> The great news is that I'm finally purchasing a new motorbike ( Aprilia RSV4 aPRC - 2012 ).
> I've made a financing to support my huge buy, but now I can stop doing all those extra jobs :)

The development status it's quite stalled, I've made some bugfix last week.
As you just read I plan to spend more time on cSploit in the near future, in these days I'm busy with banks, insurance companies and alike :confounded: 

My studies goes well, not as I expect but I'm doing a good job considering that I'm also working :stuck_out_tongue_closed_eyes: 

Thanks for your interest :blush:

**Comment by theoneandonly-vector** [comment]
sadly still no update :(

**Comment by pahapoika** [comment]
@theoneandonly-vector
The team has been busy, but there's internal challenge of getting alpha build out on August.

The development is anything but dead.

#longlivecSploit

**Comment by theoneandonly-vector** [comment]
nice to hear :)
