### ISSUE TITLE
Csploit2

### ISSUE THREAD

**Issue by evertking** [cSploit/android#854]
##DEVICE:
Oneplus

##OS version:7

##cSploit version:

##busybox (installed or not):

##Rooted with supersu?

##logcat (filter it!):

**Daemon specific questions**

##Go version:

##OS:

##Using Docker (incase of unofficial build.)

##Actions performed:

#Logs:

##Issue:
*Remember to search for issues alike before creating new one.
Sorry but don't know where to ask. But is csploit 2 still gonna happen?

**Comment by IwraStudios** [comment]
csploit 2 is still happening see issue #853

**Comment by pahapoika** [comment]
As iwra said.

Also remember to keep eye on http://www.csploit.org/news/ for updates regarding cSploit.
