### ISSUE TITLE
Cannot update Ruby 

### ISSUE THREAD

**Issue by dusasrikanth** [cSploit/android#861]
##DEVICE:Alcatel Touch Pop c1 4015D

##OS version: Android v4.2.2 

##cSploit version:1.6.6

##busybox (installed or not):

##Rooted with supersu?

##logcat (filter it!):

**Daemon specific questions**

##Go version:

##OS:

##Using Docker (incase of unofficial build.)

##Actions performed:

#Logs:

##Issue:
*Remember to search for issues alike before creating new one.

**Comment by pahapoika** [comment]
Closing as duplicated
