### ISSUE TITLE
not work properly

### ISSUE THREAD

**Issue by devdjena** [cSploit/android#862]
##DEVICE:

##OS version:

##cSploit version:

##busybox (installed or not):

##Rooted with supersu?

##logcat (filter it!):

**Daemon specific questions**

##Go version:

##OS:

##Using Docker (incase of unofficial build.)

##Actions performed:

#Logs:

##Issue:
*Remember to search for issues alike before creating new one.

**Comment by pahapoika** [comment]
Hey @devdjena

You must fill all questions above (Not Docker specific if you are not running cSploit on Docker)

**Comment by Silur** [comment]
closing due to lack of update
