### ISSUE TITLE
"Heart attack occurred" Asus ZenFone 5 (A500KL)

### ISSUE THREAD

**Issue by SAVILIA** [cSploit/android#869]
##DEVICE:
Asus ZenFone 5 (A500KL)

##OS version:
Android 5.0 Lolliopop

##cSploit version:
1.6.6 RC2

##busybox (installed or not):
Installed

##Rooted with supersu?
No. Rooted with Kingroot

##logcat (filter it!):
05-12 18:28:02.537683 961 1783 I ActivityManager: START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=org.csploit.android/.MainActivity bnds=[32,181][196,401] (has extras)} from uid 10012 on display 0

05-12 18:28:02.634301 961 1042 I ActivityManager: Displayed org.csploit.android/.MainActivity: +72ms

05-12 18:28:04.265310 1795 1795 W PackageManager: Failure retrieving resources for org.csploit.android: Resource ID #0x0

05-12 18:28:04.354336 1795 1795 W PackageManager: Failure retrieving resources for org.csploit.android: Resource ID #0x0

**Daemon specific questions**

##Actions performed:
Log into the application.

##Issue:
[Log_2017-05-12_18-36-26.txt](https://github.com/cSploit/android/files/997232/Log_2017-05-12_18-36-26.txt)

At the first login, the application updates the kernel, after which the text "Heart attack occurred" appears. The superuser rights for the application are provided.

**Comment by AlA777** [comment]
cSploit on Intel platform is not working. I tryed on Tooj/Toof too, and on tf103c without success.

**Comment by pahapoika** [comment]
Hey @SAVILIA
Heartattack is caused by Kingroot. It misses some SU libraries that cSploit uses.

I don't have information regarding Intel support on cSploit, but I do know that cSploit 2 will support X86 architecture.

**Comment by SAVILIA** [comment]
When will cSploit 2 be ready?

**Comment by pahapoika** [comment]
@SAVILIA Please see #871
