### ISSUE TITLE
Alias's for devices disapear upon closing and reopening app

### ISSUE THREAD

**Issue by TheRollingEdit** [cSploit/android#87]
Everytime I leave an alias for a device and i quit csploit, when i come back, the alias is gone. Is there any way to fix this so the alias's are kept?

**Comment by tux-mind** [comment]
just press home instead of back :wink: 

  - pressing back twice will **close** cSploit
  - pressing home will leave it in the background

feel free to reopen the issue if you think that I'm wrong.
thanks for the report anyway :blush:
