### ISSUE TITLE
Can't use the app properly

### ISSUE THREAD

**Issue by saloniamatteo** [cSploit/android#872]
##DEVICE: Samsung Galaxy A5

##OS version: 5.0.2

##cSploit version: Latest

##busybox (installed or not): yes

##Rooted with supersu? Yes, but with Kingroot

##logcat (filter it!): wut?

**Daemon specific questions**

##Go version: idk

##OS: idk

##Using Docker (incase of unofficial build.) Idk

##Actions performed: idk

#Logs: idk

##Issue: 
I open the app, I add a new target and nothing appens.
*Remember to search for issues alike before creating new one.

**Comment by pahapoika** [comment]
Kingroot=No support.
I suggest to switch to SuperSU.

**Comment by saloniamatteo** [comment]
Doesn't still work. I have SuperSU but I don't know how to set it up without harming my device.

**Comment by saloniamatteo** [comment]
Do you know what can I do?

**Comment by pahapoika** [comment]
So you have already successfully rooted with superSu and removed kingroot?
