### ISSUE TITLE
no sirve

### ISSUE THREAD

**Issue by caceres82** [cSploit/android#877]
##DEVICE:RYXIfv2vHIrd7hmk

##OS version:

##cSploit version:

##busybox (installed or not):

##Rooted with supersu?

##logcat (filter it!):

**Daemon specific questions**

##Go version:

##OS:

##Using Docker (incase of unofficial build.)

##Actions performed:

#Logs:

##Issue:
*Remember to search for issues alike before creating new one.

**Comment by Silur** [comment]
duplicate of #876
