### ISSUE TITLE
Eternalblue and doublepulsar, how to install in csploit?

### ISSUE THREAD

**Issue by jlucaso** [cSploit/android#882]
DEVICE:L70

OS version:4.4.2

**cSploit version:**

**busybox** *(installed or not):*

**Rooted with supersu?**

**logcat** *(filter it!):*
[How-to guide](https://forum.xda-developers.com/showthread.php?t=1726238)

------------------------------------------------------------------------------------------------------------------------------

**Daemon specific questions**

Go version:

OS:

Using Docker (incase of unofficial build.)

Actions performed:

Logs:
------------------------------------------------------------------------------------------------------------------------------

**Issue:**
How to install eternalblue and doublepulsar in csploit?

**Comment by pahapoika** [comment]
Hey @jlucaso! Currently it's not possible on cSploit.
