### ISSUE TITLE
Potentially Virus. Reported by ESET on installation process

### ISSUE THREAD

**Issue by ctoor** [cSploit/android#905]
DEVICE:
Huawai P9 lite

OS version:
Android 7

**cSploit version:**
1'6'5

**busybox** *(installed or not):*

No
**Rooted with supersu?**
No

**logcat** *(filter it!):*
[How-to guide](https://forum.xda-developers.com/showthread.php?t=1726238)

------------------------------------------------------------------------------------------------------------------------------

**Daemon specific questions**

Go version:

OS:

Using Docker (incase of unofficial build.)

Actions performed:

Logs:
------------------------------------------------------------------------------------------------------------------------------

**Issue:**
*Remember to search for issues alike before creating new one!*

**Comment by pahapoika** [comment]
Hey @ctoor
Csploit apks downloaded from fdroid or from https://github.com/cSploit/android/releases are not viruses. 
If you think that those builds may include something suspicious you can always build your own app directly from source. That way you know exactly what's in the app.
