### ISSUE TITLE
Unable to upgrade core.

### ISSUE THREAD

**Issue by leamlidara** [cSploit/android#909]
DEVICE: 
sm-n920c

OS version:
Android 7.0

**cSploit version:**
1.6.6 rc-2

**busybox** *(installed or not):*
Yes

**Rooted with supersu?**
Yes

**logcat** *(filter it!):*
[How-to guide](https://forum.xda-developers.com/showthread.php?t=1726238)

------------------------------------------------------------------------------------------------------------------------------
--------- beginning of main
W/InputEventReceiver(11950): Attempted to finish an input event but the input event receiver has already been disposed.
D/InputTransport(11950): Input channel destroyed: fd=59
D/InputTransport(11950): Input channel constructed: fd=52
D/ViewRootImpl@3092110[Toast](11950): setView = android.widget.LinearLayout{5562409 V.E...... ......I. 0,0-0,0} touchMode=true
D/ViewRootImpl@3092110[Toast](11950): dispatchAttachedToWindow
D/ViewRootImpl@3092110[Toast](11950): Relayout returned: oldFrame=[0,0][0,0] newFrame=[257,1636][822,1752] result=0x27 surface={isValid=true 518121028608} surfaceGenerationChanged=true
D/ViewRootImpl@3554e07[LogActivity](11950): MSG_WINDOW_FOCUS_CHANGED 1
V/InputMethodManager(11950): Starting input: tba=android.view.inputmethod.EditorInfo@c9e460e nm : org.jtb.alogcat ic=null
I/InputMethodManager(11950): [IMM] startInputInner - mService.startInputOrWindowGainedFocus
D/InputTransport(11950): Input channel constructed: fd=59
D/InputTransport(11950): Input channel destroyed: fd=53
E/ViewRootImpl(11950): sendUserActionEvent() mView == null
D/ViewRootImpl@3092110[Toast](11950): MSG_RESIZED_REPORT: ci=Rect(0, 0 - 0, 0) vi=Rect(0, 0 - 0, 0) or=1
V/InputMethodManager(11950): Starting input: tba=android.view.inputmethod.EditorInfo@86eee40 nm : org.jtb.alogcat ic=null
I/InputMethodManager(11950): [IMM] startInputInner - mService.startInputOrWindowGainedFocus
D/InputTransport(11950): Input channel constructed: fd=60
D/InputTransport(11950): Input channel destroyed: fd=59
D/ViewRootImpl@3092110[Toast](11950): dispatchDetachedFromWindow
D/InputTransport(11950): Input channel destroyed: fd=52
D/ViewRootImpl@3554e07[LogActivity](11950): MSG_WINDOW_FOCUS_CHANGED 0
D/InputTransport(11950): Input channel destroyed: fd=60
D/ViewRootImpl@3554e07[LogActivity](11950): Relayout returned: oldFrame=[0,0][1080,1920] newFrame=[0,0][1080,1920] result=0x5 surface={isValid=false 0} surfaceGenerationChanged=true
D/ViewRootImpl@3554e07[LogActivity](11950): Relayout returned: oldFrame=[0,0][1080,1920] newFrame=[0,0][1080,1920] result=0x5 surface={isValid=false 0} surfaceGenerationChanged=false
D/ViewRootImpl@3554e07[LogActivity](11950): Relayout returned: oldFrame=[0,0][1080,1920] newFrame=[0,0][1080,1920] result=0x1 surface={isValid=false 0} surfaceGenerationChanged=false
D/ViewRootImpl@3554e07[LogActivity](11950): Relayout returned: oldFrame=[0,0][1080,1920] newFrame=[0,0][1080,1920] result=0x3 surface={isValid=true 518418434560} surfaceGenerationChanged=true
D/InputTransport(11950): Input channel constructed: fd=53
D/ViewRootImpl@a545f04[Toast](11950): setView = android.widget.LinearLayout{bf7dced V.E...... ......I. 0,0-0,0} touchMode=true
D/ViewRootImpl@a545f04[Toast](11950): dispatchAttachedToWindow
D/ViewRootImpl@a545f04[Toast](11950): Relayout returned: oldFrame=[0,0][0,0] newFrame=[257,1636][822,1752] result=0x27 surface={isValid=true 518121028608} surfaceGenerationChanged=true
D/ViewRootImpl@3554e07[LogActivity](11950): MSG_WINDOW_FOCUS_CHANGED 1
V/InputMethodManager(11950): Starting input: tba=android.view.inputmethod.EditorInfo@a277722 nm : org.jtb.alogcat ic=null
I/InputMethodManager(11950): [IMM] startInputInner - mService.startInputOrWindowGainedFocus
D/InputTransport(11950): Input channel constructed: fd=59
D/ViewRootImpl@a545f04[Toast](11950): MSG_RESIZED_REPORT: ci=Rect(0, 0 - 0, 0) vi=Rect(0, 0 - 0, 0) or=1

**Daemon specific questions**
I found that application is trying to download file core-v1.0.11.android16.armeabi-v7a.tar.xz with 4772948 bytes. But I don't know why it show update core fail. This problem occore on all version of cSploit which are available.
Go version:

OS:

Using Docker (incase of unofficial build.)

Actions performed:

Logs:
------------------------------------------------------------------------------------------------------------------------------

**Issue:**
*Remember to search for issues alike before creating new one!*

**Comment by r1riyad** [comment]
Can i Know ur SuperSU version.?? r u using the version 2.82??? 
then try this fix...
Install superSU 2.79 by zip flashing..then goto busybox and install it in /su/xbin or /su/bin
then try again to install csploit.
I had the same issue with supersu 2.82

**Comment by leamlidara** [comment]
Thanks, I will try.
