### ISSUE TITLE
I can provide help

### ISSUE THREAD

**Issue by Check-mate** [cSploit/android#91]

**Comment by Check-mate** [comment]
I appreciate your enthusiasm for this project and like me you're still a student (computer I guess). I have some ideas that may be able to interest you and can improve this project. You will continue to maintain cSploit in 4-5 months?

**Comment by tux-mind** [comment]
I @Check-mate , I really need some help.
I have to graduate in July and work for pay the food, my free time is very low.

ATM I want to maintain the project forever, I want to bring it to a stable point, then start developing many cool features like using USB WiFi dongles, injecting backdoor on infected machines and so on.

**Comment by sorano** [comment]
@Check-mate 
cSploit development have been resumed recently.
Please drop by #csploit at irc.freenode.net if you want to discuss and help with development.
