### ISSUE TITLE
about  csploit 2

### ISSUE THREAD

**Issue by cobrax1** [cSploit/android#910]
DEVICE:tecno m3 

OS version: android 4.2

**cSploit version:**
1.6

**busybox** *installed 

**Rooted with supersu?** yes
 well first i think  csploit is getting old  i thing there was a long time without a new  release  , and i think this tool is great  but  the old tool doesn't have  much options  , we're waiting for the new update plz  give us  a date or something.....

**Comment by pahapoika** [comment]
All discussion regarding cSploit 2 should be kept in one separate thread, which is #896
