### ISSUE TITLE
Cant link java to jni [Solved]

### ISSUE THREAD

**Issue by e2002e** [cSploit/android#928]
Nexus One
Android 2.3.7
Kernel cyanogen (found on needrom)
super su
busybox

Hi, I can install and run the cSploit apk found on the website (even though the size of my mmc can't allow for a msf) it is all functional but for the login cracker module which I have never seen running fine.
I wondered why and think I spot a bug in the code so I went on and correct it but when compiling with the default and after trying different settings for the min sdk and target sdk I find out the program is getting stuck when updating the core. I got the file - that is about 5mb - on the sdcard but the program just restarts when finishing downloads, at the step of verification. Any clue ?

The stacktrace points to the function Client.Disconnect invoqued by system.Clear() it seems like i'm missing the jni libraries but then don't compile because the .mk are missing from the folders and there is no 'configure' file. I came half-way by using the build-nighlty script which downloaded the libs for me but i still can't build because three .mk are missing:
build/core/build-host-executable.mk
/build/core/build-host-shared-library.mk
/build/core/build-host-static-library.mk

Now i have the libs but I still can't link functions for Client.Activity that appear in red in the editor, but don't stop the apk from compiling so that is the point where the program gives up when runing

**Comment by e2002e** [comment]
Needed to compile the jni libs.
-in the android folder -> ./gradlew && ./gradlew assemble (make sure **jdk** is in your path)
-in android/cSploit/jni -> ./build (make sur **ndk** is in your path)
-in android-studio, DONT update gradle and build apk. Done
In the version I recompiled, a little modification allows the login cracker to use hydra's -x option which was not working.
[Edit] the nightly-build.sh scripts automates everything here provided the jdk and ndk are in your path, and it will automatically fetch the required jni files that are not included with a simple git clone command.

**Comment by SuperOP535** [comment]
Please close solved issues
