### ISSUE TITLE
cannot find a core fore devis

### ISSUE THREAD

**Issue by freddL** [cSploit/android#93]
Hi,
i have a motorola G 4G xt1039 when I start cSploit release 1.4.1, this message print :
"cannot find a core fore devis"

My phone is root and I use Bliss Pop ROM 5.0.2 based CyanogenMod

**Comment by Avamander** [comment]
Try newer version.

**Comment by sorano** [comment]
Try out the latest version with updated supersu and busybox installed in the correct path.
Then if it is not working put the logfiles on pastebin and reopen the issue.
