### ISSUE TITLE
Redmi note 4x

### ISSUE THREAD

**Issue by longkutis** [cSploit/android#937]
DEVICE:Xiaomi redmi note 4x

OS version:android 7.1

**cSploit version:**

**busybox** *(installed or not):*

**Rooted with supersu?**

**logcat** *(filter it!):*
[How-to guide](https://forum.xda-developers.com/showthread.php?t=1726238)

------------------------------------------------------------------------------------------------------------------------------

**Daemon specific questions**

Go version:

OS:

Using Docker (incase of unofficial build.)

Actions performed:

Logs:
------------------------------------------------------------------------------------------------------------------------------

**Issue:**
*Remember to search for issues alike before creating new one!*

**Comment by pahapoika** [comment]
Hey @longkutis
Thanks for kindly ignoring everything but Device name and OS version. Sadly i failed to negotiate telepathic connection with neither your nor your device, so please provide more information.
