### ISSUE TITLE
Cannot start process

### ISSUE THREAD

**Issue by Alpibrine28** [cSploit/android#94]
It still keeps giving cannot start process error while trying to start Metasploit RPCD on Note 3. Please fix it.

**Comment by greensmith** [comment]
this is also happening to me, with 1.4.5, on Galaxy S2.

http://hastebin.com/igowejubik.tex

I also, occasionally, get 'encounted an error' when loading the application

**Comment by Avamander** [comment]
What version of cSploit?

**Comment by greensmith** [comment]
1.4.5. But i've just updated to 1.4.6, Same issues.
I have a feeling this, and other issues I experience,  might be something to do with ruby. 
It does not seem to run properly at all, even when manually trying to run it from console. 

```bash
root@GT-I9100:/storage/sdcard0 # ruby -v
ruby 1.9.3p546 (2014-03-31) [arm-linux-androideabi]
root@GT-I9100:/storage/sdcard0 # ruby hello.rb
<internal:gem_prelude>:1:in `require': cannot load such file -- rubygems.rb (LoadError)
        from <internal:gem_prelude>:1:in `<compiled>'
```

just wondering if the ruby is either not installed properly or not compatible with the device.

**Comment by Systemad** [comment]
@greensmith I'm having the same response when ./ruby -v
My guess is that the installation is corrupted.

**Comment by Alpibrine28** [comment]
I realized that it also happens after updating ruby, and it always fails to download core.

**Comment by Alpibrine28** [comment]
And yes, ruby also fails to start.

**Comment by sorano** [comment]
Try out the latest version with updated supersu and busybox installed in the correct path.
Then if it is not working put the logfiles on pastebin and reopen the issue.
