### ISSUE TITLE
Core is not installed, how to install it? 

### ISSUE THREAD

**Issue by sourabhkoli121** [cSploit/android#942]
DEVICE:Samsung Galaxy Tab 4

OS version: android 4.4.2

**cSploit version:** 1.6.6 RC2

**busybox** *(installed or not):* installed

**Rooted with supersu?** yes

**logcat** *(filter it!):*
[How-to guide](https://forum.xda-developers.com/showthread.php?t=1726238)

------------------------------------------------------------------------------------------------------------------------------

**Daemon specific questions**

Go version:

OS:

Using Docker (incase of unofficial build.)

Actions performed:

Logs:
------------------------------------------------------------------------------------------------------------------------------

**Issue:**
*Remember to search for issues alike before creating new one!*

**Comment by alphaomicron** [comment]
It should automatically ask you to install core.Have you granted root permission?

**Comment by pahapoika** [comment]
@sourabkholi121 please add logcat and provide information about the behavior of the app. thanks

**Comment by Aayushkumar1020** [comment]
Is this app requires root permission?
