### ISSUE TITLE
Metasploit don't start

### ISSUE THREAD

**Issue by qweered** [cSploit/android#985]
DEVICE: Xiaomi mi a2 lite

OS version: 9.0

**cSploit version:**
1.7.0

**busybox** *(installed or not):* installed

**Rooted with supersu?** With Magisk

**logcat** *(filter it!):*
[How-to guide](https://forum.xda-developers.com/showthread.php?t=1726238)

------------------------------------------------------------------------------------------------------------------------------

**Daemon specific questions**

Go version:

OS:

Using Docker (incase of unofficial build.)

Actions performed: update msf

Logs:
------------------------------------------------------------------------------------------------------------------------------

**Issue:**

**Comment by fat-tire** [comment]
Logs?
