### ISSUE TITLE
Starting Metasploit RPCD... No progress

### ISSUE THREAD

**Issue by ghost** [cSploit/android#996]
DEVICE:
Samsung Galaxy S8+

OS version:
Android Nougat 7.0

**cSploit version:**
cSploit v1.7.0-unstable+70268d9

**busybox** *(installed or not):*
Installed in /system/bin

**Rooted with supersu?**
Correct

**logcat** *(filter it!):*
How do i do this correctly?

------------------------------------------------------------------------------------------------------------------------------

**Daemon specific questions**

Go version:
I don't know what this means

OS:
I don't know what to put here

Using Docker (incase of unofficial build.)
?
Actions performed:
??

Logs:
------------------------------------------------------------------------------------------------------------------------------

**Issue:**
While attempting to start Metasploit RPCD it is static and says "Starting Metasploit RPCD. Standby..." for about a minute then says "MSF RPC daemon killed" and doesn't work.

Any help would be awesome!
Thank you!
Cyanide

**Comment by laithalshabi** [comment]
the same error

**Comment by L1LJ3PPE** [comment]
Same..

**Comment by Gamekiller17** [comment]
Same problem

**Comment by emlinhax** [comment]
I have the Problem too, but your Problem may be that you installed busybox in the wrong location. SuperSU is installed in /sbin/ by default.. and you have installed busybox in /SYSTEM/sbin/
Try to reinstall busybox in /sbin/
